### ISSUE TITLE
cleanup cmdline pci device selection by vendor/device ids

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#101]
hwloc-calc and friends support specifying pci device by device/vendor ids:
  $ hwloc-calc pci:8086:3b2f
The device or vendor id may be omitted for a wildcard, an optional index may even be added in case of multiple matches:
  $ hwloc-calc pci:3b2f::2

This has never been documented for some reason. And that's good because the syntax looks like core:2:3 which means something totally different (3 cores start with the second one).

The original intent of the syntax was to ease selection of devices that have no OS devices. For instance NVIDIA GPUs. Now that we have the cuda component, it doesn't matter much anymore.

If we still want to support something like this (and document it), we should likely change the syntax. Could be something similar to lspci vendor/device display **pci[vendor:device]:index** (Brice has a patch to do that). Could also be **pci=[vendor:device]:index** to follow the existing **pci=busid** or **os=name** syntax.

**Comment by bgoglin** [comment]
This is basically fixed now, but not documented.
