### ISSUE TITLE
some osdev without pcidev when no PCI backend

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#102]
The usual way to add OS device is to detect PCI devices with the PCI backend, and ask other backends if they have any OS device to add under a given PCI device.

Backends such as Cuda and OpenCL could work the other way: they list their devices, and tell the core "I need a PCI device whose bus id is xx:yy.z". If the PCI backend isn't available, we can't create a fully-configured PCI device, but the OS may still be able to retrieve its locality (Linux can). So we could still add the OS device at the right place in the topology.

So basically these backends would define both the discover() and notify_new_obj() callback. discover() would try to insert all devices that were not inserted by notify_new_obj() earlier.

Issues:
* notify_new_obj() and get_obj_cpuset() callbacks want a PCI device object, and we cannot really create one without the PCI backend. Either we create a fake PCI object. Or we modify the callback to accept a bus ID instead of a full object, but these callbacks are not supposed to be PCI specific, they could be used for other types.
* in normal cases, Cuda/OpenCL are loaded last, so their discover() will be called after notify_new_obj() had a chance to be called. But if one changes default component priorities, discover() may be called early, causing the new fallback code to run before notify_new_obj() had a chance to do the full PCI thing. Having a special discover() that is guaranteed to be called at the end of the discovery could help.
* can we insert a OS device in the topology without a bridge and a pci device above it?

First, let's wait and see if people complain about missing I/O devices because of missing PCI headers.

**Comment by bgoglin** [comment]
This is supported in master since ba7307939bd022f9064edb74522f24c5cee29ee8
