### ISSUE TITLE
more "nofile" info in fsroot topologies

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#109]
The is_thissystem flag was added to enable/disable binding when loading topology dumps or XML. It was later extended to detect whether Linux syscalls are OK while running the Linux or x86 discovery on a topology dump. We may actually remove all the later by storing everything needed in /proc/hwloc-nofile-info. This will make the code much more simple and will simplify gather topology (users are confused when hwloc-gather-topology generates an incomplete lstopo output because HWLOC_THISSYSTEM=0).

What's needed is to add the following to /proc/hwloc-nofile-info:
- hwloc_getpagesize()
- sysconf(_SC_LARGE_PAGESIZE)
- hwloc_fallback_nbprocessors(topology)

We may also want to improve the Architecture field in hwloc-cpuid-info file so that we can replace uname when loading a cpuid dump too.

**Comment by bgoglin** [comment]
sysconf(_SC_LARGE_PAGESIZE) isn't needed anymore. Others are already dumped.
