### ISSUE TITLE
Warning with pci-common.c on OS X

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/hwloc#122]
Getting this warning from clang on OS X in hwloc/src/pci-common.c (probably would also show up with clang on Linux, too):

```
pci-common.c:252:7: warning: variable 'parent' is used uninitialized whenever
      'if' condition is false [-Wsometimes-uninitialized]
  if (group_obj) {
      ^~~~~~~~~
pci-common.c:282:10: note: uninitialized use occurs here
  return parent;
         ^~~~~~
pci-common.c:252:3: note: remove the 'if' if its condition is always true
  if (group_obj) {
  ^~~~~~~~~~~~~~~
pci-common.c:219:32: note: initialize the variable 'parent' to silence this
      warning
  hwloc_obj_t group_obj, parent;
                               ^
                                = NULL
```

With a quick review of the code, I'm not sure what the Right answer is.  The caller of this function expects a valid parent to be returned -- it (currently) doesn't handle a NULL.

So I'm not sure if the caller needs to check for NULL, or whether some valid object needs to *always* be returned from hwloc_pci_find_hostbridge_parent().

**Comment by sthibaul** [comment]
Well, hwloc_alloc_setup_object, which creates group_obj, assumes that it always return non-NULL (it memsets it to 0), so the if is actually a non-op atm.
