### ISSUE TITLE
Missing object infos when running in a cgroup without CPU 0

### ISSUE THREAD

**Issue by TomTheBear** [open-mpi/hwloc#124]
Hello,

I use hwloc 1.8.1 in my tool to determine the CPU family and model. The CPU family and model numbers are stored in the info section of socket objects. While updating my tool to work with cgroups, I found the following bug:

```Shell
$ sudo /bin/echo 0 > cpuset.cpus
$ ~/hwloc-cgroup-test
CPU family 6 model 60
$ sudo /bin/echo 1 > cpuset.cpus
$ ~/hwloc-cgroup-test
CPU family 0 model 0
```

I got this result for hwloc 1.8.1 and 1.10.1.

Greetings,
Thomas

Code of hwloc-cgroup-test.c:
```C
#include <stdlib.h>
#include <stdio.h>
#include <hwloc.h>

int main(int argc, char* argv[])
{
    hwloc_topology_t hwloc_topology;
    hwloc_obj_t obj;
    hwloc_topology_init(&hwloc_topology);
    hwloc_topology_set_flags(hwloc_topology, HWLOC_TOPOLOGY_FLAG_WHOLE_SYSTEM);
    hwloc_topology_load(hwloc_topology);
    obj = hwloc_get_obj_by_type(hwloc_topology, HWLOC_OBJ_SOCKET, 0);
    if (!obj)
    {
        hwloc_topology_destroy (hwloc_topology);
        return 1;
    }
    printf("CPU family %s model %s\n",
            hwloc_obj_get_info_by_name(obj, "CPUFamilyNumber"),
            hwloc_obj_get_info_by_name(obj, "CPUModelNumber"));
    hwloc_topology_destroy (hwloc_topology);
    return 0;
}
```

**Comment by bgoglin** [comment]
The problem is that the x86-cpuid backend assumes we have a contigous range of CPUs starting at 0. It's on my TODO list, thanks.

**Comment by bgoglin** [comment]
What distribution and kernel are you using?
I am seeing a different behavior here (works fine with v1.9 and later, gives "null" and "null" for v1.8)
Can you send your /proc/cpuinfo from inside the cgroup in both cases if they are different?

**Comment by TomTheBear** [comment]
I'm using Ubuntu 12.04.5 LTS with the 3.11.0-18-generic kernel in default configuration. /proc/cpuinfo is equal for both cpusets. I will do some further investigation, maybe I can give you a hint.

**Comment by TomTheBear** [comment]
I found the problem and it was on my side. My LD_LIBRARY_PATH contained an 1.8.1 library that was taken instead of the 1.10.1 lib. With the 1.10.1 library it works fine. I will update the hwloc version used in my tool. This issue can be closed.

**Comment by bgoglin** [comment]
thanks !
