### ISSUE TITLE
Properly place GPUs when on the CPU die

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#125]
AMD and Intel both have GPUs sharing the die with the CPU, but configured through virtual PCI functions. So we display them as PCI devices while they may want to be directly inside the CPU instead. Find a way to detect and report that.

http://www.open-mpi.org/community/lists/hwloc-users/2015/03/1159.php

**Comment by jsquyres** [comment]
@rhc54 may well care about this issue.

**Comment by bgoglin** [comment]
As discussed in the above link, this old issue isn't very important because locality is correct. PCI objects may be ignored in hwloc if really needed.
