### ISSUE TITLE
Collapse "repeated" PCI VFs in hwloc output

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/hwloc#129]
As you know, with the Cisco usNIC device, we tend to instantiate oodles of VFs.  hwloc currently renders all the VFs in the console and GUI outputs fairly non-scalably -- it simply lists them all.

Would it be possible to add some kind of "collapsing" feature to lstopo output?

E.g., today's console output looks like this:

```
PCIBridge
  PCI 1137:0043
    Net L#9 "eth6"
    OpenFabrics L#10 "usnic_2"
  PCI 1137:00cf
  PCI 1137:00cf
  PCI 1137:00cf
...etc. (same PCI 1137:00cf listed 64 times)
```

Maybe lstopo could output something like this, instead:

```
PCIBridge
  PCI 1137:0043
    Net L#9 "eth6"
    OpenFabrics L#10 "usnic_2"
  64 x { PCI 1137:00cf }
```

Some more finesse may be required in the `lstopo -v` output, since P values and PCI bus IDs will be different.  Perhaps something like:

```
PCI 1137:0043 (P#561152 busid=0000:89:00.0 class=0200(Ether) PCIVendor="Cisco Systems Inc" PCIDevice="VIC Ethernet NIC") "Cisco Systems Inc VIC Ethernet NIC"
  Network L#11 (Address=74:26:ac:40:32:5e Port=1) "eth7"
  OpenFabrics L#12 (NodeGUID=0200:00ff:fe00:0000 SysImageGUID=7626:acff:fe40:325e Port1State=4 Port1LID=0x0 Port1LMC=1 Port1GID0=fe80:0000:0a08:0ab8:7626:acff:fe40:325e) "usnic_3"
64 x { PCI 1137:00cf (P#[collapsed] busid=[collapsed] class=0200(Ether) PCIVendor="Cisco Systems Inc" PCIDevice="VIC Userspace NIC") "Cisco Systems Inc VIC Userspace NIC"
```

To see the non-collapsed versions, pass `--no-collapse` (or something like this)?

I imagine something clever could be done in the GUI output, perhaps showing the same kind of "64 x { PCI 1137:0043 }" in the VF box, but display ~3 boxes overlaid, like they were stacked on each other -- just as a visual indication that there's more than 1.

CC'ing @goodell

**Comment by bgoglin** [comment]
Yeah we really need to do this. I think I'll do a pass of preprocessing to add "lstopoCollapse=5" attributes, and then we can talk about improving the display layout.
We're only talking about collapsing PCI boxes, right? Or will you want to collapse PCI boxes that all contain ethX+usnix_Y boxes next? (assuming many VFs are enabled simultaneously).

**Comment by jsquyres** [comment]
I'm only concerned with the VF PCI boxes -- I think the ethX + usnic_Y boxes (which is a similar pattern for IB / IPoIB boxes) are fine.

Here's XML output from the hwloc git HEAD of one of our lab machines showing oodles of VFs:

https://gist.github.com/jsquyres/45b9e5a0837cfe85cd0f
