### ISSUE TITLE
hwloc-1.11.1 breaks cygwin build

### ISSUE THREAD

**Issue by matzeri** [open-mpi/hwloc#138]
Latest changes break build on cygwin, that worked fine on hwloc-1.11.0

Following patches 
https://github.com/matzeri/cygwin-pkg/blob/master/hwloc/hwloc-1.11.1-1.src.patch

re-enabled the build. All tests fine as hwloc-1.11.0

**Comment by bgoglin** [comment]
Thanks, I am applying this.
Do you have a real name for thanks in the NEWS file?

I don't have access to a cygwin, I'll try to remember pinging you when we release a release candidate, so that such fixes can be applied before the final release. Are you subscribed to hwloc-announce?

**Comment by matzeri** [comment]
Now I am subscribed to hwloc-announce.
I saw the RC, but I was not able to test it in time as I was on road.
https://www.cygwin.com/ml/cygwin-announce/2015-10/msg00070.html
