### ISSUE TITLE
Potential Memory Leak on Topology

### ISSUE THREAD

**Issue by daschl** [open-mpi/hwloc#141]
Hi,

I'm using hwloc 1.11.1, working on my rust binding. I did a little but of valgrind work to see if I'm leaking memory (in pure rust this should not be possible, but since I'm interfering over FFI with hwloc...).

If you need more info on my machine: this is a 2 core ubuntu vm on os x (`Linux vagrant-ubuntu-trusty-64 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`)

```
Machine (490MB)
  Socket L#0 + L2d L#0 (6144KB)
    L1d L#0 (32KB) + Core L#0 + PU L#0 (P#0)
    L1d L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  HostBridge L#0
    PCI 80ee:beef
    PCI 8086:100e
      Net L#0 "eth0"
    PCI 8086:100e
      Net L#1 "eth1"
    PCI 8086:2829
      Block L#2 "sda"
```
So here is rust code (should not be too hard to digest):

```rust
extern crate libc;

pub enum HwlocTopology {}

fn main() {
    // Done in ::new()
    let mut topo: *mut HwlocTopology = std::ptr::null_mut();
    
    unsafe {
        hwloc_topology_init(&mut topo);
        hwloc_topology_load(topo);
        hwloc_topology_destroy(topo);
    }
}

#[link(name = "hwloc")]
extern "C" {
    pub fn hwloc_topology_init(topology: *mut *mut HwlocTopology) -> libc::c_int;
    pub fn hwloc_topology_load(topology: *mut HwlocTopology) -> libc::c_int;
    pub fn hwloc_topology_destroy(topology: *mut HwlocTopology);
}
```

All this code does is initializes the exported C methods from hwloc in the `extern` block and then creates a mutable pointer which is then used to init, load and finally destroy the topology. This is a simplified version of what the `hwloc-rs` module does under the covers. Running this code under valgrind shows a leak:

```
==13316== HEAP SUMMARY:
==13316==     in use at exit: 124 bytes in 3 blocks
==13316==   total heap usage: 622 allocs, 619 frees, 314,895 bytes allocated
==13316== 
==13316== 88 bytes in 1 blocks are definitely lost in loss record 3 of 3
==13316==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13316==    by 0x618FA18: lt__malloc (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.0)
==13316==    by 0x618FA4D: lt__zalloc (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.0)
==13316==    by 0x6191BB9: ??? (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.0)
==13316==    by 0x61925B1: lt_dlopenadvise (in /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.0)
==13316==    by 0x740E39A: ???
==13316==    by 0x740ED09: ???
==13316==    by 0x4E4AF99: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.4.0)
==13316==    by 0x4E4B3B6: ??? (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.4.0)
==13316==    by 0x4E43D3F: hwloc_topology_load (in /usr/lib/x86_64-linux-gnu/libhwloc.so.5.4.0)
==13316==    by 0x10C738: main::ha67dc92297b7efc9haa (simple.rs:11)
==13316==    by 0x1121E4: sys_common::unwind::try::try_fn::h5008875067004982501 (in /vagrant/hwloc-rs/target/debug/examples/simple)
==13316== 
==13316== LEAK SUMMARY:
==13316==    definitely lost: 88 bytes in 1 blocks
==13316==    indirectly lost: 0 bytes in 0 blocks
==13316==      possibly lost: 0 bytes in 0 blocks
==13316==    still reachable: 36 bytes in 2 blocks
==13316==         suppressed: 0 bytes in 0 blocks
```

Note that these 88 bytes do not show up when I just init and destroy it (commenting out the `hwloc_topology_load(topo);` from the above example):

```
==13358== 
==13358== HEAP SUMMARY:
==13358==     in use at exit: 36 bytes in 2 blocks
==13358==   total heap usage: 163 allocs, 161 frees, 124,135 bytes allocated
==13358== 
==13358== LEAK SUMMARY:
==13358==    definitely lost: 0 bytes in 0 blocks
==13358==    indirectly lost: 0 bytes in 0 blocks
==13358==      possibly lost: 0 bytes in 0 blocks
==13358==    still reachable: 36 bytes in 2 blocks
==13358==         suppressed: 0 bytes in 0 blocks
```

the dangling 88 bytes are gone - any idea why that could be? Is there anything going on in load which is not properly cleaned up in destroy? Btw, I know that the destroy call definitely works, because when I comment it out it leaks nearly 2k, so its definitely cleaning up (but not everything?).

**Comment by bgoglin** [comment]
Hello

This leak appears as soon as we load a single hwloc plugin. When plugins are enabled but nothing gets loaded, no leak. When multiple are loaded, still a single leak.

There is some global state that libtool/ltdl allocates once at startup and never frees. Maybe this one is an additional one. Hard to say. I verified that hwloc is closing all plugins properly and exiting ltdl, nothing to fix there, but still this leak.

Brice

**Comment by daschl** [comment]
Feel free to close it if you think the leak is not in hwloc, I just wanted to bring it up :)

**Comment by bgoglin** [comment]
Let's assume it's another ltdl global state and close this.
Thanks for the report anyway.
