### ISSUE TITLE
Error handling /proc/mounts with long lines

### ISSUE THREAD

**Issue by hjelmn** [open-mpi/hwloc#142]
I have a system with unusually long lines in /proc/mounts (larger than 512 characters). This is causing parsing errors in hwloc_find_linux_cpuset_mntpnt. Ideally this could be fixed by using setmntent/getmntent/etc. Is there a reason why (as the comment states) that hwloc needs a relative open here? From what I understand the behavior of open and openat is identical when given an absolute path (such as /proc/mounts).

**Comment by bgoglin** [comment]
Hello

I knew this code would break one day :/

We need the relative openat() so that we can load sys/proc filesystems gathered by hwloc-gather-topology for offline regression testing, instead of the local sys/proc files. openat() makes that code generic and simple everywhere in the Linux backend. That said, in yout case, we always open /proc/mounts, so the generic openat() code isn't that useful. I'll try to just setmnt(filesystemroot+"/proc/mounts") directly.

For the record, what makes your /proc/mounts line so long?

**Comment by hjelmn** [comment]
The lines are long because of the way Cray mounts their system images. Here is an example:

```
/var/opt/cray/imps /opt/intel dvs ro,relatime,blksize=32768,nodename=c0-0c1s9n3:c0-1c1s9n3:c0-2c1s9n3:c0-3c1s9n3:c0-4c1s9n3:c1-0c1s9n3:c1-1c1s9n3:c1-2c1s9n3:c1-3c1s9n3:c1-4c1s9n3:c2-0c1s9n3:c2-1c1s9n3:c2-2c1s9n3:c2-3c1s9n3:c2-4c1s9n3:c3-0c1s9n3:c3-1c1s9n3:c3-2c1s9n3:c3-3c1s9n3:c3-4c1s9n3:c4-0c1s9n3:c4-1c1s9n3:c4-2c1s9n3:c4-3c1s9n3:c4-4c1s9n3:c5-0c1s9n3:c5-1c1s9n3:c5-2c1s9n3:c5-3c1s9n3:c5-4c1s9n3:c6-0c1s9n3:c6-1c1s9n3:c6-2c1s9n3:c6-3c1s9n3:c7-0c1s9n3:c7-1c1s9n3:c7-2c1s9n3:c7-3c1s9n3:c8-0c1s9n3:c8-1c1s9n3:c8-2c1s9n3:c8-3c1s9n3:c9-0c1s9n3:c9-1c1s9n3:c9-2c1s9n3:c9-3c1s9n3:c10-0c1s9n3:c10-1c1s9n3:c10-2c1s9n3:c10-3c1s9n3:c11-0c1s9n3:c11-1c1s9n3:c11-2c1s9n3:c11-3c1s9n3,nodefile=/proc/fs/dvs/mounts/1/nodenames,attrcache_timeout=14400,nodwfs,nomultifsync,cache,nodatasync,noclosesync,retry,failover,userenv,clusterfs,killprocess,noatomic,nodeferopens,no_distribute_create_ops,no_ro_cache,loadbalance,maxnodes=1,nnodes=54,hash=fnv-1a 0 0
```

**Comment by bgoglin** [comment]
Ok. Which hwloc or OMPI are you using? (to make sure my upcoming patch will apply)

**Comment by hjelmn** [comment]
Both ompi master and v2.x will need to be patched.

**Comment by bgoglin** [comment]
Here's a patch against hwloc v1.11.2 (pretty close to what's in OMPI iirc)
https://github.com/bgoglin/hwloc/commit/d2d07b9a2268699e13e1644b4f2ef7a53ef7396c

**Comment by bgoglin** [comment]
This fix breaks thread-safety because of getmntent(). By the way getmntent() is actually internally limited to 4kB lines. getmntent_r() is thread-safe and supports larger buffers, but it cannot report truncation errors anyway. See #194 for more details.
