### ISSUE TITLE
hwloc-ls does not list all PCIe cards

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [open-mpi/hwloc#148]
You can see the Fibrechannel device with lspci, but not with hwloc-ls.
[root@nh]# lspci -nn | grep Fibre
14:00.0 Fibre Channel [0c04]: QLogic Corp. ISP8324-based 16Gb Fibre Channel to PCI Express Adapter [1077:2031] (rev 02)
14:00.1 Fibre Channel [0c04]: QLogic Corp. ISP8324-based 16Gb Fibre Channel to PCI Express Adapter [1077:2031] (rev 02)
34:00.0 Fibre Channel [0c04]: QLogic Corp. ISP8324-based 16Gb Fibre Channel to PCI Express Adapter [1077:2031] (rev 02)
34:00.1 Fibre Channel [0c04]: QLogic Corp. ISP8324-based 16Gb Fibre Channel to PCI Express Adapter [1077:2031] (rev 02)
[root@nh]# hwloc-ls | grep 1077
[root@nh netloc-0.5]#

FWIW, I get the same result if I use lstopo.

Thanks,
Matt.

**Comment by bgoglin** [comment]
Hello

hwloc-ls and lstopo are strictly identical. They filter PCI devices by default: they only keep the common kinds of device, and FibreChannel adapters are not considered "common". lstopo --whole-io should display them (as well as many other devices).

If these adapters are rare but important, we could consider them as "common". The idea of this filtering is basically yo avoid listing hundreds of PCI devices whose locality is useless anyway. The current list is: display devices (PCI class 0x03xx), network (02xx), storage (01xx), processor (0bxx), processing accelerator (12xx), and only Infiniband (0c06) within the serial class (0cxx). I wouldn't enable the entire serial class (that would enable USB, IPMI, CANBUS, ...) but FiberChannel (0c04) could be possible maybe?

By the way, note that starting with hwloc 2.0, lstopo won't display vendor:device ids by default. You would have to do "lstopo -v --whole-io | grep 1077".

Brice

**Comment by LiveFreeAndRoam** [comment]
Thanks Brice,

I agree, hiding the junk PCI devices makes sense.

Fibre Channel devices are important.  They provide access to the storage array and are very popular in large corporations.  It would be great to add them as the default.

# lspci -vvv -nn | grep Fibre
01:00.2 Fibre Channel [0c04]: Emulex Corporation OneConnect 10Gb FCoE Initiator (be3) [19a2:0714] (rev 01)
01:00.3 Fibre Channel [0c04]: Emulex Corporation OneConnect 10Gb FCoE Initiator (be3) [19a2:0714] (rev 01)
11:00.2 Fibre Channel [0c04]: Emulex Corporation OneConnect 10Gb FCoE Initiator (be3) [19a2:0714] (rev 01)
11:00.3 Fibre Channel [0c04]: Emulex Corporation OneConnect 10Gb FCoE Initiator (be3) [19a2:0714] (rev 01)
# lstopo -v --whole-io | grep 19a2
        2 x { PCI 19a2:0714 (P#[collapsed] busid=[collapsed] class=0c04(Fiber) link=4.00GB/s) }
        2 x { PCI 19a2:0714 (P#[collapsed] busid=[collapsed] class=0c04(Fiber) link=4.00GB/s) }
 
FWIW, there is a difference in the way Fibre vs Fiber is being spelt.  US Engrish vs Queen's Anglish. :) 

Cheers,
Matt.

**Comment by bgoglin** [comment]
So you want me to replace "Fiber" with "Fibre"? Or maybe even "FC" in case the short name "Fibre" is too vague in the lstopo output?

FWIW, 0c04 is called PCI_CLASS_SERIAL_FIBER in pci/header.h, that may be the reason why we currently have "Fiber".

BTW, if there are some kinds of disks attached behind those adapters, I wonder lstopo doesn't report any of them. I should find an access to a FC server to look deeper in /sys/class/block

**Comment by bgoglin** [comment]
By the way, please provide a full name if you want a proper "Thanks" in the v1.11.3 NEWS file :)

**Comment by LiveFreeAndRoam** [comment]
Matt Muggeridge. :)
