### ISSUE TITLE
Segfault when hwloc_alloc fails (maybe it is a wrong use by myself)

### ISSUE THREAD

**Issue by hbrunie** [open-mpi/hwloc#153]
Hi!
When I try this code it segfault with HWLOC and it aborts without.
gcc -Wall simpletest.c -DDOUBLE
hugo@hugo-X301A:~$ ./a.out 
a.out: simpletest.c:37: main: Assertion `buffer' failed.
Abandon (core dumped)
:~$ gcc -Wall simpletest.c
:~$ ./a.out 

:~$ gcc -Wall simpletest.c -lhwloc -DHWLOC
:~$ ./a.out 

:~$ gcc -Wall simpletest.c -lhwloc -DHWLOC -DDOUBLE
:~$ ./a.out 
Erreur de segmentation (core dumped)

Best regards,

Hugo BRUNIE
[test.zip](https://github.com/open-mpi/hwloc/files/182652/test.zip)

**Comment by bgoglin** [comment]
Thanks, the issue is that mmap fails inside hwloc_alloc() (because mmap doesn't like >2Go) and we don't convert MAP_FAILED (-1) into NULL. I'll fix that.
