### ISSUE TITLE
misc TODO

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#16]
Tools
===

  * bind process on 2 cores "near" physical proc id 3 ?
    * hwloc-calc: add an option to request a cpuset containing of n close entries among the generated cpuset

  * internationalize the output of lstopo? object types and memory size units

  * hwloc-top, like lstopo, but keeps printing every 3s or so, and show bound threads as well as the used CPU%

Doc
===

  * automatically generate the pngs?
    * see doc/images/HACKING

Support
===

  * add info about supported instructions (sse, avx, ...)
  * add info about available execution units (fpu)
    * and say if they are shared between threads/cores
      * this could help improving the current ambiguity between two real cores, one hyperthreaded core, and AMD dual-fake-core compute units

  * reduce distance matrices so that parent objects get distances between them as well (just like we do when computing group distances after inserting groups)

  * parallelize the discovery ? :)

I/O
===

  * CCI interoperability to get cci_device and/or cci_device->name locality
    * use cci_device->pci.{domain,bus,dev,func} to retrieve the PCI device
    * wait for the CCI API to be stable

  * Add a ofed plugin to gather ofed device info without relying on Linux sysfs
    * Not sure whether ofed works the same on other OS anyway

Backends and Ports
===

  * Try to make the distance grouping code a separate component ?

  * QNX
    * _syspage_ptr() SYSPAGE_ENTRY(entry)
    * ThreadCtl/Thread_ctl_r(_NTO_TCTL_RUNMASK)

  * BSD
    * sys/sched.h: sched_bind/sched_unbind, but that's in-kernel only for now.

  * AIX
    * area memory binding not working, see question and testcase asked on http://www.ibm.com/developerworks/forums/thread.jspa?threadID=366801&tstart=0

  * Cray Catamount?

**Comment by bgoglin** [comment]
Moved all slightly-relevant remaining items to their own ticket.
