### ISSUE TITLE
Pass "support" info in XML

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#166]
OpenMPI would like to know whether remote nodes support binding. The support information is not exported in XML. So they currently export/load the support info manually.

If we had that information in XML, how do we expose to the user? We don't want to allow binding when loading from XML by default, but we still want to return that binding is supported?

**Comment by bgoglin** [comment]
@rhc54 Do you still need this?
We'd need to clarify what to do when B imports XML from A. Usually, we report that binding is not supported, and we indeed fail to bind on B. Looks like we'd need a way to change the former without changing the former. Maybe only when we import XML with a specific flag saying "report remote support even if not locally supported".

**Comment by rhc54** [comment]
Our current workaround is functional. Frankly, though, I don't understand your distinction. If I provide an XML form of the current node's topology (e.g., because I already discovered it and stored it in a file, or the string is passed down to me from the local RM) - why would you deny me the ability to use it to bind? What makes importing XML "special"?

**Comment by bgoglin** [comment]
The default is "you import from XML, hwloc doesn't know if the XML matches the local machine, hence we don't bind". If the user knows the XML matches the local machine, he can set the THISSYSTEM flag to tell hwloc "don't worry, you can enable binding".

But we're not talking about the same case. I was talking about exchanging XML between processes on different nodes (e.g. the frontend node retrieving compute node topology). You seem to be talking about two processes on the same node. If only the latter matters, we're already good.

**Comment by rhc54** [comment]
OMPI used to compute the bindings on the head node and then send those to the backend for execution. Hence the problem. However, we now do it all on the backend, and so the problem no longer exists. I can't speak to others, of course, but you can close it so far as OMPI is concerned.
