### ISSUE TITLE
Error installing man pages when install dir contains "@"

### ISSUE THREAD

**Issue by ronawho** [open-mpi/hwloc#187]
This is a really minor issue, but having an "@" in the install path leads to an
error when installing the man pages because a sed command is using "@" as the
delimiter.

This wasn't an issue in 1.11.2, but I think it was introduced with [this commit] (https://github.com/open-mpi/hwloc/commit/329c1d2e),
specifically [this line] (https://github.com/open-mpi/hwloc/commit/329c1d2e#diff-6fcbb175ea79ad6fd46472db231fe263R129)

Should be pretty simple to repro with:
```sh
  ./configure --prefix=$PWD/../hwloc-install@/
  make
```

For context: we don't personally have paths with @'s in them, but Jenkins (a
continuous integration tool we use for testing) uses "@{num}" to give concurrent
builds unique build directories.

**Comment by sthibaul** [comment]
Indeed. And basically all characters (except NUL) are allowed in a path. I have changed the code to escape / instead of using @.

**Comment by ronawho** [comment]
Just to confirm, your patch worked for me. Thanks for such a fast fix!
