### ISSUE TITLE
buggy sysfs package information on Cray/KNL

### ISSUE THREAD

**Issue by jette** [open-mpi/hwloc#188]
Errors of the sort shown below are generated on Cray systems with the KNL processor when the KNL is configured in SNC2 NUMA mode and flat MCDRAM mode.

**Comment by bgoglin** [comment]
Hello,
I removed most of what was in your report because they are not public. Cray must update their kernel and/or BIOS. hwloc support for KNL in all modes was verified with Intel several month ago. Please discuss this issue in private email with me if needed.
Regards
