### ISSUE TITLE
getmntent() thread-unsafe in hwloc_topology_load() on Linux

### ISSUE THREAD

**Issue by corossig** [open-mpi/hwloc#194]
Hi,
Thread sanitizer report a data race in getmntent which is called at least by hwloc_topology_load.

## How to reproduce
Call the sequence "hwloc_topology_init, hwloc_topology_load and hwloc_get_cpubind" in two threads.

## Compile the example
with a recent gcc (> 4.8)
gcc -fsanitize=thread getmntent_tsan.c -lhwloc -lpthread

## Possible solutions
Use re-entrant version getmntent_r 
OR
Put a static mutex around call of hwloc_find_linux_cpuset_mntpnt.

## System informations
Linux 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: CentOS
Description:    CentOS release 6.6 (Final)
Release:        6.6
Codename:       Final
Hwloc 1.11.3
gcc 5.3

[tsan.txt](https://github.com/open-mpi/hwloc/files/350290/tsan.txt)
[getmntent_tsan.c.txt](https://github.com/open-mpi/hwloc/files/350311/getmntent_tsan.c.txt)

**Comment by bgoglin** [comment]
I look at using getmntent_r(), thanks.

**Comment by bgoglin** [comment]
By the way, you should use a single topology for both threads whenever possible.
