### ISSUE TITLE
hwloc-ps --cpuset not showing the correct CPU mask for some process

### ISSUE THREAD

**Issue by elvinio** [open-mpi/hwloc#201]
There is a bug in version 1.5 of hwloc-ps.

Pid 29149 is taskset to 0x3fc. However hwloc-ps shows it as 0x9e3ff.
```
$ hwloc-ps -c | grep Low
20563   0x000ff000              Low
21949   0x0009e3ff              Low

$hwloc-ps | grep Low
20563   L2Cache:12 L2Cache:13 L2Cache:14 L2Cache:15 L2Cache:16 L2Cache:17 L2Cache:18 L2Cache:19         Low
21949   NUMANode:0 L2Cache:13 L2Cache:14 L2Cache:15 L2Cache:16 L2Cache:19               Low
```

Querying the process directly with taskset shows the correct value:
```
$ taskset -p 21949
pid 21949's current affinity mask: 3fc
```

The CPU mask of pid 20563 is reported correctly.

CPU Architecture
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Stepping:              4
CPU MHz:               2799.776
BogoMIPS:              5599.20
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
NUMA node1 CPU(s):     10-19

**Comment by bgoglin** [comment]
Hello
Can you try with a more recent version of hwloc ? 1.5 is 4 years old, I can't remember if we fixed anything related in the meantime.
You say "for some process". Does it mean it works in most other cases? How did you bind this process to 3fc? What does "hwloc-bind 0x3fc -- hwloc-bind --get" report?
Can you post the textual output of "lstopo -" too?
Random question, is this process and/or your shell running in a cgroup that restricts the available CPUs?
Thanks
Brice

**Comment by elvinio** [comment]
Hi Brice

I will see if I can get a newer version compiled and check the output.

I mentioned for some processes because I ran the same process twice taskset to different cores.
Process 1: chrt --fifo 50 taskset -p 0x3fc ./Low
Process 2: chrt --fifo 50 taskset -p 0xff00 ./Low

While it displayed correctly for one process, it was wrong for the other.
This is a 20 cores machine on 2 sockets.
I have isolated 8 cores (core 2 - 9, 0x3fc) in the kernel boot.
I don't believe it is due to isolcpus. If I run the processes again, I can get the output for 0xff00 wrong too.

For example, this is what I get now:
```
> hwloc-ps -c | grep Low
28014   0x000003fc              Low
28280   0x000ffa7f              Low

> taskset -p 28014
pid 28014's current affinity mask: 3fc

> taskset -p 28280
pid 28280's current affinity mask: ff000

```

The process is a c-compiled binary. There is no cgroup, only isolcpu as mentioned earlier.

Other info that you requested for:
```
> hwloc-bind 0x3fc -- hwloc-bind --get
0x000003fc

lstopo -
Machine (128GB)
  NUMANode L#0 (P#0 64GB)
    Socket L#0 + L3 L#0 (25MB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
      L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
      L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
      L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
      L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
      L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
      L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#7)
      L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8 + PU L#8 (P#8)
      L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9 + PU L#9 (P#9)
    HostBridge L#0
      PCIBridge
        PCI 14e4:168e
          Net L#0 "eth0"
        PCI 14e4:168e
          Net L#1 "eth1"
        PCI 14e4:168e
          Net L#2 "eth2"
        PCI 14e4:168e
          Net L#3 "eth3"
      PCIBridge
        PCI 103c:323b
          Block L#4 "sda"
      PCIBridge
        PCI 102b:0533
  NUMANode L#1 (P#1 64GB) + Socket L#1 + L3 L#1 (25MB)
    L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10 + PU L#10 (P#10)
    L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11 + PU L#11 (P#11)
    L2 L#12 (256KB) + L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12 + PU L#12 (P#12)
    L2 L#13 (256KB) + L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13 + PU L#13 (P#13)
    L2 L#14 (256KB) + L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14 + PU L#14 (P#14)
    L2 L#15 (256KB) + L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15 + PU L#15 (P#15)
    L2 L#16 (256KB) + L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16 + PU L#16 (P#16)
    L2 L#17 (256KB) + L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17 + PU L#17 (P#17)
    L2 L#18 (256KB) + L1d L#18 (32KB) + L1i L#18 (32KB) + Core L#18 + PU L#18 (P#18)
    L2 L#19 (256KB) + L1d L#19 (32KB) + L1i L#19 (32KB) + Core L#19 + PU L#19 (P#19)
```

Regards
Elvin

**Comment by elvinio** [comment]
I have version 1.11.3 compiled and ran it. The output is the same:

```
> ./hwloc-ps -c | grep Low
28014   0x000003fc              Low
28280   0x000ffa7f              Low
```

**Comment by bgoglin** [comment]
Do you know if there are threads in your process? taskset only returns the binding of the main thread, while hwloc returns the entire process by default? What does "hwloc-bind --tid 28280 --get" return? Is it different from "hwloc --pid 28280 --get"?

With hwloc-ps, you may add -t to see individual threads (but "grep Low" won't work anymore).

I looked at the taskset source code, it doesn't do anything complicated. I was wondering if isolcpus could cause some cpumask bits to remain uninitialized, but the code doesn't show any problem like that.

**Comment by elvinio** [comment]
I see my folly now. Hwloc-ps is returning an aggregation of cores that are used.
There are indeed threads in my process that were manually bound to cores outside of the process mask.

When I ran hwloc-bind --tid and --pid commands, it was returning different values.
If I recompile the program without the manual cpu affinity, the cpumask returned by hwloc-ps is the same the main thread.

Thanks for you patience and help in troubleshooting this.
