### ISSUE TITLE
Properly handle cppcheck errors

### ISSUE THREAD

**Issue by bryongloden** [open-mpi/hwloc#207]
- [ ] [netloc/map.c:1201]: (error) Common realloc mistake: 'edges' nulled but not freed upon failure
- [ ] [netloc/map.c:1306]: (error) Common realloc mistake: 'edges' nulled but not freed upon failure
- [ ] [netloc/map.c:1618]: (error) Common realloc mistake: 'next_ids' nulled but not freed upon failure
- [ ] [netloc/map.c:1634]: (error) Common realloc mistake: 'done_ids' nulled but not freed upon failure
- [ ] [netloc/map.c:1647]: (error) Common realloc mistake: 'prev_ids' nulled but not freed upon failure
- [ ] [netloc/metadata.c:280]: (error) Common realloc mistake: 'all_networks' nulled but not freed upon failure
- [ ] [netloc/pathfinder.c:278]: (error) Common realloc mistake: 'rev_edges' nulled but not freed upon failure
- [ ] [netloc/pathfinder.c:312]: (error) Common realloc mistake: 'rev_edges' nulled but not freed upon failure
- [ ] [tests/netloc/embedded/do_test.c:55]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_hello.c:36]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_hello.c:47]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_hello.c:57]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_hello.c:70]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_hello.c:78]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_nodes.c:43]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_nodes.c:52]: (error) Memory leak: search_uris
- [ ] [tests/netloc/netloc_nodes.c:61]: (error) Memory leak: search_uris
- [ ] [utils/hwloc/hwloc-distrib.c:204]: (error) Memory leak: cpuset
- [ ] [utils/hwloc/hwloc-ps.c:317]: (error) Null pointer dereference: tidcpusets
- [ ] [utils/hwloc/hwloc-ps.c:318]: (error) Null pointer dereference: tidcpusets
- [ ] [utils/hwloc/hwloc-ps.c:319]: (error) Null pointer dereference: tidcpusets
- [ ] [utils/hwloc/hwloc-ps.c:277]: (error) Memory leak: path
- [ ] [utils/lsnettopo/lsnettopo.c:239]: (error) Common realloc mistake: 'indir' nulled but not freed upon failure
- [ ] [utils/lsnettopo/lsnettopo.c:121]: (error) Memory leak: search_uris
- [ ] [utils/netloc_reader_ib/netloc_reader_ib.c:313]: (error) Common realloc mistake: 'outdir' nulled but not freed upon failure
- [ ] [utils/netloc_reader_of/netloc_reader_of.c:323]: (error) Common realloc mistake: 'outdir' nulled but not freed upon failure
- [ ] [utils/netloc_reader_static/netloc_reader_static.c:326]: (error) Common realloc mistake: 'outdir' nulled but not freed upon failure

Bonjour @bgoglin. This is it for the rest of the cppcheck errors at this point. As you've already said in https://github.com/open-mpi/hwloc/pull/202, the netloc lib and utils is going to be deeply revamped. You'll notice that some of these aren't realloc errors, but if you're going to revamp netloc (including /test/netloc) and utils, then you might as well wait on fixing the rest.

If you want my help patching any of this, I'm happy to cherry pick any of the errors you deem critical. Just ping me here so I can receive a GitHub notification. Best of luck mate.

-bg

**Comment by bgoglin** [comment]
Thanks.
I fixed hwloc-ps.c:277. Others in that file cannot actually leak.
hwloc-distrib.c has many other leaks in case of error in main, OK to ignore.
All netloc stuff will be heavily changed or removed in the future.
