### ISSUE TITLE
No hwloc-distances output on KNL

### ISSUE THREAD

**Issue by loveshack** [open-mpi/hwloc#209]
I'm looking at a 7210 Knights Landing box under latest CentOS 7 with hwloc 1.11.4; it's set up as SNC-4/cache.

I find that hwloc-distances produces no output, whereas numactl -H does show distances.  (I _think_ the lstopo output is right.)

Tracing open calls, to see what it reads, I see this at the end (with a substantial pause after opening mounts).  I can get gdb on it if necessary, but could use hints as I haven't looked at the code for ages.

```
open("/etc/udev/udev.conf", O_RDONLY|O_CLOEXEC) = 4
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 4
open("/proc/mounts", O_RDONLY|O_CLOEXEC) = 4
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 4
open("/sys/devices/system/cpu/possible", O_RDONLY) = 4
```

**Comment by bgoglin** [comment]
Hello,
It's not a bug, it's a feature. The NUMA distance on KNL is totally upside down (MCDRAM nodes appear far away while they are not). hwloc uses it to find out which nodes are MCDRAM, and then it drops it. Do you actually need it for something other than curiosity?
Brice

**Comment by loveshack** [comment]
On 2 September 2016 18:53:04 BST, Brice Goglin <notifications@github.com> wrote:
>Hello,
>It's not a bug, it's a feature. The NUMA distance on KNL is totally
>upside down (MCDRAM nodes appear far away while they are not). hwloc
>uses it to find out which nodes are MCDRAM, and then it drops it. Do
>you actually need it for something other than curiosity?
>Brice

Thanks. No, it was basically a sanity check, though of some basic interest.
It might be worth a message, if that's easy.
-- 
Sent from a mobile thing; excuse the result.

**Comment by bgoglin** [comment]
Not sure where to put that message, I'll think about it, thanks.
