### ISSUE TITLE
get_obj_inside_cpuset() vs empty cpuset being included in all cpusets

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#215]
get_nbobjs_inside_cpuset(NUMANODE) gives unexpected results on KNL since the MCDRAM NUMA nodes have an empty cpuset. Those nodes always match because get_*obj*_inside_cpuset() just uses bitmap_isincluded() which considers that 0x0 is included in all possible cpusets.

In SNC4 Flat (4 normal NUMA nodes and 4 CPU-less MCDRAM nodes), you get 5 NUMA nodes included a NUMA node (itself + 4 MCDRAM).

We may want to ignore objects with empty sets in get_*obj*_inside_cpuset() functions.

Or maybe even modify bitmap_isincluded(0, x) to return FALSE? Would require to carefully review the core, and maybe update bitmap_compare_inclusion(0,x) not to return INCLUDED?

**Comment by sthibaul** [comment]
Making compare_inclusion(0,x) not to return INCLUDED looks very odd to me. That strikes logic, and will possibly break existing algorithms.

**Comment by sthibaul** [comment]
Fixing get_/obj/_insert_cpuset() to ignore empty sets however makes sense to me
