### ISSUE TITLE
Offline PUs are not added to the topology on Android device

### ISSUE THREAD

**Issue by sbufalov** [open-mpi/hwloc#226]
I cross-compiled hwloc for android. Backend type is Linux. Offline PUs can be seen in complete_cpuset but are not available in the topology even with whole system discovery enabled.

**Comment by sthibaul** [comment]
Hello,
Would you be able to run the hwloc-gather-topology script, so we can see what the OS is reporting?

**Comment by sbufalov** [comment]
machine -> package -> core -> single pu.
However, there are 3 offline PUs. They are reported by the utility in verbose mode.
Sorry, that I can't provide more details. The device is in the office and I'm not until Monday

**Comment by sbufalov** [comment]
note, Numa node is also missing. It is not a uniform behavior what complicates my design

**Comment by bgoglin** [comment]
That's expected.

Linux doesn't report any topology anymore for offline CPUs (I don't remember which kernel version started doing this, but it's been a while). That's why we won't report offline CPUs at all anymore in hwloc 2.0.

For NUMA nodes, that's a historical decision that indeeds causes confusion. In hwloc 2.0, there will always be a NUMA node, even on UMA machine like yours and on machine with non-NUMA kernels.

**Comment by sbufalov** [comment]
on Android devices the system moves PUs online and offline dynamically depending on the load. So the topology is not static. How to handle this use case correctly with hwloc?

**Comment by bgoglin** [comment]
That's something we don't know how to handle yet, we're open to suggestion. Ideally, the kernel would give information about these changes but it doesn't (last time I checked). We have some collaboration with ARM but their software stack isn't really ready for topology-related development yet :/

**Comment by sbufalov** [comment]
I'm new in hwloc but will try to provide any valuable input. By the way, the documentation is not up-to-date. It says that the topology will include ALL objects discarding any restrictions in policy and offline settings if you enable WHOLE system discovery (HWLOC_TOPOLOGY_FLAG_WHOLE_SYSTEM). That confused me a lot. And contradicts with what you say.

**Comment by bgoglin** [comment]
I'll fix that, thanks.
