### ISSUE TITLE
KNL: cannot bind to MCDRAM

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/hwloc#233]
in ```SNC-4``` cluster mode and ```flat``` memory mode

```
$ hwloc-info 
depth 0:	1 Machine (type #1)
 depth 1:	1 Package (type #3)
  depth 2:	4 Group0 (type #7)
   depth 3:	8 NUMANode (type #2)
    depth 4:	34 L2Cache (type #4)
     depth 5:	68 L1dCache (type #4)
      depth 6:	68 L1iCache (type #4)
       depth 7:	68 Core (type #5)
        depth 8:	272 PU (type #6)
```

NUMA node ```4``` is the MCDRAM of node ```0``` and it has no cpu attached to it
```
$ hwloc-bind --membind numa:4 true
object #4 depth 3 below cpuset 0x0000ffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff does not exist
cannot membind to empty set
```

if there a way to bind to MCDRAM with ```hwloc``` ?
fwiw ```numactl -m 4 true``` does the trick.

i digged a bit and found that ```--membind numa:4``` is converted into an empty _cpuset_
and then things goes wrong. should ```--membind numa:4``` be converted and then handled as a  (non empty) _nodeset_ instead ?

fwiw, i want to write a program that binds to the closest MCDRAM
```numactl -l ...``` binds to the local memory only, and i hope a ```numactl --mcdram ...``` feature so
i can easily uses that with mpi (e.g. ```mpirun numactl --mcdram ...```)
that can be achieved with a bit of scripting, but i think a ```hwloc``` based version would be more generic.

**Comment by bgoglin** [comment]
"should --membind numa:4 be converted and then handled as a (non empty) nodeset instead ?"

This should be case since hwloc 1.11.3. Which version are you using?

**Comment by ggouaillardet** [comment]
```1.11.5``` ```v1.11``` and ```master```

**Comment by bgoglin** [comment]
We broke it again in 1.11.5 when fixing #215 (3df864a1c5519719c5efa47d528464359e7213a7).

People wanted CPU-less NUMA nodes to be ignored when looking for objects inside a cpuset, which makes sense. But hwloc-bind (and friends) only look at cpusets when searching for objects, so they cannot find the MCDRAM anymore.

All these issues will go away with the upcoming memory model in git master. In the meantime and in 1.x, the proper fix is look for both cpuset and nodeset when searching objects. I'll see what I can do.

**Comment by ggouaillardet** [comment]
ok, thanks !

**Comment by bgoglin** [comment]
This seems to fix the issue.
https://github.com/bgoglin/hwloc/commit/380000c67f49da92fdf856aac3c2f59c83db64b9
It was much easier than I expected so I'd like a double-check :)

**Comment by ggouaillardet** [comment]
I will give it a try tomorrow, thanks !

**Comment by ggouaillardet** [comment]
it works for me, thanks !
