### ISSUE TITLE
hwloc_nvml_get_device_osdev() rarely returns the GPU hwloc_obj_t handle

### ISSUE THREAD

**Issue by dbeer** [open-mpi/hwloc#240]
Additionally, I have noticed that the function hwloc_nvml_get_device_osdev() very seldomly actually finds a GPU. Instead, we have added a workaround to the Torque code to find GPUs' localities using hwloc: it is the function get_non_nvml_device() which starts on line 44 here: https://github.com/adaptivecomputing/torque/blob/develop/src/resmom/accelerators_numa.cpp.

**Comment by dbeer** [comment]
For clarification, this workaround works for GPUs that do show up in the output of lstopo.

**Comment by bgoglin** [comment]
How do they show up in lstopo? As "nvml%d" or as "cuda%d"? Your workaround does not check whether the osdev name starts with "nvml", do you know if that was the important reason it works better?

**Comment by dbeer** [comment]
It was important that the device name need not start with nvml; when checking for that, we don't see any GPUs. Here is how the GPUs are displayed in lstopo:

[root@host ~]# lstopo | grep GPU
          GPU L#0 "card1"
          GPU L#1 "renderD128"
              GPU L#2 "card2"
              GPU L#3 "renderD129"
              GPU L#4 "card3"
              GPU L#5 "renderD130"
          GPU L#6 "card0"
          GPU L#7 "controlD64"
              GPU L#12 "card4"
              GPU L#13 "renderD131"
              GPU L#14 "card5"
              GPU L#15 "renderD132"

**Comment by bgoglin** [comment]
OK so that's expected. NVML are only for NVIDIA GPU as reported by their NVML library, which requires the nvml lib/headers to be available. That's why the documentation talks about "NVML devices" instead of "GPUs".

If you want all GPUs, either reported by the Linux DRM driver (open-source drivers), or by CUDA, or by NVML, or by OpenCL, iterating with hwloc_get_next_osdev() and checking whether obj->attr->osdev.type == GPU is the way to go.

If you see how to better document this, please let me know.

**Comment by bgoglin** [comment]
Oh and CUDA devices are reported as COPROCESSORs instead of GPUs.

**Comment by dbeer** [comment]
If that's how it is intended to work, then that makes sense and you can close this issue. I guess my confusion started from the fact that all of these are reported by nvml, and I thought since the function would return the same.

**Comment by bgoglin** [comment]
There's still something strange going on.

1) hwloc uses nvmlDeviceGetHandleByIndex() for getting nvmlDevice_t and building their osdev (with name nvml%d). I don't see why hwloc_nvml_get_device_osdev() would fail to find them back if you use nvmlDeviceGetHandleByIndex() in the same way.

2) Your code explicitly ignores all osdevs but card* and controlD*:
```
if ((strncmp(osdev->name, "card", 4)) &&
        (strncmp(osdev->name, "controlD", 8)))
  continue;
```
These osdevs come from open-source GPU drivers, they cannot match the PCI id of a nvmlDevice_t (NVIDIA proprietary driver only). So I wonder if your first while loop in get_non_nvml_device() can ever match something.
