### ISSUE TITLE
Hwloc fails to report GPUs installed on machine

### ISSUE THREAD

**Issue by dbeer** [open-mpi/hwloc#241]
In debugging issues for Torque, we have found that hwloc sometimes fails to detect GPUs that are visible in nvidia-smi and lspci outputs. When I say fails to detect, I mean that there are no GPUs in lstopo outputs and that if I traverse the topology of the machine using hwloc_get_next_osdev() there are no GPU handles returned.

I'm not sure what the cause is, and unfortunately none of the machines I have locally reproduce this issue. I understand that you will probably need more information, I should be able to get it for you but I'll have to request it from others.

**Comment by bgoglin** [comment]
When you say "sometimes fails to detect", do you mean "it doesn't always work on the very same machine", or "it works on some machines, not on others" ?
It would be good to see what kind of osdev they get on these machines. Do they get cuda%d, nvml%d and/or ":x.y". These come from 3 different GPU-related backends (nvml, cuda and gl) that have different requirements.

**Comment by dbeer** [comment]
I mean that it works on some machines and not others. I'm not sure exactly what you mean by what kind of osdev. Do you want me to paste the contents of that struct after printing in gdb? Or is there some command I can run to show you what you need?

**Comment by dbeer** [comment]
Sorry, I was mixing up my issues. For this one, I was on the machine and I didn't see any osdev related to a GPU. They were all network devices.

**Comment by dbeer** [comment]
[lstopo_lspci.txt](https://github.com/open-mpi/hwloc/files/1019408/lstopo_lspci.txt)

This contains the lstopo output and the lspci output for a machine with this issue.

**Comment by bgoglin** [comment]
First, check whether GPU-related backends are detected by configure. You need to see CUDA and/or NVML on the "Probe..." line at the end of configure. Something like this:
```
Probe / display I/O devices: PCI(pciaccess+linux) LinuxIO OpenCL CUDA GL
```
In this case, I am getting:
```
$ utils/lstopo/lstopo --only osdev
CoProc(CUDA) "cuda0"
Block(Disk) "sda"
Net "eth0"
Net "eth1"
CoProc(CUDA) "cuda1"
CoProc(CUDA) "cuda2"
```

**Comment by bgoglin** [comment]
With NVML detected by configure:
```
$ utils/lstopo/lstopo --only osdev                                     
CoProc(CUDA) "cuda0"
GPU "nvml0"
Block(Disk) "sda"
Net "eth0"
Net "eth1"
CoProc(CUDA) "cuda1"
GPU "nvml1"
CoProc(CUDA) "cuda2"
GPU "nvml2"
```

Each "GPU" device is reported as a CUDA coprocessor osdev and a NVML GPU.

**Comment by acvizi** [comment]
I'm confused by what you are saying. On a system with NVIDIA hardware that *does* show up in lstopo like this:

```
$ lstopo --only osdev
GPU L#0 "card1"
GPU L#1 "renderD128"
GPU L#2 "card2"
GPU L#3 "renderD129"
GPU L#4 "card3"
GPU L#5 "renderD130"
GPU L#6 "card0"
GPU L#7 "controlD64"
Block(Disk) L#8 "sda"
Block(Disk) L#9 "sdb"
Net L#10 "eth0"
Net L#11 "eno1"
GPU L#12 "card4"
GPU L#13 "renderD131"
GPU L#14 "card5"
GPU L#15 "renderD132"
```

The configure during the build of hwloc shows this (note no CUDA or NVML tags on the Probe line):

```
hwloc-1.11.7$ ./configure 2>&1 | egrep -i cuda\|nvml\|probe
checking cuda.h usability... no
checking cuda.h presence... no
checking for cuda.h... no
checking cuda_runtime_api.h usability... no
checking cuda_runtime_api.h presence... no
checking for cuda_runtime_api.h... no
checking nvml.h usability... no
checking nvml.h presence... no
checking for nvml.h... no
config.status: linking src/topology-cuda.c to tests/ports/topology-cuda.c
config.status: linking src/topology-nvml.c to tests/ports/topology-nvml.c
Probe / display I/O devices: PCI(pciaccess+linux)
```

**Comment by bgoglin** [comment]
Indeed, I found out today that NVIDIA devices appear as cardX and renderDY as well today. I guess something changed in the kernel and/or the NVIDIA driver. That explains things. So no nvml GPU can be reported, and nvml functions cannot work, but there are still some GPU osdevs.

Maybe it's time to revisit how to expose all this mess in hwloc 2.0 (do something better than report cardX GPU osdev + renderDY GPU osdev + (optionally) cudaZ CoProc osdev + (optionally)nvmlX GPU osdev for each GPU).

**Comment by acvizi** [comment]
So based on what you said, for systems where lstopo does not report any GPU device info, there is no way (ex. run configure with different switches, etc.) to build the latest stable version of hwloc to have it discover GPU devices?

**Comment by bgoglin** [comment]
If all your GPU drivers create DRM devices (/dev/dri/*), yes.

**Comment by bgoglin** [comment]
In theory, you could look at the PCI device class to find out GPUs. Or we could d random quirks to show GPUs. But in the end, it's useless to applications: They use DRI, CUDA, NVML, OpenCL, ... to use these GPUs, so what they need is the way to convert those API handles into hwloc objects so as to find the locality of the exact GPU they use.

**Comment by bgoglin** [comment]
If SLURM has another use case, let me know.

**Comment by FrankYu** [comment]
same question from here. 
env:
centos 7.3 with kernel version "3.10.0-514.6.1.el7.x86_64", four titan xp, and install NVIDIA driver with "NVIDIA-Linux-x86_64-384.59.run" 
I can see the four cards with cmd "nvidia-smi" and "lspci", but only got one with cmd "lstopo-no-graphics". And I also got some error logs about pbs_mom like "pbs_mom: LOG_ERROR::initializeNVIDIADevices, NVML reports 4 devices, but we only found 2" 
also, I can get lstopo-no-graphics work fine(report fours cards) after I do reboot to the hosts. 
Any idea about what cause this? mismatch version of some software?

Thanks

**Comment by bgoglin** [comment]
@FrankYu How about you post your lstopo output for debugging ? I guess your hwloc build didn't find some CUDA/NVML headers and couldn't report any GPU (check at the end of configure). It's likely only reporting the basic GPU embedded on the motherboard.

**Comment by acvizi** [comment]
@FrankYu The error log messages in TORQUE from pbs_mom are fixed in 6.1.2. They were due to hwloc not properly detecting NVIDIA devices on some systems (the substance of this hwloc bug discussion).

The workaround in Torque was to not use hwloc to report NVIDIA device info but instead used the NVML library.

**Comment by bgoglin** [comment]
Hello @acvizi or @dbeer 
Is there still anything to fix and/or clarify here?

**Comment by bgoglin** [comment]
I am closing this issue since nobody replied to the above question one year ago. Feel free to reopen if needed, or better open a new one with recent info.
