### ISSUE TITLE
Regression-test failure with CUDA 9.0

### ISSUE THREAD

**Issue by cponder** [open-mpi/hwloc#250]
I built HWLoc 1.11.7 with the PG! 17.7 compiler and the CUDA 9.0 release-candidate.
Running the `make check` gave me this failure-message
```
FAIL: cuda
PASS: nvml
============================================================================
Testsuite summary for hwloc 1.11.7
============================================================================
# TOTAL: 41
# PASS:  40
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to http://www.open-mpi.org/projects/hwloc/
============================================================================
```
The` tests/test-suite.log` shows this message
```
FAIL: cuda
==========

lt-cuda: cuda.c:52: main: Assertion `osdev' failed.
cuDeviceGetCount found 6 devices
./wrapper.sh: line 14: 26250 Aborted                 "$@"
FAIL cuda (exit status: 134)
```
The node has P100 GPU's. I can provide other info if you need.
I use this HWLoc with OpenMPI, and with MVAPICH2 in conjunction with Hydra.
Will this particular failure affect the ability to RDMA between GPU's for example?

**Comment by bgoglin** [comment]
Does lstopo show some cuda devices? The failure is occuring in hwloc/cuda.h which fails to find a hwloc object matching the given cuda device. First thing you should do is adding printf there to see whether hwloc_cuda_get_device_pci_ids() found PCI domain/bus/dev as expected.

**Comment by bgoglin** [comment]
Ping @cponder

**Comment by cponder** [comment]
I'd been ignoring this bug because I was waiting to see what happened when I used newer components.
Moving up to HWloc 1.11.8 and CUDA 9.0/GA and PGI 17.9, all the regression-tests are passing.
I'm going to close this one, if I have problems in the future I'll file new bugs.

**Comment by cponder** [comment]
I'd been ignoring this bug because I was waiting to see what happened when I used newer components.
Moving up to HWloc 1.11.8 and CUDA 9.0/GA and PGI 17.9, all the regression-tests are passing.
I'm going to close this one, if I have problems in the future I'll file new bugs.
