### ISSUE TITLE
blacklist/whitelist some components from the C interface

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#252]
Some people want to blacklist the OpenCL component for some reason. We can do it by setting HWLOC_COMPONENTS=-foo in the environment, but they would rather use a C function between init() and load().

Need to check whether blacklisting after init() is enough because init() calls components' init() callback. This callback usually does pretty-much nothing (check that plugin found core symbols, init basic stuff, but nothing discovery-related) but we should clarify that.

That API could also be used for whitelisting components that disabled by default in 2.x.

It could also accept wildcard for enabling/disabling based on the name and/or kind of backends.

**Comment by bgoglin** [comment]
@sthibaul Branch 'components' in my github fork lets you blacklist a component using
```
err = hwloc_topology_set_components(topology, HWLOC_TOPOLOGY_COMPONENTS_FLAG_BLACKLIST, "cuda");
```
(example at https://github.com/bgoglin/hwloc/blob/components/tests/hwloc/hwloc_backends.c#L202)

There's a tarball at https://ci.inria.fr/hwloc/job/zbgoglin-basic/lastSuccessfulBuild/artifact/hwloc-components-20180923.1202.gitc35f96a.tar.bz2

It seems to work but I didn't verify that CUDA-related init overheads are totally gone. Some people say that poking the PCI config space in the PCI backend may wakeup some devices, causing overheads too, don't know if it applies to NVIDIA GPUs.

**Comment by sthibaul** [comment]
Using it did work to remove the nvidia overhead without having to remove complete PCI support.
