### ISSUE TITLE
hwloc-dump-hwdata finds wrong size of MCDRAM (buggy BIOS) but lstopo finds correct size

### ISSUE THREAD

**Issue by johnnysmc** [open-mpi/hwloc#264]
I have a system with Intel Knights Landing platform, model 7250 processor.
While using hwloc to dump MCDRAM size, it's only shown 8192MB available. The spec says to support with 16384 MB with flat mode. Is there anything I done in wrong? Or, how can I get fully MCDRAM size from using hwloc?

Note: I try numactl --hardware and I can see 16384 MB shown in node 1 size field. I suspect the problem from hwloc detection issue.

----------------
Dumping KNL SMBIOS Memory-Side Cache information:
  File = ///sys/firmware/dmi/entries/14-0/raw, size = 4096
  Found KNL type = 160
  Found KNL type = 161
  Seeking dir Ì€`160-' 4
  File = ///sys/firmware/dmi/entries/160-0/raw, size = 4096
  Getting general KNL info
  Seeking dir Ì€`161-' 4
  File = ///sys/firmware/dmi/entries/161-0/raw, size = 4096
  Getting MCDRAM KNL info. Count=8 struct size=12
  MCDRAM controller 0
  Size = 2048 MB
  MCDRAM controller 1
  Size = 2048 MB
  MCDRAM controller 2
  Size = 2048 MB
  MCDRAM controller 3
  Size = 2048 MB
  MCDRAM controller 4
  Controller fused
  MCDRAM controller 5
  Controller fused
  MCDRAM controller 6
  Controller fused
  MCDRAM controller 7
  Controller fused
  Total MCDRAM 8192 MB
  Cluster mode: All2All
  Memory Mode: Flat
  Flat Mode: No MCDRAM cache available, nothing to dump.

**Comment by bgoglin** [comment]
Hello. Does lstopo report 8GB as well? hwloc-dump-hwdata is used for finding some information about the clustering/mcdram modes, and the mcdram cache size. But we still use sysfs for finding the MCDRAM NUMA node size, so lstopo should report 16GB just like numactl.

@grzegorz-andrejczuk Is it expected that hwloc-dump-hwdata reports 4 controllers with 2GB MCDRAM each, and 4 fused controllers even if there are actually 16GB total? Do we care?

**Comment by grzegorz-andrejczuk** [comment]
Hi,
I assume that BIOS provides incorrect DMI entries.
hwloc-dump-hwdata translates binary BIOS DMI entries to some human (or hwloc) readable text.

When **flat** mode is used this information is redundant and can be omitted.
This can be more complicated in **cache** mode and user wants to do some assumptions based on detected MCDRAM cache size.

We can workaround this issue by do not attempt to detect MCDRAM size and use hard-coded 16 GB instead.

Best Regards,
Grzegorz Andrejczuk

Correct output on hwloc 1.11.5
with some formatting
` hwloc-dump-hwdata -o .`
Dumping KNL SMBIOS Memory-Side Cache information:
  File = ///sys/firmware/dmi/entries/14-0/raw, size = 4096
  Found KNL type = 160
  Found KNL type = 161
  Seeking dir ̀'160-' 4
  File = ///sys/firmware/dmi/entries/160-0/raw, size = 4096
  Getting general KNL info
  Seeking dir ̀'161-' 4
  File = ///sys/firmware/dmi/entries/161-0/raw, size = 4096
  Getting MCDRAM KNL info. Count=8 struct size=12
  MCDRAM controller 0
  Size = 2048 MB
  MCDRAM controller 1
  Size = 2048 MB
  MCDRAM controller 2
  Size = 2048 MB
  MCDRAM controller 3
  Size = 2048 MB
  MCDRAM controller 4
  Size = 2048 MB
  MCDRAM controller 5
  Size = 2048 MB
  MCDRAM controller 6
  Size = 2048 MB
  MCDRAM controller 7
  Size = 2048 MB
  Total MCDRAM 16384 MB
  Cluster Mode: Quadrant Memory Mode: Cache
  MCDRAM total = 0 bytes, cache = 17179869184 bytes
  MCDRAM total = 0 bytes, cache = 17179869184 bytes per node

` cat knl_memoryside_cache`
version: 2
cache_size: 17179869184
associativity: 1
inclusiveness: 1
line_size: 64
cluster_mode: Quadrant
memory_mode: Cache

**Comment by johnnysmc** [comment]
@bgoglin
I did not try lstopo yet, but I tried to re-install the operating system to isolate if it's something going wrong. After fresh installation, it's still shown 8192 MB there.

@grzegorz-andrejczuk
I just used `dmidecode -t memory` to check MCDRAM units. If it's showing correctly, I should have 8 units there and each of them will carry with Size 2048 MB. When the problem happened, it's only 4 there. Is this normal?

**Comment by grzegorz-andrejczuk** [comment]
As I wrote this looks like BIOS is buggy and shows incorrectly some MCDRAM controllers as fused in DMI.
I created pull request #265 to workaround this issue.

When Linux/numactl -H shows 16 GB there is nothing to worry.
hwloc-dump-hwdata is used only to read cluster and memory modes and provide size of cache in cache mamory mode.

**Comment by johnnysmc** [comment]
@grzegorz-andrejczuk thanks. I will also consult with BIOS engineer and see if it's something wrong in BIOS code. Any further update will be provided shortly. Appreciate all your strong support.
