### ISSUE TITLE
visibility flags when embedding hwloc into shared library

### ISSUE THREAD

**Issue by raffenet** [open-mpi/hwloc#283]
We recently noticed an issue when using the embedding instructions here: https://www.open-mpi.org/projects/hwloc/doc/v1.11.8/a00304.php

`HWLOC_EMBEDDED_CFLAGS` may contain `-fvisibility=hidden` if supported by the compiler/linker. This can be problematic if we are embedding hwloc into a shared library, but don't want to deal with symbol visibility. A workaround is to set `enable_visibility=no` before calling `HWLOC_SETUP_CORE`, which has us working for the time-being. Is there any other way to avoid this issue that I'm not seeing?

**Comment by bgoglin** [comment]
cc @jsquyres

**Comment by jsquyres** [comment]
Setting `enable_visibility=no` is likely the Right answer here: it's the embedded equivalent of passing `--disable-visibility` on the command line.

Are you just checking in to see if there's a better way, or is there something less-than-optimal about setting `$enable_visibility`?

**Comment by raffenet** [comment]
Was just checking to see if there was a better way. I think the current method is probably good enough for our needs. Thanks!

**Comment by bgoglin** [comment]
Thanks guys, I am closing this then!
