### ISSUE TITLE
Infinite loop when using hwloc in embedded mode in mpich with opensolaris compiler

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [open-mpi/hwloc#290]
We are running into an infinite loop when using hwloc in embedded mode in mpich with compiler  Sun C 5.10 SunOS_i386 2009/06/03.
I see it’s because of the loop in look_proc method of topology-x86 where thread and core information are updated for each level of cache.

i don't see this problem when the library is linked directly. 

Log:
Reading a.out
Reading ld.so.1
Reading libm.so.2
Reading libmpi.so.0.0.0
Reading libc.so.1
Reading libkstat.so.1
Reading liblgrp.so.1
Reading libpciaccess.so.0.11.1
Reading libxml2.so.2.9.4
Reading libpthread.so.1
Reading libnsl.so.1
Reading libsocket.so.1
(dbx) run
Running: a.out 
(process id 29494)
^Cdbx: warning: Interrupt ignored but forwarded to child.
t@1 (l@1) signal INT (Interrupt) in hwloc_x86_cpuid at 0xfe8f0425
0xfe8f0425: hwloc_x86_cpuid+0x0015:     xchgl    %esi,%ebx
Current function is main
   27       MPI_Init(&argc, &argv);
(dbx) where
current thread: t@1
  [1] hwloc_x86_cpuid(0x80478a4, 0x80478a8, 0x80478a0, 0x80478ac), at 0xfe8f0425 
  [2] cpuid_or_from_dump(0x80478a4, 0x80478a8, 0x80478a0, 0x80478ac, 0x0, 0xa439795, 0xd), at 0xfe8f08b1 
  [3] look_proc(0x8082588, 0x8085b40, 0xd, 0xd, 0x80479c0, 0x0, 0x0, 0xfe8f2625), at 0xfe8f0fe0 
  [4] look_procs(0x8082588, 0x8085b40, 0x0, 0xd, 0xd, 0x80479c0, 0x0, 0xfe8edcd8, 0xfe8edb74, 0x0, 0x0, 0xfe8f292d), at 0xfe8f26ce 
  [5] hwloc_look_x86(0x8082588, 0x0, 0xf69890e4, 0xfe8f2d81), at 0xfe8f2ce1 
  [6] hwloc_x86_discover(0x8082588, 0xfea12290, 0x8047b08, 0xfe8cde24), at 0xfe8f2e28 
  [7] hwloc_discover(0x80821f8, 0x28, 0x80733b0, 0xfe8cec8b), at 0xfe8cde55 
  [8] hwloc_topology_load(0x80821f8, 0xfea12290, 0x8047b78, 0xfe70db30), at 0xfe8cee2c 
  [9] MPIR_Init_thread(0x8047ca0, 0x8047ca4, 0x0, 0x8047b9c), at 0xfe70db5a 
  [10] PMPI_Init(0x8047ca0, 0x8047ca4), at 0xfe70cd1f 
=>[11] main(argc = 1, argv = 0x8047ccc), line 27 in "cpi.c"

**Comment by bgoglin** [comment]
Can you reproduce it without MPICH?
If so, can you run hwloc-gather-cpuid and send a tarball of the "cpuid" directory that it will generate?

**Comment by KavithaTipturMadhu** [comment]
I could not reproduce the issue without mpich. The issue also seems to show up and then vanish inconsistently across mpich builds.

**Comment by KavithaTipturMadhu** [comment]
I can't seem to reproduce the issue with hwloc build and consistently in mpich either. I have attached the cpuid folder here. 
[cpuid.zip](https://github.com/open-mpi/hwloc/files/1701952/cpuid.zip)

**Comment by bgoglin** [comment]
I don't see anything suspect in the cpuid dump. Next time it happens, try to get a full backtrace with "bt full". If debug could be enabled with CFLAGS="-g -O0" and --enable-debug at configure, that would help.

**Comment by KavithaTipturMadhu** [comment]
I debugged this issue with suncc, what I noticed was the hwloc_x86_cpuid call ends up calling cpuid with eax to edx registers set to the argument values when hwloc is linked as a library. However, when used in mpich, the eax and ecx registers are not set to argument values when cpuid_or_from_dump query is made for cache type queries. Can you confirm that the registers eax and ecx ought to be set to 0x04 and cachenum respectively before cpuid instruction is executed?

**Comment by bgoglin** [comment]
Yes, for 'basic' cache detection, eax=0x4 and ecx=cachenum is a valid input for cpuid. You cannot have eax=0x4 with ecx different from something between 0 and the number of caches (usually 0=L1d, 1=L1i, 2=L2, 3=L3, 4=endmark, returns an invalid cache).

Other expected values for eax are between 0 and 0x16 or between 0x80000000 and 0x8000001e

Do you have a reproducible way to get a failing build now? Are you building the hwloc lib and mpich with the same compiler flags?

**Comment by KavithaTipturMadhu** [comment]
I am building with flags "-g -O0" and I see this issue popping up consistently across mpich builds with hwloc used in embedded mode.

**Comment by bgoglin** [comment]
The upstream issue https://github.com/pmodels/mpich/issues/2969 was closed as stale, let's close that one too.
