### ISSUE TITLE
man3 files installed in /usr/share/man

### ISSUE THREAD

**Issue by chris2553** [open-mpi/hwloc#291]
### What version of hwloc are you using?

$ which lstopo
/usr/bin/lstopo

$ lstopo --version
lstopo 2.0.0

$ rpm -qa hwloc
hwloc-2.0.0-1.x86_64
NOTE: built by me on a Linux From Scratch system with rpm added as package manager.

### Which operating system and hardware are you running on?

$ uname -a
Linux laptop 4.15.1 #1 SMP PREEMPT Sun Feb 4 23:10:36 GMT 2018 x86_64 GNU/Linux

## Details of the problem

A few of the man3 files are installed in /usr/share/man ($mandir in Makefile) instead of /usr/share/man/man3 ($man3dir}

### Additional information
This patch fixes the install:

--- hwloc-2.0.0/doc/Makefile.am~	2018-02-07 07:22:10.791959560 +0000
+++ hwloc-2.0.0/doc/Makefile.am	2018-02-07 07:22:25.787959254 +0000
@@ -569,7 +569,7 @@ man3_helper_ancestors_DATA = \
         $(DOX_MAN_DIR)/man3/hwloc_get_common_ancestor_obj.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_is_in_subtree.3
 
-man3_helper_find_typesdir = $(mandir)
+man3_helper_find_typesdir = $(man3dir)
 man3_helper_find_types_DATA = \
         $(DOX_MAN_DIR)/man3/hwlocality_helper_types.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_type_is_normal.3 \
--- hwloc-2.0.0/doc/Makefile.in~	2018-02-07 07:22:32.767959111 +0000
+++ hwloc-2.0.0/doc/Makefile.in	2018-02-07 07:22:51.151958736 +0000
@@ -907,7 +907,7 @@ EXTRA_DIST = \
 @HWLOC_INSTALL_DOXYGEN_TRUE@        $(DOX_MAN_DIR)/man3/hwloc_get_common_ancestor_obj.3 \
 @HWLOC_INSTALL_DOXYGEN_TRUE@        $(DOX_MAN_DIR)/man3/hwloc_obj_is_in_subtree.3
 
-@HWLOC_INSTALL_DOXYGEN_TRUE@man3_helper_find_typesdir = $(mandir)
+@HWLOC_INSTALL_DOXYGEN_TRUE@man3_helper_find_typesdir = $(man3dir)
 @HWLOC_INSTALL_DOXYGEN_TRUE@man3_helper_find_types_DATA = \
 @HWLOC_INSTALL_DOXYGEN_TRUE@        $(DOX_MAN_DIR)/man3/hwlocality_helper_types.3 \
 @HWLOC_INSTALL_DOXYGEN_TRUE@        $(DOX_MAN_DIR)/man3/hwloc_obj_type_is_normal.3 \

**Comment by bgoglin** [comment]
Thanks, I am applying this to master and v2.0 (only the Makefile.am part of the patch, Makefile.in will be updated by autogen).
Not sure why my custom install was already putting everything in man/man3/ without this fix...
