### ISSUE TITLE
2.0 regression on KNL

### ISSUE THREAD

**Issue by loveshack** [open-mpi/hwloc#293]
### What version of hwloc are you using?

2.0 built from tarball.  configure was run without arguments

```
-----------------------------------------------------------------------------
Hwloc optional build support status (more details can be found above):

Probe / display I/O devices: PCI(pciaccess+linux) LinuxIO
Graphical output (Cairo):    yes
XML input / output:          full
Netloc functionality:        no
Plugin support:              no
-----------------------------------------------------------------------------
```

* Run `which lstopo`to find out where your tools come from
* Run `lstopo --version` to find their hwloc version
* If hwloc comes from a RPM package (RHEL, CentOS, Fedora, etc.), run `rpm -qa '*hwloc*'`
* If hwloc comes from a DEB package (Debian, Ubuntu, Mint, etc.), run `dpkg -l '*hwloc*'`
* If hwloc was built from GIT, report the GIT hash (or at least the branch and date you checked out)
* If the hwloc error occured inside a non-hwloc process (e.g. MPI, SLURM, etc.), report the version of that software. Also try things like `ldd` on the program to find out which hwloc it is using.

### Which operating system and hardware are you running on?

RHEL 7, up-to-date (Linux 3.10.0-693.17.1.el7.x86_64)

* On Unix, run `uname -a` so that we know which operating system, distribution, and kernel version you are using.
* Post the output of `lstopo -` if it works
* Describe the machine and the processors it contains, as well as memory and/or peripherals if they matter to your issue

This is a KNL 7290 system with Dell BIOS 1.4.1 in snc-4/hybrid mode
lstopo:

```
Machine (136GB total)
  Package L#0
    Group0(Cluster) L#0
      NUMANode L#0 (P#0 32GB)
      NUMANode(MCDRAM) L#1 (P#4 2048MB)
      L2 L#0 (1024KB)
        L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
          PU L#0 (P#0)
          PU L#1 (P#72)
          PU L#2 (P#144)
          PU L#3 (P#216)
        L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
          PU L#4 (P#1)
          PU L#5 (P#73)
          PU L#6 (P#145)
          PU L#7 (P#217)
      L2 L#1 (1024KB)
        L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
          PU L#8 (P#2)
          PU L#9 (P#74)
          PU L#10 (P#146)
          PU L#11 (P#218)
        L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
          PU L#12 (P#3)
          PU L#13 (P#75)
          PU L#14 (P#147)
          PU L#15 (P#219)
      L2 L#2 (1024KB)
        L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
          PU L#16 (P#4)
          PU L#17 (P#76)
          PU L#18 (P#148)
          PU L#19 (P#220)
        L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
          PU L#20 (P#5)
          PU L#21 (P#77)
          PU L#22 (P#149)
          PU L#23 (P#221)
      L2 L#3 (1024KB)
        L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
          PU L#24 (P#6)
          PU L#25 (P#78)
          PU L#26 (P#150)
          PU L#27 (P#222)
        L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
          PU L#28 (P#7)
          PU L#29 (P#79)
          PU L#30 (P#151)
          PU L#31 (P#223)
      L2 L#4 (1024KB)
        L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
          PU L#32 (P#8)
          PU L#33 (P#80)
          PU L#34 (P#152)
          PU L#35 (P#224)
        L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
          PU L#36 (P#9)
          PU L#37 (P#81)
          PU L#38 (P#153)
          PU L#39 (P#225)
      L2 L#5 (1024KB)
        L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
          PU L#40 (P#10)
          PU L#41 (P#82)
          PU L#42 (P#154)
          PU L#43 (P#226)
        L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
          PU L#44 (P#11)
          PU L#45 (P#83)
          PU L#46 (P#155)
          PU L#47 (P#227)
      L2 L#6 (1024KB)
        L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12
          PU L#48 (P#12)
          PU L#49 (P#84)
          PU L#50 (P#156)
          PU L#51 (P#228)
        L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13
          PU L#52 (P#13)
          PU L#53 (P#85)
          PU L#54 (P#157)
          PU L#55 (P#229)
      L2 L#7 (1024KB)
        L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14
          PU L#56 (P#14)
          PU L#57 (P#86)
          PU L#58 (P#158)
          PU L#59 (P#230)
        L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15
          PU L#60 (P#15)
          PU L#61 (P#87)
          PU L#62 (P#159)
          PU L#63 (P#231)
      L2 L#8 (1024KB)
        L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16
          PU L#64 (P#16)
          PU L#65 (P#88)
          PU L#66 (P#160)
          PU L#67 (P#232)
        L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17
          PU L#68 (P#17)
          PU L#69 (P#89)
          PU L#70 (P#161)
          PU L#71 (P#233)
      HostBridge
        PCIBridge
          PCI 02:00.0 (Network)
            Net "ib0"
            OpenFabrics "mlx4_0"
        PCI 00:11.4 (SATA)
        PCIBridge
          PCI 04:00.0 (Ethernet)
            Net "em1"
        PCIBridge
          PCIBridge
            PCIBridge
              PCIBridge
                PCI 08:00.0 (VGA)
        PCI 00:1f.2 (SATA)
          Block(Disk) "sda"
          Block(Disk) "sdb"
[similar groups elided]

  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
  Misc(MemoryModule)
```

### Details of the problem

lstopo is not reporting the MCDRAM according to the 2.0 "best of lstopo" example, as above.

I realized hwloc-dump-hwdata is failing:

```
Dumping KNL SMBIOS Memory-Side Cache information:
  File = ///sys/firmware/dmi/entries/14-0/raw, size = 4096
SMBIOS table does not contain KNL entries
```

With 1.11.9 (rebuilt rpms), hwloc-dump-hwdata works, and lstopo gives the expected result.

* What happened?
* How did you start your process?
* How did it fail? Crash? Unexpected result?
* If crashed, can you get a `gdb` backtrace, etc?

### Additional information

github won't let me attach files.  I'm happy to mail the gather-topology files.

If your issue consists in a wrong topology detection, we'll also need this for debugging remotely:
* On Linux, run `hwloc-gather-topology myhost` and post the `myhost.*` files that it will generate (so that we may debug remotely).
* On MacOS, `sysctl hw` and `sysctl machdep.cpu`
* On Solaris, `kstat cpu_info` and `lgrp_info -a`
* On BSD, `sysctl hw`
* On BSD x86 platforms, if using hwloc >= 2.0, also run `hwloc-gather-cpuid` and post an archive of the `cpuid` that was generated.
* On Windows, `coreinfo -cgnlsm`

**Don't post these files on Github or on public mailing list if your machine is a top-secret prototype!**

Note that upgrading your operating system (e.g. Linux kernel) and platform firmwares (e.g. BIOS) might help solving issues about wrong topology detection.

**Comment by bgoglin** [comment]
The only difference I see in your output is the missing MemorySideCache (MCDRAM in cache mode). This is expected if hwloc-dump-hwdata failed.

Assuming you posted the entire output of hwloc-dump-hwdata above, can you post the entire output of that tool from hwloc 1.11.9?

**Comment by loveshack** [comment]
You wrote: 

> The only difference I see in your output is the missing
> MemorySideCache (MCDRAM in cache mode). This is expected if
> hwloc-dump-hwdata failed.

Yes (plus the list of the modules at the end, which I assume is
connected).  Apologies for not being more explicit.

> Assuming you posted the entire output of hwloc-dump-hwdata above, can
> you post the entire output of that tool from hwloc 1.11.9?

Here you are.  I can poke around with gdb or in /sys if you can suggest
what to check.  I didn't think it was worth trying trying to understand
quickly.

1.11.9:

  # /usr/sbin/hwloc-dump-hwdata
  Dumping KNL SMBIOS Memory-Side Cache information:
    File = ///sys/firmware/dmi/entries/14-0/raw, size = 4096
    Found KNL type = 160
    Found KNL type = 161
    Seeking dir ̀`160-' 4
    File = ///sys/firmware/dmi/entries/160-0/raw, size = 4096
    Getting general KNL info
    Seeking dir ̀`161-' 4
    File = ///sys/firmware/dmi/entries/161-0/raw, size = 4096
    Getting MCDRAM KNL info. Count=8 struct size=12
    MCDRAM controller 0
    Size = 2048 MB
    MCDRAM controller 1
    Size = 2048 MB
    MCDRAM controller 2
    Size = 2048 MB
    MCDRAM controller 3
    Size = 2048 MB
    MCDRAM controller 4
    Size = 2048 MB
    MCDRAM controller 5
    Size = 2048 MB
    MCDRAM controller 6
    Size = 2048 MB
    MCDRAM controller 7
    Size = 2048 MB
    Total MCDRAM 16384 MB
    Cluster Mode: SNC4 Memory Mode: Hybrid50
    MCDRAM total = 8589934592 bytes, cache = 8589934592 bytes
    MCDRAM total = 2147483648 bytes, cache = 2147483648 bytes per node

2.0:

  # /usr/local/sbin/hwloc-dump-hwdata 
  Dumping KNL SMBIOS Memory-Side Cache information:
    File = ///sys/firmware/dmi/entries/14-0/raw, size = 4096
  SMBIOS table does not contain KNL entries

**Comment by bgoglin** [comment]
MemoryModules at the end are DIMM information. It's only accessible when running as root, forget about them.

Then we'll need a tarball from /sys/firmware/dmi/. Either hwloc-gather-topology with --dmi, or a manually-built tarball.

**Comment by bgoglin** [comment]
Don't use tar. These special files have length=0 even if they are not empty when you read them. hwloc-gather-topology --dmi takes care of working around that issue. I am also trying to get same info from a local Dell KNL node in the meantime.

**Comment by loveshack** [comment]
I'll mail you the gather-topology files separately as I don't know what
will happen to them in a reply and I'm not going to try to debug the
problems uploading them to github.  Let me know if they don't turn up
shortly.

[It might be worth a warning about hwloc-gather-topology being slow on
big systems.  It took seven minutes on this one, and I did wonder if it
was stuck.]

**Comment by bgoglin** [comment]
@grzegorz-andrejczuk This Dell BIOS contains "Knights Landing Association" instead of "Group: Knights Landing Information". What should we do? If vendors use random strings like this, hwloc-dump-hwdata won't work anymore except on Intel baseboards? Should we revert to matching everything? Or look for KN or Knights anywhere in the string?

@loveshack Thanks for the files. I'll document that gather-topology is slow (and make it more verbose too).

**Comment by grzegorz-andrejczuk** [comment]
DMI group entry is part of standard, so without the check hwdata could read something else and wander on DMI sysfs (having root/system service privileges).
We could add argument forcing to ignore this check or supplying user defined string. Then check can be avoided when system administrator wants to avoid it.

**Comment by bgoglin** [comment]
@grzegorz-andrejczuk Should we at least whitelist some known other values? I got the same "Knights Landing Association" on another C6320p Dell machine with a different BIOS version, so I guess most Dell KNLs will report this. Otherwise, most Dells will be screwed forever unless they have a very good reason to update their BIOS and you manage to force Dell to fix this :/

Do you have access to other vendors' KNL to check this?

**Comment by grzegorz-andrejczuk** [comment]
I prepared simple patch for this issue

**Comment by loveshack** [comment]
For anyone else coming across this a fix, the 1.11 file seems to be
compatible with 2.0.  (Brice please say if not.)  I did

ln -sf /var/run/hwloc/knl_memoryside_cache /usr/local/var/run/hwloc/

so the 2.0 version in /usr/local gets updates from the 1.11 service.

**Comment by grzegorz-andrejczuk** [comment]
You can also use (1.11) `hwloc-dump-hwdata -o {your dir to store files} `
or 
`HWLOC_DUMPED_HWDATA_DIR="/var/run/hwloc" lstopo ` when calling hwloc 2.0

**Comment by grzegorz-andrejczuk** [comment]
I checked on Intel KNL and KNM.
https://github.com/open-mpi/hwloc/pull/295
@bgoglin @loveshack Could you check it on Dell machine?

**Comment by bgoglin** [comment]
@loveshack I verified that it works on your files.
