### ISSUE TITLE
hwloc_type_sscanf test fails with 2.0.0 and PGI 18.1 compiler

### ISSUE THREAD

**Issue by cponder** [open-mpi/hwloc#298]
I built hwloc/2.0.0 on CentOS 7.3 based on the kernel

       Linux hsw218 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

using the PGI 18.1 compiler. This regression-test failed

      FAIL: hwloc_type_sscanf

with this message in the Summary

      See tests/hwloc/test-suite.log
      Please report to http://www.open-mpi.org/projects/hwloc/

The log-file had this line

      FAIL hwloc_type_sscanf (exit status: 33)

Tell me if there's any other information I can provide.

**Comment by cponder** [comment]
There's this issue logged

        https://github.com/open-mpi/hwloc/issues/195

but it mentions other failures that aren't happening here, so I assume the root-cause is different.

**Comment by cponder** [comment]
Trying to build OpenMPI 3.1.0rc1 with it, I get this error. Building with hwloc/1.11.9 didn't have the problem.

PGC-S-0060-allowed_cpuset is not a member of this struct or union (base/hwloc_base_util.c: 152)
PGC-W-0095-Type cast required for this conversion (base/hwloc_base_util.c: 152)
PGC-W-0155-Pointer value created from a nonlong integral type  (base/hwloc_base_util.c: 152)
PGC-S-0060-allowed_cpuset is not a member of this struct or union (base/hwloc_base_util.c: 176)
PGC-W-0095-Type cast required for this conversion (base/hwloc_base_util.c: 176)
PGC-W-0155-Pointer value created from a nonlong integral type  (base/hwloc_base_util.c: 176)
PGC-S-0060-allowed_cpuset is not a member of this struct or union (base/hwloc_base_util.c: 198)
PGC-W-0095-Type cast required for this conversion (base/hwloc_base_util.c: 198)
PGC-W-0155-Pointer value created from a nonlong integral type  (base/hwloc_base_util.c: 198)
PGC/x86-64 Linux 18.1-1: compilation completed with severe errors
make[2]: *** [base/hwloc_base_util.lo] Error 1

**Comment by bgoglin** [comment]
Hello

When you get such a failure, please try to run the failing program manually. You will likely get an assert failure, and you will be able to add some printfs to further see what's the expected and unexpected values that cause the failure. The code is in tests/hwloc/hwloc_type_sscanf.c. You can rerun it with tests/hwloc/hwloc_type_sscanf and rebuild it when needed with make hwloc_type_sscanf -C tests/hwloc

I removed your other comments, they are unrelated. FWIW OMPI has not been ported to the final 2.0 API yet. See ompi#4677 for patches.

**Comment by cponder** [comment]
*On 02/16/2018 12:11 AM, Brice Goglin wrote:*
>
>     When you get such a failure, please try to run the failing program
>     manually. You will likely get an assert failure, and you will be
>     able to add some printfs to further see what's the expected and
>     unexpected values that cause the failure. The code is in
>     tests/hwloc/hwloc_type_sscanf.c. You can rerun it with
>     tests/hwloc/hwloc_type_sscanf and rebuild it when needed with make
>     hwloc_type_sscanf -C tests/hwloc
>
Brice -- when I ran it, it didn't print out any message.
But $? returned the 33 value.

         -- Carl



-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------

**Comment by bgoglin** [comment]
I have no idea what this 33 could mean. Does another PGI compiler or a non-PGI compiler change anything?

**Comment by bgoglin** [comment]
Any news about this?

**Comment by cponder** [comment]
I'll pick this up again when I can start using 2.* with the new OpenMPI's.
The 3.0.* & 3.1.* are still in their first (or pre-) release so I they're not in working order for us.
If you want to close the thread, I can just open a new one if I see the problem down the line.

**Comment by bgoglin** [comment]
hwloc 2.0 won't be supported in OMPI very soon. Officially only in 4.0, maybe earlier, but not in 3.1.0. Let's close this for now, thanks.
