### ISSUE TITLE
Tiling of cores on a KNL node

### ISSUE THREAD

**Issue by elliottslaughter** [open-mpi/hwloc#299]
I'm wondering if it's possible to use hwloc (or anything, really) to determine how cores are tiled on a KNL node. Basically, I'm looking to make a diagram like this one:

![](http://www.nersc.gov/assets/Uploads/KNLOverview.png)

But with the tiles numbered with the actual IDs of cores on a real, live running KNL node. At the moment, the best I can seem to do with lstopo is this:

http://www.nersc.gov/assets/Uploads/knl-snc4-flat.pdf

Which tells me which IDs are in which quadrants/tiles, but not where the cores are on the mesh interconnect of the node. (Note therefore that this is different from #209, which if I understand correctly was asking for the distances between NUMA nodes. I already understand how NUMA nodes are related, and now I'm loooking to understand cores.)

Is this possible to do this with hwloc (or any other tool)?

Thanks.

### What version of hwloc are you using?

Version 1.11.4 on NERSC Cori (a Cray machine).

```
$ which lstopo
/usr/bin/lstopo
$ lstopo --version
lstopo 1.11.4
```

**Comment by bgoglin** [comment]
Hello

We got that request several times but this information is not available unfortunately. Possible reasons include the fact that it's hard to expose that informationbecause it likely changes from one machine to another (even if the model of KNL is the same, it depends on which tiles are enabled among the 38 on the die). Also people would hardwire things that depends on the layout of tiles in their code, which means Intel won't be able to change tile numbers anymore (that argument doesn't stands anymore now that KNL is abandoned).

Anyway, some people tried to guess the location on the mesh from microbenchmarks. It worked on KNC but I haven't seen any useful result on KNL. If somebody ever get that information, we could use hwloc's distance API to expose it.

**Comment by elliottslaughter** [comment]
Thanks, that makes sense. I'll go ahead and close this issue, since KNL doesn't warrant putting that much time into at this point.
