### ISSUE TITLE
libhwloc.la libdir not set correctly

### ISSUE THREAD

**Issue by cponder** [open-mpi/hwloc#310]
I'm building HWloc 1.11.10 on Ubuntu 16.04 with the PGI 18.4 compiler.
I haven't seen this issue with builds on CentOS.
I'm using this configure setting to install to a side-directory

        PREFIXPATH=/gpfs/fs1/SHARE/Utils/HWLoc/1.11.10/PGI-18.4_CUDA-9.1.85
        ./configure -prefix=$PREFIXPATH ....

since we're using Lmod to manage alternative library builds.
The last 2 lines of the lib/libhwloc.la read as follows:

        # Directory that this library needs to be installed in:
        libdir='/usr/lib/x86_64-linux-gnu'

When I go on to build other components like OpenMPI and HDF5 I see these warnings

       libtool: warning: '/gpfs/fs1/SHARE/Utils/HWLoc/1.11.10/PGI-18.4_CUDA-9.1.85/lib/libhwloc.la' seems to be moved

which don't break the build, but I think there ought to be an easy way to fix this.
Do I need to use -rpath somehow, for example?

**Comment by bgoglin** [comment]
I have never seen PREFIXPATH, and I don't see any reference to it in the autoconf-generated configure. Is PREFIXPATH a non-standard way to pass --prefix on the configure command-line?
$libdir is set based on $prefix. Can you try --prefix instead of $PREFIXPATH ?

**Comment by cponder** [comment]
Sorry --I had omitted this

./configure --prefix=$PREFIXPATH  ....

I just put it into the description at the top, we might want to delete these two comments.

**Comment by bgoglin** [comment]
libdir is correctly set to $prefix/blabla in libhwloc.la on my Ubuntu 16.04 amd64 VM (GCC 4:5.3.1-1ubuntu1 and libtool 2.4.6-0.1). Tried with 1.11.10 and latest git master.

I don't know what could fail like this. I don't think PGI touches any of this, but can you try with the default compiler anyway?

**Comment by bgoglin** [comment]
I've seen it too, without caring about it. But still libhwloc.la shouldn't point to a wrong libdir

**Comment by jsquyres** [comment]
Is that the `.la` in the build tree or the installation tree?

**Comment by cponder** [comment]
It's the .ls that's in the installation directory.
Also, I'm seeing some real breakage now, in the HDF5 build:

libtool: warning: '/gpfs/fs1/SHARE/Utils/HWLoc/1.11.10/PGI-18.4_CUDA-9.1.85/lib/libhwloc.la' seems to be moved
libtool: warning: library '/gpfs/fs1/SHARE/Utils/HWLoc/1.11.10/PGI-18.4_CUDA-9.1.85/lib/libhwloc.la' was moved.
/bin/grep: /usr/lib/x86_64-linux-gnu/libhwloc.la: No such file or directory
/bin/sed: can't read /usr/lib/x86_64-linux-gnu/libhwloc.la: No such file or directory
libtool:   error: '/usr/lib/x86_64-linux-gnu/libhwloc.la' is not a valid libtool archive
Makefile:905: recipe for target 'libhdf5_cpp.la' failed
make[2]: *** [libhdf5_cpp.la] Error 1
make[2]: Leaving directory '/gpfs/fs1/SHARE/Utils/HDF5/1.10.2/PGI-18.4_SZip-2.1.1_ZLib-1.2.11_OpenMPI-3.0.1_CUDA-9.1.85_HWloc-1.11.10/distro/c++/src

**Comment by bgoglin** [comment]
As requested above, try without PGI. And check which libtool/libtoolize is being used (where do them come from and which version they are).

**Comment by jsquyres** [comment]
I can't imagine how the libdir got set to be something else in `libhwloc.la` other than the actual `libdir`.

Can you send the output of configure, your `config.log`, and the output from `make clean; make V=1 install`?

**Comment by cponder** [comment]
Editing the libhwloc.la didn't fix the HDF5 build problem. So there's 2 things

1. the fact it got set oddly
2. the fact that the HDF5 build is trying to find it in the wrong place

I think #2 is because the bad libdir setting is inhertied when I built OpenMPI and then applied to the HDF5 build.
I'll take a closer look at the way PGI is doing linkages.
If i don't find an answer I'll do the GCC comparison as Bryce recommended.
And post the build logs based on what turns up.

**Comment by cponder** [comment]
Here's the problem:

  -rpath LIBDIR     the created library will eventually be installed in LIBDIR

I had been using -rpath this because the build was picking up the wrong libnuma.so, and -L didn't seem to fix the problem. I can set LD_PRELOAD to the path instead of using -rpath in the LDFLAGS.
You're welcome to close this ticket, I can still view the details while I figure out why I need special linkage for the libnuma.

**Comment by cponder** [comment]
(closing it myself)
