### ISSUE TITLE
should be able to disable components from the API

### ISSUE THREAD

**Issue by sthibaul** [open-mpi/hwloc#326]
Hello, a bit of context: in StarPU we use hwloc with `HWLOC_TOPOLOGY_FLAG_IO_DEVICES | HWLOC_TOPOLOGY_FLAG_IO_BRIDGES`   to detect where GPUs are. Such detection is very expensive when persistent mode is not enabled. We would thus like to be able to disable the components we do not need: if StarPU is built with only OpenCL support, disable the CUDA hwloc component, and vice-versa.

AIUI the only way to disable a component is `export HWLOC_COMPONENTS=-cuda`, but setting an environment variable is not safe, we'd rather use an API attached to `hwloc_topology_t`.

Samuel

**Comment by bgoglin** [comment]
Merged into #252
