### ISSUE TITLE
Question: hwloc and hyper-threads on virtual machines

### ISSUE THREAD

**Issue by angainor** [open-mpi/hwloc#349]
Hi,

Does anyone know a virtual machine solution, which could be configured in such a way that hwloc will report the existence of Hyper-threads, cores, and numa-nodes? We need this to simulate a production environment for testing things like MPI binding. The closest we've found is VMware, which can be configured to CPUs and cores per CPU, but AFAIK not hw threads.

Thanks a lot!

**Comment by sthibaul** [comment]
From man qemu-system, I see

       -smp
       [cpus=]n[,cores=cores][,threads=threads][,sockets=sockets][,maxcpus=maxcpus]
           Simulate an SMP system with n CPUs. On the PC target, up to 255
           CPUs are supported. On Sparc32 target, Linux limits the number of
           usable CPUs to 4.  For the PC target, the number of cores per
           socket, the number of threads per cores and the total number of
           sockets can be specified. Missing values will be computed. If any
           on the three values is given, the total number of CPUs n can be
           omitted. maxcpus specifies the maximum number of hotpluggable CPUs.

       -numa node[,mem=size][,cpus=firstcpu[-lastcpu]][,nodeid=node]
       -numa node[,memdev=id][,cpus=firstcpu[-lastcpu]][,nodeid=node]
       -numa dist,src=source,dst=destination,val=distance
       -numa cpu,node-id=node[,socket-id=x][,core-id=y][,thread-id=z]
           Define a NUMA node and assign RAM and VCPUs to it.  Set the NUMA
           distance from a source node to a destination node.

           For example, the following option assigns VCPUs 0, 1, 2 and 5 to a
           NUMA node:

                   -numa node,cpus=0-2,cpus=5

**Comment by bgoglin** [comment]
Indeed, I often use something like this to get a dual-socket NUMA dual-core HT machine (8 threads total):
```
kvm -hda foo.img -smp cpus=8,threads=2,cores=2,sockets=2 -numa node,cpus=0-3,nodeid=0 -numa node,cpus=4-7,nodeid=1
```
