### ISSUE TITLE
Win7, Ryzen 5 2600 caches misidentified

### ISSUE THREAD

**Issue by gwoltman** [open-mpi/hwloc#360]
A user of prime95 is reporting issues with hwloc 2.0.3 and 2.0.4rc1 on a Ryzen 5 2600.  Prime95 relies on hwloc to identify cache heirarchy.  Hwloc is reporting this 6 core processor has 12 L1, L2, and L3 caches.  See https://www.mersenneforum.org/showpost.php?p=518768&postcount=280

I do not have access to this machine.  

Prime95 does have a feature to dump hwloc info.  Here is the output:

`Machine#0 (total=27862856KB, Backend=Windows, hwlocVersion=2.0.4rc1, ProcessName=prime95.exe)
Package (total=27862856KB, CPUVendor=AuthenticAMD, CPUFamilyNumber=23, CPUModelNumber=8, CPUModel="AMD Ryzen 5 2600 Six-Core Processor ", CPUStepping=2)
Core (cpuset: 0x00000003)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#0 (cpuset: 0x00000001)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#1 (cpuset: 0x00000002)
Core (cpuset: 0x0000000c)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#2 (cpuset: 0x00000004)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#3 (cpuset: 0x00000008)
Core (cpuset: 0x00000030)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#4 (cpuset: 0x00000010)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#5 (cpuset: 0x00000020)
Core (cpuset: 0x000000c0)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#6 (cpuset: 0x00000040)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#7 (cpuset: 0x00000080)
Core (cpuset: 0x00000300)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#8 (cpuset: 0x00000100)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#9 (cpuset: 0x00000200)
Core (cpuset: 0x00000c00)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#10 (cpuset: 0x00000400)
L3 (size=16384KB, linesize=64, ways=16, Inclusive=0)
L2 (size=512KB, linesize=64, ways=8, Inclusive=1)
L1d (size=32KB, linesize=64, ways=8, Inclusive=0)
PU#11 (cpuset: 0x00000800)`

**Comment by bgoglin** [comment]
When you opened the issue, there was a template asking for useful information about the operating system. If he's running Windows, we'd need something like the output of "coreinfo -cgnlsm".

It might be good to test with HWLOC_COMPONENTS set to "x86,stop" in the environment and then set to "-x86" to see if the buggy information comes from Windows or from the processor. My guess is that Windows doesn't support that processor well yet.

**Comment by gwoltman** [comment]
The user reports:

> Coreinfo v3.31 - Dump information on system CPU and memory topology
Copyright (C) 2008-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

Logical to Physical Processor Map:
**----------  Physical Processor 0 (Hyperthreaded)
--**--------  Physical Processor 1 (Hyperthreaded)
----**------  Physical Processor 2 (Hyperthreaded)
------**----  Physical Processor 3 (Hyperthreaded)
--------**--  Physical Processor 4 (Hyperthreaded)
----------**  Physical Processor 5 (Hyperthreaded)

Logical Processor to Socket Map:
************  Socket 0

Logical Processor to NUMA Node Map:
************  NUMA Node 0

No NUMA nodes.

Logical Processor to Cache Map:
*-----------  Data Cache          0, Level 1,   32 KB, Assoc   8, LineSize  64
*-----------  Instruction Cache   0, Level 1,   64 KB, Assoc   4, LineSize  64
*-----------  Unified Cache       0, Level 2,  512 KB, Assoc   8, LineSize  64
*-----------  Unified Cache       1, Level 3,   16 MB, Assoc  16, LineSize  64
-*----------  Data Cache          1, Level 1,   32 KB, Assoc   8, LineSize  64
-*----------  Instruction Cache   1, Level 1,   64 KB, Assoc   4, LineSize  64
-*----------  Unified Cache       2, Level 2,  512 KB, Assoc   8, LineSize  64
-*----------  Unified Cache       3, Level 3,   16 MB, Assoc  16, LineSize  64
--*---------  Data Cache          2, Level 1,   32 KB, Assoc   8, LineSize  64
--*---------  Instruction Cache   2, Level 1,   64 KB, Assoc   4, LineSize  64
--*---------  Unified Cache       4, Level 2,  512 KB, Assoc   8, LineSize  64
--*---------  Unified Cache       5, Level 3,   16 MB, Assoc  16, LineSize  64
---*--------  Data Cache          3, Level 1,   32 KB, Assoc   8, LineSize  64
---*--------  Instruction Cache   3, Level 1,   64 KB, Assoc   4, LineSize  64
---*--------  Unified Cache       6, Level 2,  512 KB, Assoc   8, LineSize  64
---*--------  Unified Cache       7, Level 3,   16 MB, Assoc  16, LineSize  64
----*-------  Data Cache          4, Level 1,   32 KB, Assoc   8, LineSize  64
----*-------  Instruction Cache   4, Level 1,   64 KB, Assoc   4, LineSize  64
----*-------  Unified Cache       8, Level 2,  512 KB, Assoc   8, LineSize  64
----*-------  Unified Cache       9, Level 3,   16 MB, Assoc  16, LineSize  64
-----*------  Data Cache          5, Level 1,   32 KB, Assoc   8, LineSize  64
-----*------  Instruction Cache   5, Level 1,   64 KB, Assoc   4, LineSize  64
-----*------  Unified Cache      10, Level 2,  512 KB, Assoc   8, LineSize  64
-----*------  Unified Cache      11, Level 3,   16 MB, Assoc  16, LineSize  64
------*-----  Data Cache          6, Level 1,   32 KB, Assoc   8, LineSize  64
------*-----  Instruction Cache   6, Level 1,   64 KB, Assoc   4, LineSize  64
------*-----  Unified Cache      12, Level 2,  512 KB, Assoc   8, LineSize  64
------*-----  Unified Cache      13, Level 3,   16 MB, Assoc  16, LineSize  64
-------*----  Data Cache          7, Level 1,   32 KB, Assoc   8, LineSize  64
-------*----  Instruction Cache   7, Level 1,   64 KB, Assoc   4, LineSize  64
-------*----  Unified Cache      14, Level 2,  512 KB, Assoc   8, LineSize  64
-------*----  Unified Cache      15, Level 3,   16 MB, Assoc  16, LineSize  64
--------*---  Data Cache          8, Level 1,   32 KB, Assoc   8, LineSize  64
--------*---  Instruction Cache   8, Level 1,   64 KB, Assoc   4, LineSize  64
--------*---  Unified Cache      16, Level 2,  512 KB, Assoc   8, LineSize  64
--------*---  Unified Cache      17, Level 3,   16 MB, Assoc  16, LineSize  64
---------*--  Data Cache          9, Level 1,   32 KB, Assoc   8, LineSize  64
---------*--  Instruction Cache   9, Level 1,   64 KB, Assoc   4, LineSize  64
---------*--  Unified Cache      18, Level 2,  512 KB, Assoc   8, LineSize  64
---------*--  Unified Cache      19, Level 3,   16 MB, Assoc  16, LineSize  64
----------*-  Data Cache         10, Level 1,   32 KB, Assoc   8, LineSize  64
----------*-  Instruction Cache  10, Level 1,   64 KB, Assoc   4, LineSize  64
----------*-  Unified Cache      20, Level 2,  512 KB, Assoc   8, LineSize  64
----------*-  Unified Cache      21, Level 3,   16 MB, Assoc  16, LineSize  64
-----------*  Data Cache         11, Level 1,   32 KB, Assoc   8, LineSize  64
-----------*  Instruction Cache  11, Level 1,   64 KB, Assoc   4, LineSize  64
-----------*  Unified Cache      22, Level 2,  512 KB, Assoc   8, LineSize  64
-----------*  Unified Cache      23, Level 3,   16 MB, Assoc  16, LineSize  64

Logical Processor to Group Map:
************  Group 0

**Comment by bgoglin** [comment]
coreinfo has the same bug, this likely confirms that the bug is in windows. You may want to update your windows since this processor is very recent.

**Comment by gwoltman** [comment]
Thanks.  Will relay this info to my user.

**Comment by bgoglin** [comment]
If he finds out something like "only supported in Windows 10 build XYZ and not in Windows 7", I'd be interested in knowing that.
