### ISSUE TITLE
hwloc fails to detect GPUs in Google Cloud Deep Learning VM with 8 V100 GPUs

### ISSUE THREAD

**Issue by denfromufa** [open-mpi/hwloc#365]
### What version of hwloc are you using?

```
    4  wget https://download.open-mpi.org/release/hwloc/v2.0/hwloc-2.0.4.tar.gz
    5  ./configure --prefix=$HOME/install
    6  make
    7  make install
    8  which lstopo-no-graphics
    9  lstopo
   10  export PATH=$PATH:$HOME/install/bin
   11  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/install/lib
   12  export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/install/lib/pkgconfig
   13  export MANPATH=$MANPATH:$HOME/install/share/man
   15  lstopo-no-graphics --no-caches --merge --ignore PU
```

![image](https://user-images.githubusercontent.com/7870949/63117198-e0c0ad00-bf60-11e9-940e-71eb607b3ecf.png)

### Which operating system and hardware are you running on?

`Linux tensorflow-1-vm 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux`

**Comment by denfromufa** [comment]
I also uploaded the log for `hwloc-gather-topology myhost`

[gcp_vm.zip](https://github.com/open-mpi/hwloc/files/3506765/gcp_vm.zip)

**Comment by denfromufa** [comment]
nvidia-smi works ok:

![image](https://user-images.githubusercontent.com/7870949/63117590-bf13f580-bf61-11e9-8aed-e17297fc8e2f.png)

**Comment by bgoglin** [comment]
GPUs are actually detected here: as "8x" PCI devices of type "3D" (line below the hostbridge). What additional information do you need? If you want to relevant CUDA info for these GPUs, you need to check whether CUDA is detected during configure (check the summary at the end of configure). NVML might help too (but it's not always installed, check configure too). OpenCL (check configure too).

**Comment by bgoglin** [comment]
I am going to assume my answer above was enough. If you have further questions or need more features, feel free to reopen. Thank
