### ISSUE TITLE
_hwloc-info: not a valid identifier

### ISSUE THREAD

**Issue by kaipee** [open-mpi/hwloc#381]
### What version of hwloc are you using?
2.1.0-2

### Which operating system and hardware are you running on?
Arch Linux
Linux gb-lis-sys-21 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux

### Details of the problem
Symptoms of the issue are : failure to login to gnome-session (xorg) via GDM.

Logs show an error with the bash-completion file
`/etc/bash_completion.d/hwloc-completion.bash: line 193: _hwloc-info: not a valid identifier`

Removing the bash-completion package resolves the login issue.

### Additional info

https://bbs.archlinux.org/viewtopic.php?pid=1884144#p1884144

**Comment by bgoglin** [comment]
Does a plain bash (not GDM) also report the same error? If so, which version of bash do you have? My bash 5.0.11 looks happy.

**Comment by bgoglin** [comment]
It looks like '-' is not allowed in bash function names (while '_' is allowed). Maybe it changed in recent bash releases. If you can confirm that renaming _hwloc-info to _hwlocinfo where it's defined and used (and remove the rest of the file because there are many other functions with the same issue), I'll fix that quickly.

**Comment by kaipee** [comment]
> Does a plain bash (not GDM) also report the same error? If so, which version of bash do you have? My bash 5.0.11 looks happy.

Yes simply logging in from tty works fine via startx.

**Comment by kaipee** [comment]
> It looks like '-' is not allowed in bash function names (while '_' is allowed). Maybe it changed in recent bash releases. If you can confirm that renaming _hwloc-info to _hwlocinfo where it's defined and used (and remove the rest of the file because there are many other functions with the same issue), I'll fix that quickly.

Yes I have confirmed that correcting the BASH function/alias works.

s/hwloc-info/hwlocinfo/g works fine

**Comment by buczek** [comment]
Just for reference:

https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html

- "When invoked as sh, Bash enters POSIX mode after reading the startup files."
-  [ when ‘POSIX mode’ is in effect ] "Function names must be valid shell names. That is, they may not contain characters other than letters, digits, and underscores, and may not start with a digit. Declaring a function with an invalid name causes a fatal syntax error in non-interactive shells."

So the problem might appear, for example, on systems which use bash as ` /bin/sh`  and then bash is invoked via such a path by the shell setting of the user or a tool with a hardcoded ` /bin/sh` path.
