### ISSUE TITLE
hwloc-2.0.3 warnings

### ISSUE THREAD

**Issue by pavanbalaji** [open-mpi/hwloc#384]
### What version of hwloc are you using?

hwloc version 2.0.3 inside `mpich/master`.

### Which operating system and hardware are you running on?

Ubuntu 19.10

```
% gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
% uname -a
Linux vflake01 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Details of the problem

Warnings during build.  The key reproduction flags seem to be `-Wcpp` and `-Wstack-usage`, althrough `-Wall` might be needed too.

### Additional information

I see the following warnings while building `hwloc`:

```
In file included from ../../../../mpich/src/hwloc/hwloc/topology.c:45:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
../../../../mpich/src/hwloc/hwloc/distances.c: In function 'hwloc__groups_by_distances':
../../../../mpich/src/hwloc/hwloc/distances.c:817:1: warning: stack usage might be unbounded [-Wstack-usage=]
  817 | hwloc__groups_by_distances(struct hwloc_topology *topology,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../mpich/src/hwloc/hwloc/topology.c: In function 'hwloc_propagate_symmetric_subtree':
../../../../mpich/src/hwloc/hwloc/topology.c:2388:1: warning: stack usage might be unbounded [-Wstack-usage=]
 2388 | hwloc_propagate_symmetric_subtree(hwloc_topology_t topology, hwloc_obj_t root)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Other similar warnings occur too, which I've dropped here to avoid redundancy.

**Comment by bgoglin** [comment]
Hello Pavan
Stack usage warnings are fixed in 2.1 since your issue #353 :)
sys/sysctl.h is protected by HAVE_SYS_SYSCTL_H so I guess things will work fine when it gets removed for real. But we need that file for non-Linux builds.

**Comment by pavanbalaji** [comment]
@bgoglin Thanks, we'll upgrade to 2.1.  For the `sys/sysctl.h` warning, can't this be tested for in configure?  It's unclear how many years it'll be before they remove it for real.

**Comment by bgoglin** [comment]
How do you make the compiler generate a warning about sys/sysctl.h? I've never seen one.

**Comment by pavanbalaji** [comment]
I don't understand.  Just include it in a simple file:

```
% cat foo.c 
#include <sys/sysctl.h>

int main()
{
    return 0;
}
```

```
% gcc -Wcpp -Werror foo.c
In file included from foo.c:1:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
cc1: all warnings being treated as errors
```

**Comment by bgoglin** [comment]
gcc 10 ? I have 9.2 here.

**Comment by pavanbalaji** [comment]
I have `gcc 9.2.1` (full version information in the issue description above).

**Comment by pavanbalaji** [comment]
Although, I'd be surprised if it's specific to the GCC version.  It's a regular `#warning`, which should show up for very old compilers too.

**Comment by bgoglin** [comment]
Looks like it was added in glibc 2.29 in 2019. Not sure why my glibc 2.29 doesn't have it.
Anyway, I'll look at disabling that on Linux, we already disable some other sysct checks on Linux for other reasons.

**Comment by pavanbalaji** [comment]
@bgoglin With hwloc-2.1, I'm seeing a different set of warnings:

```
../../../../mpich/src/hwloc/hwloc/components.c: In function 'hwloc_disc_components_enable_others':
../../../../mpich/src/hwloc/hwloc/components.c:698:9: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  698 |    name = "linux";
      |         ^
```

**Comment by bgoglin** [comment]
For some reason, these warnings actually appears when we pass -Wwrite-strings instead of -Wdiscarded-qualifiers. I am going to add that flag to our picky flags (and fix the warnings).
Can you provide the list of flags that I should also enable for developer builds when they are supported by GCC ?

**Comment by pavanbalaji** [comment]
Here's the list of compile flags that we use in MPICH:

https://github.com/pmodels/mpich/blob/master/confdb/aclocal_cc.m4#L491

Configure checks and picks the subset that the compiler accepts.

**Comment by pavanbalaji** [comment]
@bgoglin I see that the fixes for these have already gotten into `master`.  Is there a plan for a `v2.1.1` release that'd include this patch?  If yes, can you share the planned timeline for it with us?  Thanks!

**Comment by bgoglin** [comment]
The current plan is rather to release a "small" major release 2.2.0 within a month.
There isn't enough in the 2.1 branch to justify a 2.1.1 release.
The 2.2 branch doesn't contain lots of changes either, but there's no reason to delay their release.

**Comment by pavanbalaji** [comment]
Would you be able to point me to the patches that fixed the warnings?  We can cherry-pick them for our code while you work on the `v2.2` release.

**Comment by bgoglin** [comment]
On the v2.1 branch, I think you'd want:
```
commit 29866b65c55722c587594198feb46ac1e395325b
    misc: fix warnings about const qualifier being discarded
commit ecea0a65e82257344439fcd6ef3549ce6ddc962c
    configure: disable sys/sysctl.h on Linux
commit 44a7d69affa2d9983d0b8bced694bdbe3b79ab3d
    core: remove variable-length arrays
```
