### ISSUE TITLE
counting DRM devices using topology info read via hwloc

### ISSUE THREAD

**Issue by npadole20** [open-mpi/hwloc#386]
I am trying to count the number of GPUs by parsing the xml information returned by hwloc_topology_export_xmlbuffer(). 
1. I tried counting the number of 'cardX' reported in the topology data. But this does not give the correct card information as display devices are also listed as 'card' like so-

>         <object type="OSDev" name="cardX" osdev_type="1"/>
>         <object type="OSDev" name="controlXXX" osdev_type="1"/>

2. I excluded the number of 'cardX' and 'controlXXX' combinations from the gpu count. But I encountered a condition where a valid GPU device is listed like so -

>         <object type="OSDev" name="cardX" osdev_type="1"/>
>         <object type="OSDev" name="renderXXX" osdev_type="1"/>
>         <object type="OSDev" name="controlXXX" osdev_type="1"/>

The documentation says "HWLOC_OBJ_OSDEV_GPU" is "Operating system GPU device. For instance ":0.0" for a GL display,"card0" for a Linux DRM device". It does not refer to what devices having the name "renderXXX" mean.

**Comment by bgoglin** [comment]
Hello
I don't have a good answer unfortunately. All these devices seem to depend on the driver, and maybe also on the kernel version (renderXXX didn't exist a couple years ago). I am open to adding more filtering of these files if you have a reliable documentation.
That said, when it comes to counting GPUs, it might be easier to just count individual PCI devices that contain any of these files.
The command-line tool hwloc-info could have helped if it had a way to select only gpu osdevs, I'll look at adding this.
Brice

**Comment by bgoglin** [comment]
In hwloc v2.2, you'll be able to match GPU OS devices on the command-line with `os[gpu]:all`. If you use that in `hwloc-info --ancestor pcidev os[gpu]:all`, you'll get their PCI parents. Then you just need to count how many of them (checking their PCI bus ID for duplicates). Something like this should work:
```
hwloc-info -i foo.xml --ancestor pcidev os[gpu]:all | grep "attr PCI bus id" | sort -u | wc -l
```
