### ISSUE TITLE
Broken PS1 colour after lstopo usage

### ISSUE THREAD

**Issue by clementFoyer** [open-mpi/hwloc#388]
### What version of hwloc are you using?
lstopo 2.1.0 (homebrew version: 2.1.15-9-ge985986)

### Which operating system and hardware are you running on?
macOS Catalina 10.15.3 (19D76)
`Darwin <machine-name> 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`
```
Machine (16GB total)
  Package L#0
    NUMANode L#0 (P#0 16GB)
    L3 L#0 (4096KB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#1)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
        PU L#2 (P#2)
        PU L#3 (P#3)
  CoProc(OpenCL) "opencl0d1"
```
### Details of the problem

When using `lstopo -.ascii` the foreground colour of the prompt is altered (`PS1="\[$(tput setaf 18)\]\u:\w\[$(tput sgr0)\]\$ "`).

Before the command
![Before the command](https://user-images.githubusercontent.com/8305389/76004883-209db080-5f02-11ea-991d-34a3436688fd.png)
After the command
![After the command](https://user-images.githubusercontent.com/8305389/76004927-3612da80-5f02-11ea-94d7-0f5f3f39de16.png)
After the reset (CMD+Opt+R)
![After the reset (CMD+Opt+R)](https://user-images.githubusercontent.com/8305389/76004943-3e6b1580-5f02-11ea-9abc-16ddfc615183.png)

The same behaviour is observable when using iterm2 instead of the default Terminal from macOS.

**Comment by bgoglin** [comment]
@jsquyres do you get the same issue on your mac?

**Comment by jsquyres** [comment]
No, I do not:

```
$ echo $PS1
%F{magenta}[%D{%L:%M}]%f %F{yellow}%m%f:%F{green}${_prompt_jsquyres_pwd}%f ${vcs_info_msg_0_}
%(!.%B%F{red}#%f%b.$) 
$ lstopo -.ascii
...
$ echo $PS1
%F{magenta}[%D{%L:%M}]%f %F{yellow}%m%f:%F{green}${_prompt_jsquyres_pwd}%f ${vcs_info_msg_0_}
%(!.%B%F{red}#%f%b.$) 
```

I am using zsh, however, and you can see that I have a complicated prompt -- it renders like this:

![Screen Shot 2020-03-05 at 12 44 08 PM](https://user-images.githubusercontent.com/617316/76009323-0a322d80-5edf-11ea-90a6-fe6265f26226.png)

I notice that PS1 also does not change with bash with the default prompt, though:

```
bash-5.0$ echo $PS1
\s-\v\$
bash-5.0$ lstopo -.ascii
...
bash-5.0$ echo $PS1
\s-\v\$
```

I'm also on MacOS Catalina 10.15.3:

```
$ uname -a
Darwin JSQUYRES-M-26UT 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

**Comment by sthibaul** [comment]
```tput setaf 18```

So your prompt is using the color 18.

the ascii backend of lstopo indeed changes the colors, to be able to use more colors than the standard ANSI colors. AIUI, you can not expect colors beyond number 15 to remain at their default state, ncurses for instance does not restore them at exit, see https://stackoverflow.com/questions/36051061/color-not-ended-in-curses for more details.

ATM lstopo sets colors starting from index 16, and declares 17 colors. We could make it set colors starting from max_colors instead, to mitigate the risk of conflicting with a color used by the user's prompt.

(note you can check max_colors with ```infocmp -1 | grep colors```)
