### ISSUE TITLE
better CUDA detection, with pkg-config?

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#392]
We don't use any CUDA-specific variable for detecting CUDA, we only assume headers/libs directories are in standard *_PATH variables.
It'd be good to find out if there's a **standard variable** such CUDA_HOME, CUDA_PATH, CUDA_SDK or CUDA_INSTALL_PATH that we should rely on.
Also it'd be nice to use pkg-config. Unfortunately it looks like the CUDA installer creates cuda-${version}.pc hence we don't know which one to use...

**Comment by fwyzard** [comment]
I could also be useful to add a `--with=cuda=...` option to specify explicitly the path to the CUDA runtime at configure time, *e.g.*
```
./configure ... --with-cuda=/usr/local/cuda-11.0 ...
```

**Comment by bgoglin** [comment]
Right. And we could also try to find NVML from there too. Headers seem to be in the same include subdirectory. Libs are rather in lib64/stubs for some reason.

**Comment by fwyzard** [comment]
`libnvidia-ml.so` is under `lib64/stubs/` instead of `lib64/` because it's not the full library - just a stub that provides the symbols so the linker is happy. The full library should come from the system (just like `libcuda.so`) because it needs to match the version of the kernel drivers.

**Comment by bgoglin** [comment]
So I guess we should put lib64/stubs in our lib path anyway, and we'll use either that one or the system, doesn't matter?

**Comment by fwyzard** [comment]
Yes, for building hwloc either the stub or the system library should be fine.

**Comment by fwyzard** [comment]
By the way, right now I'm using
```
./configure ... CPPFLAGS="-I/usr/local/cuda-11.0/include" LDFLAGS="-L/usr/local/cuda-11.0/lib64 -L/usr/local/cuda-11.0/lib64/stubs"
```
to build hwloc with a specific CUDA toolkit.

Is there a better alternative ?

**Comment by bgoglin** [comment]
The only alternative I am aware of is to set LIBRARY_PATH=/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.0/lib64/stubs and C_INCLUDE_PATH=/usr/local/cuda-11.0/include in the environment before running configure. That's usually what we do on our local cluster because our cuda modules export those variables.

**Comment by bgoglin** [comment]
Looks like the NVML part won't work because linking hwloc programs requires libnvidia-ml.so.1 but only libnvidia-ml.so is installed by CUDA.

**Comment by bgoglin** [comment]
@fwyzard --cuda-dir is available in PR#440, there's a tarball for easier testing at https://ci.inria.fr/hwloc/job/basic/job/PR-440/

**Comment by fwyzard** [comment]
@bgoglin thanks ! 
Using the [tarball](https://ci.inria.fr/hwloc/job/basic/job/PR-440/lastSuccessfulBuild/artifact/hwloc-PR-440-20210104.0927.gitd454edf3.tar.bz2) I can successfully build hwloc passing `--with-cuda=$CUDA_ROOT` instead of `CPPFLAGS="-I$CUDA_ROOT/include" LDFLAGS="-L$CUDA_ROOT/lib64 -L$CUDA_ROOT/lib64/stubs"` on a machine that does not have CUDA under `/usr/local`.

By the way, I also saw a couple more differences with respect to 2.4.0 (`libhwloc.so.0.0.0` vs `libhwloc.so.15.4.0` and `netloc` built by default), but I assume those are due to it being a development tarball instead of a release one ?

**Comment by bgoglin** [comment]
Thanks for testing, I'll merge this.
Yes, stable branches such as 2.4 have a library soname defined, and netloc disabled.

**Comment by SteVwonder** [comment]
> Also it'd be nice to use pkg-config. Unfortunately it looks like the CUDA installer creates cuda-${version}.pc hence we don't know which one to use...

What are your thoughts on potentially supporting a configure flag or env var that the user can set to provide the cuda version (e.g., similar to `PYTHON_VERSION`)?  If so, then not only could hwloc use pkg-config to detect all the proper flags, but the `cuda-${version}.pc` file could also be added to the `Requires` line of the hwloc.pc file.

I mention the latter bit because I'm currently bumping into issues configuring a project against a cuda-enabled hwloc that is linked against a CUDA package installed in a non-default location.  The project I'm configuring uses pkg-config to get the right flags for hwloc, but since cuda isn't in the `Requires` line for hwloc, the proper cuda flags aren't included.

**Comment by bgoglin** [comment]
I didn't know about PYTHON_VERSION but this looks like an interesting idea. Are you aware of an existing project already doing this? (in case there's anything interesting to see in their code)
I guess we'd do --with-cuda-version=X (could also be a change in --enable-cuda to support =X) and the CUDA_VERSION envvar (which would take precedence over --with-cuda-version).

**Comment by SteVwonder** [comment]
> Are you aware of an existing project already doing this? (in case there's anything interesting to see in their code)

Unfortunately, I am not.  The closest I can think of is the python m4 from autoconf archive:
```m4
	AC_ARG_VAR([PYTHON_VERSION],[The installed Python
		version to use, for example '2.3'. This string
		will be appended to the Python interpreter
		canonical name.])

	AC_PATH_PROG([PYTHON],[python[$PYTHON_VERSION]])
	if test -z "$PYTHON"; then
	   AC_MSG_ERROR([Cannot find python$PYTHON_VERSION in your system path])
	   PYTHON_VERSION=""
	fi
```
http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_python_devel.m4

I didn't test extensively, but something along these lines (in `config/hwloc.m4`) does seem to configure correctly:
```m4
    AC_ARG_VAR([CUDA_VERSION],[The installed CUDA version to use, for example '10.1'.])

    hwloc_have_cuda=no
    hwloc_have_cudart=no
    HWLOC_PKG_CHECK_MODULES([CUDA], [cuda-$CUDA_VERSION], [cuInit], [cuda.h], [hwloc_have_cuda=yes], [:])
    HWLOC_PKG_CHECK_MODULES([CUDART], [cudart-$CUDA_VERSION], [cudaGetDeviceProperties], [cuda_runtime_api.h], [hwloc_have_cudart=yes], [:])
```

**Comment by bgoglin** [comment]
@SteVwonder Can you try a tarball from https://ci.inria.fr/hwloc/view/all/job/bgoglin/373/ ? It supports --with-cuda-version and the CUDA_VERSION environment variable to select the appropriate CUDA pkg-config files.

**Comment by SteVwonder** [comment]
Works on my system 🥳 
```terminal
$ printenv PKG_CONFIG_PATH
/usr/tce/packages/cuda/cuda-10.1.168/lib64/pkgconfig
$ ./configure --prefix=$HOME/opt/packages/toss3/hwloc/2021-02-25-cudapc --with-cuda-version=10.1
<snip>
checking if cuda-10.1.pc exists... yes
checking if cudart-10.1.pc exists... yes
configure: common CUDA/OpenCL/NVML CPPFLAGS: -I/usr/tce/packages/cuda/cuda-10.1.168/include
configure: common CUDA/OpenCL/NVML LDFLAGS: -L/usr/tce/packages/cuda/cuda-10.1.168/lib64 -L/usr/tce/packages/cuda/cuda-10.1.168/lib64/stubs/
<snip>
$ make -j
<snip>
$ make install
<snip>
$ find $HOME/opt/packages/toss3/hwloc/2021-02-25-cudapc/ -name "*.pc" -exec cat {} \;
prefix=/g/g0/herbein1/opt/packages/toss3/hwloc/2021-02-25-cudapc
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: hwloc
Description: Hardware locality detection and management library
Version: cudapc-20210225.0553.gitb6f5c544
Requires.private: libxml-2.0 xext x11  cudart  pciaccess
Cflags: -I${includedir}
Libs: -L${libdir} -lhwloc
Libs.private: -lm  -ludev -lpciaccess   -lOpenCL -L/usr/tce/packages/cuda/cuda-10.1.168/lib64 -lcudart   -lnvidia-ml -lXNVCtrl -lXext -lX11 -lxml2      -lpthread
```

Thanks @bgoglin for getting this implemented!

**Comment by bgoglin** [comment]
Thanks for testing, there's a little bug in Requires.private hwloc.pc, cudart should be cudart-10.1. I'll fix this, run more tests and push this for hwloc 2.5.

**Comment by bgoglin** [comment]
I am closing this now that we have --with-cuda=<dir> and --with-cuda-version/CUDA_VERSION for pkg-config in master for hwoc v2.5. I think the original issue is solved. Thanks for your contributions.
