### ISSUE TITLE
hwloc fails to detect AMD Vega 56 GPU

### ISSUE THREAD

**Issue by MatthewOwens** [open-mpi/hwloc#393]
### What version of hwloc are you using?
`$ lstopo --version`
lstopo 2.1.0

### Which operating system and hardware are you running on?

`$ uname -a`
Linux gensokyo 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux

`$ lstopo -`
Machine (16GB total)
  Package L#0
    NUMANode L#0 (P#0 16GB)
    L3 L#0 (8192KB)
      L2 L#0 (512KB) + L1d L#0 (32KB) + L1i L#0 (64KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#1)
      L2 L#1 (512KB) + L1d L#1 (32KB) + L1i L#1 (64KB) + Core L#1
        PU L#2 (P#2)
        PU L#3 (P#3)
      L2 L#2 (512KB) + L1d L#2 (32KB) + L1i L#2 (64KB) + Core L#2
        PU L#4 (P#4)
        PU L#5 (P#5)
      L2 L#3 (512KB) + L1d L#3 (32KB) + L1i L#3 (64KB) + Core L#3
        PU L#6 (P#6)
        PU L#7 (P#7)
    L3 L#1 (8192KB)
      L2 L#4 (512KB) + L1d L#4 (32KB) + L1i L#4 (64KB) + Core L#4
        PU L#8 (P#8)
        PU L#9 (P#9)
      L2 L#5 (512KB) + L1d L#5 (32KB) + L1i L#5 (64KB) + Core L#5
        PU L#10 (P#10)
        PU L#11 (P#11)
      L2 L#6 (512KB) + L1d L#6 (32KB) + L1i L#6 (64KB) + Core L#6
        PU L#12 (P#12)
        PU L#13 (P#13)
      L2 L#7 (512KB) + L1d L#7 (32KB) + L1i L#7 (64KB) + Core L#7
        PU L#14 (P#14)
        PU L#15 (P#15)
  HostBridge
    PCIBridge
      PCI 03:00.1 (SATA)
        Block(Disk) "sdb"
        Block(Disk) "sda"
      PCIBridge
        PCIBridge
          PCI 18:00.0 (Ethernet)
            Net "enp24s0"
        PCIBridge
          PCI 1a:00.0 (Network)
            Net "wlp26s0"
    PCIBridge
      PCIBridge
        PCIBridge
          PCI 1f:00.0 (VGA)
    PCIBridge
      PCI 21:00.2 (SATA)

CPU and memory are detected correctly (as above), however I also have a Radeon RX Vega 56 that is not being detected:

`$ lspci | grep VGA`
1f:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] (rev c3)

### Details of the problem

Expected to see 'card0' in one of the PIC outputs on lstopo, and for there to be 'GPU' lines in `lstopo --only osdev`, but this does not occur.

`$ lstopo --only osdev`
Block(Disk) "sdb"
Block(Disk) "sda"
Net "enp24s0"
Net "wlp26s0"

### Additional information

Topology information attached. Seems to be a different issue from #241, as this is affecting an AMD card.

[myhost.zip](https://github.com/open-mpi/hwloc/files/4380910/myhost.zip)

**Comment by bgoglin** [comment]
Hello
Add --whole-io or --filter osdev:all, card0 will appear inside the PCI(VGA) box. It is not shown by default because showing "card0" isn't of much use in practice. Enabling OpenCL might be more useful.
Brice
