### ISSUE TITLE
dlclosing libxml2 with threads crashes

### ISSUE THREAD

**Issue by sthibaul** [open-mpi/hwloc#394]
Hello,

Here is a horror story...
[test.c.txt](https://github.com/open-mpi/hwloc/files/4384241/test.c.txt) is a reproducer for crashing. Run

```
gcc test.c -o test -g -lhwloc -lpthread
lstopo -f test.xml
./test
```

and that will crash. What happens is: 

- the main thread loads an xml topology. This `dlopen()`s the hwloc xml plugin and thus libxml2, and plays with it
- libxml2's `xmlOnceInit()` calls `pthread_key_create()`, to store per-thread xml state, and passes the  `xmlFreeGlobalState` destructor function.
- we create another thread
- the other thread loads an xml topology. That triggers a call to `xmlGetGlobalState()` which allocates the per-thread xml state
- the other thread closes its xml topology. The per-thread xml state remains allocated.
- the main thread closes its xml topology. 
- that triggers an actual `dlclose()` of the xml component and thus of libxml.
- the other thread terminates
- the thread library tries to call the per-thread key destructor `xmlFreeGlobalState()` but that's not loaded any more...
- thus a segfault...

The real problem here is that libxml2 doesn't get to call `pthread_key_delete()` to unregister its destructor function. There is the `xmlCleanupThreads()` function which is meant to get it to call `pthread_key_delete()`, but also a lot of other xml stuff, and thus it's very unsafe since it's very hard to know whether libxml2 is to be unloaded or not (think concurrent threads doing whatever else).

Perhaps we can convince libxml maintainers to set an ELF destructor that calls `xmlCleanupThreads()`?

Samuel

**Comment by sthibaul** [comment]
(i.e. 
[patch.txt](https://github.com/open-mpi/hwloc/files/4384328/patch.txt)

**Comment by bgoglin** [comment]
Could this be related to the fact that we don't call xmlCleanupParser() by default? I didn't check recently but old libxmls didn't have a reference counter. Calling xmlCleanupParser() could break things that another thread or library was still doing using libxml.
Maybe try setting HWLOC_LIBXML_CLEANUP=1 in the env to force xmlCleanupParser() (that's what we use in hwloc tests for valgrind checks).

**Comment by sthibaul** [comment]
Calling `xmlCleanupParser()` has the same problem as calling `xmlCleanupThreads()` (it actually calls it): you never know what is happening in other threads, which might be using libxml too. In my case that's the problem: mixing StarPU, OpenMPI, and Fortran, I have really no control over what uses hwloc when and when they start/terminate threads.

**Comment by bgoglin** [comment]
So, in the meantime, do you want a workaround such disabling dlclose for that component if some envvar is set or unset?

**Comment by sthibaul** [comment]
In the meantime I have applied the attached fix to libxml :)
An envvar could be a workaround for now, but it'd need to be emphasized in the xml component documentation to be actually useful: "if your application strangely crashes, try this envvar".

**Comment by bgoglin** [comment]
Actually HWLOC_PLUGINS_BLACKLIST=hwloc_xml_libxml or HWLOC_LIBXML=0 should already be enough.

**Comment by sthibaul** [comment]
I have forwarded to https://gitlab.gnome.org/GNOME/libxml2/-/issues/153

**Comment by bgoglin** [comment]
Upstream says it's fixed, and indeed I can't reproduce anymore with libxml2 2.9.14+dfsg-1.2 (while it crashes with 2.9.10+dfsg-6.7+deb11u3 and 2.9.1+dfsg1-5+deb8u4).
