### ISSUE TITLE
Add a shortcut to refresh output of graphical lstopo

### ISSUE THREAD

**Issue by philippemilink** [open-mpi/hwloc#402]
It could be nice having a shortcut (by pressing a key) to update the graphical output of lstopo, to avoid closing and launching again lstopo when bindings change.

**Comment by bgoglin** [comment]
"r" and "R" shortcuts are already used for resizing and autoresizing of the window. Do we want to use F5?

We can't easily modify existing process bindings, so I guess we'll just reload the entire topology, which won't be very smooth, but should be OK anyway.

There are multiple things that can be refreshed:
* process bindings (--ps/--top)
* specific/current process binding (--pid)
* hardware topology (cgroup changes, SMT disabled/enabled)
I'd vote for refreshing everything is it's not too slow.

**Comment by sthibaul** [comment]
Not being smooth on a user reload request looks completely fine to me.

I'm wondering whether users might at some point request for a periodical auto-reload, to be able to see e.g. dynamic binding.

**Comment by bgoglin** [comment]
A draft of lstopo refresh when hitting the F5 key is available for X11 in the tarball at https://ci.inria.fr/hwloc/view/all/job/zbgoglin-basic/327/
Windows is still under development/testing.
Periodical auto-reload will need X11 and Windows event loops to handle timeouts, we'll see that later.
