### ISSUE TITLE
Regression failure with CUDA 11.0

### ISSUE THREAD

**Issue by cponder** [open-mpi/hwloc#403]
I'm building HWLoc 2.2.0 using the PGI 20.5 compiler and CUDA 11.0.
This regression-test failed:
```
FAIL: cuda
==========
cuda: cuda.c:53: main: Assertion `osdev' failed.
Aborted
FAIL cuda (exit status: 134)
```
This didn't happen when I used CUDA 10.1 or 10.2. I don't know whether the PGI compiler level matters.

**Comment by bgoglin** [comment]
Please give more details in your bug reports, we cannot do anything here. The issue template tells you what to report, please try to at least post some of what it requests.

What does lstopo -v report? how many CUDA devices? attached to the right PCI devices? The failure is occuring in hwloc/cuda.h which fails to find a hwloc object matching the given cuda device. First thing you should do is adding printf there to see whether hwloc_cuda_get_device_pci_ids() found PCI domain/bus/dev as expected.

By the way this issue looks similar to what you reported in https://github.com/open-mpi/hwloc/issues/250 which was closed without any hwloc fix or explanation, so my current feeling is that this is yet another PGI compiler failure to proper build hwloc/cuda.h properly.

**Comment by cponder** [comment]
I skipped gathering the lstopo version & location information because it's the one that I had just built from source. Here's the output of the lstopo command:

[typescript.lstopo.txt](https://github.com/open-mpi/hwloc/files/4750959/typescript.lstopo.txt)

**Comment by cponder** [comment]
I believe the node configuration is correct, I'd built & tested this same version of HWLoc on the same nodes before, and the regression-test didn't fail. Yeah, this could be a PGI problem, but I'm thinking it's more likely some incompatibility with the new CUDA version (11.0.1). The prior bug #250 had gone away with an upgrade to the HWLoc version, do you know if it had any changes to be compatible with the CUDA 9.0?

**Comment by bgoglin** [comment]
I don't see any "cuda" object in lstopo, only nvml and opencl. Did cuda get enabled in the hwloc configuration? It should show up at the very end of the configure script summary. You may also pass HWLOC_COMPONENTS_VERBOSE=cuda in the environment to see if a cuda component gets used during hwloc discovery.

**Comment by cponder** [comment]
Here's some info from the build:
```
checking cuda.h usability... yes
checking cuda.h presence... yes
checking for cuda.h... yes
checking if CUDA_VERSION >= 3020... yes
checking for cuInit in -lcuda... yes
checking cuda_runtime_api.h usability... yes
checking cuda_runtime_api.h presence... yes
checking for cuda_runtime_api.h... yes
checking if CUDART_VERSION >= 3020... yes
checking for cudaGetDeviceProperties in -lcudart... yes
....
checking components to build statically...  noos xml synthetic xml_nolibxml linux pci opencl cuda nvml x86
....
config.status: linking hwloc/topology-cuda.c to tests/hwloc/ports/topology-cuda.c
```
and this output
```
-----------------------------------------------------------------------------
Hwloc optional build support status (more details can be found above):

Probe / display I/O devices: PCI(pciaccess+linux) LinuxIO OpenCL CUDA NVML
Graphical output:            no
XML input / output:          basic
Netloc functionality:        no
Plugin support:              no
-----------------------------------------------------------------------------
```

**Comment by bgoglin** [comment]
Can you put a printf in hwloc/topology-cuda.c after cudaGetDeviceCount() in hwloc_cuda_discover to check if it returns an errors, and if not how many devices it returns? Your test failure sounds like tests/hwloc/cuda.c finds some devices while hwloc/topology-cuda.c doesn't. The former uses cuDeviceGetCount(). There's also tests/hwloc/cudart.c which uses cudaGetDeviceCount(). You may run these tests manually to verify how many devices they find.

**Comment by cponder** [comment]
Here's the output of the lstopo with the environment variable set. Yeah, I see what you mean about OpenCL being reported.

[typescript.lstopo.2.txt](https://github.com/open-mpi/hwloc/files/4751152/typescript.lstopo.2.txt)

Running an earlier build of the same HWLoc with CUDA 10.2 & PGI 20.4, I do see the CUDA references:
```
Co-Processor(CUDA) L#5 (Backend=CUDA GPUVendor="NVIDIA Corporation" GPUModel="Tesla V100-SXM2-16GB" CUDAGlobalMemorySize=16548352 CUDAL2CacheSize=6144 CUDAMultiProcessors=80 CUDACoresPerMP=64 CUDASharedMemorySizePerMP=48) "cuda0"
```
but not in this newer build.

**Comment by cponder** [comment]
I used this form
```
     75   cures = cudaGetDeviceCount(&nb);
     76   fprintf(stderr, "cudaGetDeviceCount count=%d returnval=%d\n", (int) nb, (int) cures); fflush(stderr);
     77   if (cures)
     78     return -1;

```
which gave me
```
cudaGetDeviceCount count=23 returnval=35
```
The nodes have 8 GPUs on them, so this doesn't look right.
That being said, I'm going to push for an upgrade to the drivers on the nodes, and see if it works any different. Do you mind holding this issue open until then?
I'll be able to run the `lstopo -v` command to see if the CUDA devices are being reported or not, which doesn't require any rebuilds.

**Comment by sthibaul** [comment]
Carl Ponder, le mar. 09 juin 2020 03:18:17 -0700, a ecrit:
> cudaGetDeviceCount count=23 returnval=35

    /**
     * This indicates that the installed NVIDIA CUDA driver is older than the
     * CUDA runtime library. This is not a supported configuration. Users should
     * install an updated NVIDIA display driver to allow the application to run.
     */
    cudaErrorInsufficientDriver           =     35,

It looks like you need a system reboot with the updated driver.

Samuel

**Comment by cponder** [comment]
The CUDA driver is supposed to be "forward compatible", but I had to move some library paths around to make it work. The "cuda" test works now. I'm going to close this issue.
I'd be inclined to print an error if the `cudaGetDeviceCount` returns a non-zero exit code, these functions
```
cudaGetErrorString(result)
cudaGetErrorName(result)
```
can be used to print the message and name.

**Comment by bgoglin** [comment]
Yes, I'll do that in some other backends too, thanks.
