### ISSUE TITLE
Windows ReleaseStatic linker settings

### ISSUE THREAD

**Issue by fj40bryan** [open-mpi/hwloc#408]
### What version of hwloc are you using?
* latest master (as well as 2.0)

### Which operating system and hardware are you running on?

* Windows 10

### Details of the problem

In master & Windows I am attempting to build statically. For the Visual Studio libhwloc project, there is a ReleaseStatic configuration. It currently sets `RuntimeLibrary` to `MultiThreadedDLL`. I might be miss-understanding this setting (mostly linux developer here) but shouldn't it be set to `MultiThreaded` for release static?

https://github.com/open-mpi/hwloc/blob/master/contrib/windows/libhwloc.vcxproj
line 175: 
```xml
<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>
```

Note: if this is an issue, then it may be present for other vs projects. I am only using libhwloc...

Thank you!

**Comment by bgoglin** [comment]
Hello. The MSVC solution was contributed by an external developer a couple years ago, I asked him to comment but it may take some time. Did you actually see a better/different behavior when changing to MultiThreaded?

**Comment by fj40bryan** [comment]
To be honest I think it’s wrong but I’m not sure.

I attempted to test it myself but cannot figure out how to patch in the change yet due to the complicated build system we use. I’ll try to test it and get back to you.

Sent from my iPhone

On Jul 21, 2020, at 11:09 PM, Brice Goglin <notifications@github.com> wrote:

﻿

Hello. The MSVC solution was contributed by an external developer a couple years ago, I asked him to comment but it may take some time. Did you actually see a better/different behavior when changing to MultiThreaded?

**Comment by bgoglin** [comment]
@egaudry is going to look at this.

**Comment by egaudry** [comment]
@fj40bryan you're right, the "Static" configuration is all messed-up, mainly because we never used it in the first place.

I was about to suggest to remove it as no one was using it ; can you let me know why you intended to build a static version of the lib ?

**Comment by fj40bryan** [comment]
We have a static and dynamic build of our source and in the static build, hwloc on windows is currently the only exception to the rule (it’s still dynamic). In general static is nice because it’s less files and simpler to copy around without messing something up.

Thanks,
Bryan

On Aug 17, 2020, at 4:20 AM, egaudry <notifications@github.com> wrote:

﻿

@fj40bryan<https://github.com/fj40bryan> you're right, the "Static" configuration is all messed-up, mainly because we never used it in the first place.

I was about to suggest to remove it as no one was using it ; can you let me know why you intended to build a static version of the lib ?

**Comment by egaudry** [comment]
@fj40bryan 
I do get your point.
Can you test it from your side (by applying the modification you suggested)?

**Comment by fj40bryan** [comment]
Sure I have been meaning to do this for a while but have been very busy. I’ll try to get on it as fast as I can. I think I can get it done this week,

Bryan

Sent from my iPhone

On Aug 17, 2020, at 8:40 AM, egaudry <notifications@github.com> wrote:

﻿

@fj40bryan<https://github.com/fj40bryan>
I do get your point.
Can you test it from your side (by applying the modification you suggested)?

**Comment by fj40bryan** [comment]
Hi,

I could not figure out how to submit a pull request (lack permissions) so I forked the repo to here https://github.com/open-mpi/hwloc/compare/master...fj40bryan:master and made this change

![image](https://user-images.githubusercontent.com/408550/90701008-22eb9100-e23c-11ea-8a36-4d1bf2d47b54.png)

My project built after some fixes on my end and runs without the usual hwloc dll present, so I think its working!

There may be other issues with the project file, but as I said earlier, I am not a vsproj expert.

Can you include these fixes, or would you like to grant me permission for the pull-request? Either way is fine with me.

Bryan

**Comment by bgoglin** [comment]
@egaudry Does the above patch look OK?

@fj40bryan You actually *must* fork the repo for submit a pull request. That way you don't need write access to the official hwloc repo. You push your branch to your own fork, and then open a PR from your fork/branch to the official report, then we review and merge. So now if you go to https://github.com/open-mpi/hwloc/compare/master...fj40bryan:master you should see a "create pull request" button on the right.

**Comment by egaudry** [comment]
Yes, it is.

**Comment by bgoglin** [comment]
@fj40bryan Can you add a Signed-off-by line in your commit message(s) with your email address? See the end of https://github.com/open-mpi/ompi/wiki/Administrative-rules for details.
You may modify your commit, force push the branch to your fork, and create the PR (and the PR will be auto-updated if your push after creating the PR).

**Comment by fj40bryan** [comment]
Thanks for the information, very helpful. I *hopefully* made the changes you requested and opened a pull request here: https://github.com/open-mpi/hwloc/pull/420
Thank you, Bryan

**Comment by bgoglin** [comment]
Fixed in #420
