### ISSUE TITLE
How to prevent hwloc from linking to libXNVCtrl.so?

### ISSUE THREAD

**Issue by lyu** [open-mpi/hwloc#416]
### What version of hwloc are you using?

2.2.0, installed from the release tarball, configured with `--without-x`

### Which operating system and hardware are you running on?

CentOS Linux release 7.8.2003 x86_64

### Details of the problem

The hwloc package was compiled and installed on the login node, but when I try to compile programs that link to hwloc on the compute nodes, I see errors like:

```
/gpfs/home/$USER/.local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: libXNVCtrl.so.0, needed by /gpfs/home/$USER/opt/lib/libpmix.so, not found (try using -rpath or -rpath-link)
/gpfs/home/$USER/.local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /gpfs/home/$USER/.local/lib/libhwloc.so.15: undefined reference to `XNVCTRLQueryTargetAttribute'
/gpfs/home/$USER/.local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /gpfs/home/$USER/.local/lib/libhwloc.so.15: undefined reference to `XNVCTRLQueryTargetStringAttribute'
/gpfs/home/$USER/.local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /gpfs/home/$USER/.local/lib/libhwloc.so.15: undefined reference to `XNVCTRLQueryTargetBinaryData'
/gpfs/home/$USER/.local/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /gpfs/home/$USER/.local/lib/libhwloc.so.15: undefined reference to `XNVCTRLIsNvScreen'
```

It seems that the filesystems of our compute nodes and the login node are slightly different. What configuration flags should I use so that `libhwloc.so` doesn't link to `libXNVCtrl.so`? Or preferably, all the X-related libs?

I've tried `--without-x`, `--disable-cuda` and `--disable-nvml`, no luck.

### Additional information

Output of `ldd libhwloc.so`:

```
	linux-vdso.so.1 =>  (0x00002aaaaaacd000)
	libm.so.6 => /lib64/libm.so.6 (0x00002aaaaaccf000)
	libXNVCtrl.so.0 => /lib64/libXNVCtrl.so.0 (0x00002aaaaafd1000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00002aaaab1d6000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00002aaaab3e8000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aaaab726000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00002aaaabaf4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaabd1c000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00002aaaabf20000)
```

**Comment by sthibaul** [comment]
XNVCtrl is used in the gl plugin, so `--disable-gl` should work.
That being said, it is surprising, don't you have plugins enabled? That would avoid libhwloc.so being itself linked to such libraries.

**Comment by lyu** [comment]
Thanks for the quick response! It works now.

I configured hwloc with `./configure --prefix=$HOME/.local --without-x`, didn't touch anything related to plugins, so I don't know. Maybe this is a PMIx issue, in which I did disable `dlopen` for PMIx.

The environment on our cluster is a mess to begin with, so this should not be a big concern for you. Closing the issue. Thank you for the help.

**Comment by sthibaul** [comment]
Possibly it didn't find dlopen on the system, and thus disabled the support for plugins.
