### ISSUE TITLE
Intel(R) Inspector reports "uninitialized memory access" issue inside the hwloc_topology_load() function

### ISSUE THREAD

**Issue by ivankochin** [open-mpi/hwloc#421]
### Details of the problem

After the analysis of the simple code example from [the official tutorial page](https://www.open-mpi.org/projects/hwloc/tutorials/20120702-POA-hwloc-tutorial.html) the [Intel(R) Inspector](https://software.intel.com/content/www/us/en/develop/tools/inspector.html) analyzer reports "Uninitialized memory access" inside the `hwloc_topology_load()` function.

### Additional information
Intel(R) Inspector version: 2020.2

Code snippet:
```c++
#include <hwloc.h>
#include <stdio.h>

int main(void) {
  hwloc_topology_t topology{nullptr};
  int nbcores{0};
  
  hwloc_topology_init(&topology);  // initialization
  hwloc_topology_load(topology);   // actual detection
  
  nbcores = hwloc_get_nbobjs_by_type(topology, HWLOC_OBJ_CORE);
  printf("%d cores\n", nbcores);

  hwloc_topology_destroy(topology);

  return 0;
}
```
How to reproduce:
```bash
g++ example.cpp -g -lhwloc -o example.exe

. <path_to>/inspxe-vars.sh
inspxe-cl -collect=mi3 example.exe
inspxe-cl -report=problems
```

Reproducer output:
```
P1: Error: Invalid memory access: New
 P1.2: Error: Invalid memory access: New
  libc.so.6!0x8697a: Error X2: Read: Function __libc_malloc: Module /lib64/libc.so.6

P2: Error: Uninitialized memory access: New
 P2.3: Error: Uninitialized memory access: New
  <path_to>/hwloc_example/hwloc_api_example.cpp(9): Error X3: Read: Function main: Module <path_to>/hwloc_example/example.exe
  <path_to>/hwloc_example/hwloc_api_example.cpp(9): Error X4: Allocation site: Function main: Module <path_to>/hwloc_example/a.out
```

**Comment by bgoglin** [comment]
Please try a more recent hwloc, 1.11.2 is 5 years old, we fixed tens of issues like this.
Also can you get a more useful output? Valgrind reports uninitialized reads with a backtrace and line numbers.

**Comment by ivankochin** [comment]
I tried to reproduce the issue on hwloc-2.0.4 and there are no problems.

Thank you for your time!
