### ISSUE TITLE
[Regression: 2.0->2.2.0] Fails to build on Windows Visual Studio

### ISSUE THREAD

**Issue by inducer** [open-mpi/hwloc#423]
### What version of hwloc are you using?

2.2.0, see https://github.com/conda-forge/libhwloc-feedstock/pull/28.

### Which operating system and hardware are you running on?

Windows, as available via the `vs2017-win2016` image on Azure.

https://github.com/conda-forge/libhwloc-feedstock/blob/a656c04e16595d4ca884b28d1266e8511cfdcba5/.azure-pipelines/azure-pipelines-win.yml#L8

### Details of the problem

[`hwloc_get_last_cpu_location.c`](https://github.com/open-mpi/hwloc/blob/5de58da6003b4c391e3cbb93a7b6fced340f15b9/tests/hwloc/hwloc_get_last_cpu_location.c) includes `unistd.h`, which is unavailable on Windows, leading to this build failure:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=213927&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f

**Comment by bgoglin** [comment]
Hello.
I guess we just need to add #ifdef HAVE_UNISTD_H like we do in hwloc_backends.c?
Please note that we don't support building these tests with MSVC . We only build the lib+tools with the MSVC solution. Tests are only built on windows in our CI when using cygwin and mingw. Hence things like this might break again in the future.
Brice

**Comment by bgoglin** [comment]
By the way, I am going to release 2.3 early next week. So please test that #ifdef before that if you want the fix to be included (or even test 2.3rc1 with that patch). There won't likely ever be any 2.2.1 release.

**Comment by bgoglin** [comment]
I checked on my MSVC machine, unistd.h seems to be the only missing #include that we use on Windows-enabled tests. Hopefully 2.3 will work fine with this (backported to 2.2 too but it likely won't ever be released).

**Comment by inducer** [comment]
Thanks! Looks like that worked: https://github.com/conda-forge/libhwloc-feedstock/pull/29
