### ISSUE TITLE
hwloc_bitmap_nr_ulongs() reports wrong result

### ISSUE THREAD

**Issue by neicker** [open-mpi/hwloc#429]
In libhwloc 2.1.0 (coming with openSUSE Leap 15.2, but this also holds for the current HEAD the master branch) result of `hwloc_bitmap_nr_ulongs()` is off by one if a bitmap's last bit is a multiple of 64.

### Details of the problem

As far as I understand `hwloc_bitmap_nr_ulongs()` shall return the number of `unsigned long`s required to store the whole bitmap. Thus:
>  unsigned int nr = hwloc_bitmap_nr_ulongs(s1);
>  unsigned long *store = malloc(nr * sizeof(*store));`
>  hwloc_bitmap_to_ulongs(s1, nr, store);
>
>  hwloc_bitmap_t s2 = hwloc_bitmap_alloc();
>  hwloc_bitmap_from_ulongs(s2, nr, store);

shall make `s2` an identical copy of `s1`.

But this does not hold if s1's last bit is a multiple of 64 (at least on 64-bit platforms).

IMHO `hwloc_bitmap_nr_ulongs()` shall return:
`	return (last + HWLOC_BITS_PER_LONG)/HWLOC_BITS_PER_LONG;`
instead of
`	return (last + HWLOC_BITS_PER_LONG-1)/HWLOC_BITS_PER_LONG;`
as in the current HEAD.

**Comment by bgoglin** [comment]
Hello. Testing with a bitmap that only contains bit 0 confirms the issue. We should return 1 instead of 0 in that case. I am fixing this and adding regression tests for this case. Thanks a lot
