### ISSUE TITLE
throughput distance matrix

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#44]
Add a throughput matrix on the side of the existing latency one (basically the same behavior except that the grouping code looks at maximum instead of mininum values). set_distance() doesn't have a latency/throughput parameter. So we will look at the matrix to find out if it's throughput (diagonal is maximum) or latency (all other cases)

If we rework the distance API because of tickets #48, #67 and #68, it might be good to add a parameter specifying if the given matrice is latency/throughput/number-of-hops/...

**Comment by bgoglin** [comment]
Both latency and bandwidth (and other) are supported since the 2.0 new distance API in commit 9e97e8a1e96a034b61027c122560320f7bad2785.
