### ISSUE TITLE
Incorrect core types detection in 32-bit mode on virtual machines with Windows Server OS.

### ISSUE THREAD

**Issue by ivankochin** [open-mpi/hwloc#444]
### What version of hwloc are you using?

HWLOC 2.4

### Which operating system and hardware are you running on?

OS: Windows Server 2019
Processor: Intel(R) Xeon(R) Gold 6252

The issue is reproduced only on virtual machines that may use only part of the host PUs.
For example:
![image](https://user-images.githubusercontent.com/22097249/104591214-6af0d180-567d-11eb-987c-2f8b0daa67fb.png)
The Intel(R) Xeon(R) Gold 6252 has 48 threads, but this virtual machine can use only 8 threads.

### Details of the problem

The `hwloc_cpukinds_get_nr()` and `hwloc_cpukinds_get_info()` interfaces reports several core types on machine with homogeneous processor.

#### Reproducer
```c++
#include <hwloc.h>

int main() {
    hwloc_topology_t topology;
    hwloc_topology_init(&topology);
    hwloc_topology_load(topology);

    unsigned i, j, nr;
    hwloc_bitmap_t cpuset = hwloc_bitmap_alloc();

    nr = hwloc_cpukinds_get_nr(topology, 0);
    printf("Number is %d \n", nr);
    for(i=0; i<nr; i++) {
      int efficiency;
      struct hwloc_info_s *infos;
      unsigned nr_infos;
      int err;

      err = hwloc_cpukinds_get_info(topology, i, cpuset, &efficiency, &nr_infos, &infos, 0);
      if (!err) {
        char* cpusetstr = new char[256];
        hwloc_bitmap_snprintf(cpusetstr, 256, cpuset);
        printf("CPU kind #%u efficiency %d cpuset %s\n", i, efficiency, cpusetstr);
        delete cpusetstr;
        for(j=0; j<nr_infos; j++)
          printf("  %s = %s\n", infos[j].name, infos[j].value);
      }
    }

    hwloc_bitmap_t process_cpu_affinity_mask  = hwloc_bitmap_alloc();
    hwloc_get_cpubind(topology, process_cpu_affinity_mask, 0);
    char* cpusetstr = new char[256];
    hwloc_bitmap_snprintf(cpusetstr, 256, process_cpu_affinity_mask);
    printf("Current cpubind %s\n", cpusetstr);
    delete cpusetstr;
    hwloc_bitmap_free(process_cpu_affinity_mask);

    // DetectWin10();
    hwloc_bitmap_free(cpuset);
    return 0;
}
```
#### Output
```
Number is 4
CPU kind #0 efficiency 0 cpuset 0x000000c0
CPU kind #1 efficiency 1 cpuset 0x0000000c
CPU kind #2 efficiency 2 cpuset 0x00000003
CPU kind #3 efficiency 3 cpuset 0x00000030
Current cpubind 0x000000ff
```
#### Compilation environment
- Compiler: Visual Studio 2019
- Arch: ia32
- Hwloc 2.4.0

**Comment by bgoglin** [comment]
Hello Ivan, could you post the output of "lstopo -v" or "lstopo -.xml" so that we know the difference between these cpu kinds? You specified 32bits, does this mean that 64bits works fine?

**Comment by ivankochin** [comment]
Hi Brice! Thanks for the quick response!

Yes, 64bits works as expected.

It is strange, but `lstopo -v` returns the correct output:
```
Machine (P#0 total=12333504KB Backend=Windows OSName=Windows WindowsBuildEnvironment=MinGW OSRelease=10 OSVersion=10.0.14393 Hostname=nntpat129-13 Architecture=i686 hwlocVersion=2.4.0 ProcessName=lstopo.exe)
  Package L#0 (total=12333504KB CPUVendor=GenuineIntel CPUFamilyNumber=6 CPUModelNumber=85 CPUModel="Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz" CPUStepping=7)
    NUMANode L#0 (P#0 local=12333504KB total=12333504KB)
    L3Cache L#0 (size=36608KB linesize=64 ways=11 Inclusive=0)
      L2Cache L#0 (size=1024KB linesize=64 ways=16 Inclusive=0)
        L1dCache L#0 (size=32KB linesize=64 ways=8 Inclusive=0)
          L1iCache L#0 (size=32KB linesize=64 ways=8 Inclusive=0)
            Core L#0
              PU L#0 (P#0)
              PU L#1 (P#1)
      L2Cache L#1 (size=1024KB linesize=64 ways=16 Inclusive=0)
        L1dCache L#1 (size=32KB linesize=64 ways=8 Inclusive=0)
          L1iCache L#1 (size=32KB linesize=64 ways=8 Inclusive=0)
            Core L#1
              PU L#2 (P#2)
              PU L#3 (P#3)
      L2Cache L#2 (size=1024KB linesize=64 ways=16 Inclusive=0)
        L1dCache L#2 (size=32KB linesize=64 ways=8 Inclusive=0)
          L1iCache L#2 (size=32KB linesize=64 ways=8 Inclusive=0)
            Core L#2
              PU L#4 (P#4)
              PU L#5 (P#5)
      L2Cache L#3 (size=1024KB linesize=64 ways=16 Inclusive=0)
        L1dCache L#3 (size=32KB linesize=64 ways=8 Inclusive=0)
          L1iCache L#3 (size=32KB linesize=64 ways=8 Inclusive=0)
            Core L#3
              PU L#6 (P#6)
              PU L#7 (P#7)
depth 0:           1 Machine (type #0)
 depth 1:          1 Package (type #1)
  depth 2:         1 L3Cache (type #6)
   depth 3:        4 L2Cache (type #5)
    depth 4:       4 L1dCache (type #4)
     depth 5:      4 L1iCache (type #9)
      depth 6:     4 Core (type #2)
       depth 7:    8 PU (type #3)
Special depth -3:  1 NUMANode (type #13)
CPU kind #0 efficiency 0 cpuset 0x000000ff
```

**Comment by bgoglin** [comment]
Can you place a hwloc_topology_export_xml(topology, "C:\Users\blabla\file.xml", 0); after topology_load() and send the generated xml file?

**Comment by ivankochin** [comment]
Yes, no problem.

GitHub restricts the XML attachments so I changed the file extension to `.txt`.

[hwloc_topology.txt](https://github.com/open-mpi/hwloc/files/5816243/hwloc_topology.txt)

**Comment by bgoglin** [comment]
I have no idea where these efficiency values come from. Can you try to build a program like this and tell us what it shows on that 32bit machines? You might need to tweak it, I couldn't test it properly yet.
```
#define _WIN32_WINNT 0x0601
#include <windows.h>
#include <stdio.h>

int main(void)
{
  PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX procInfoTotal, tmpprocInfoTotal, procInfo;
  DWORD length = 0;

  procInfoTotal = NULL;
  while (1) {
    if (GetLogicalProcessorInformationEx(RelationAll, procInfoTotal, &length))
      break;
    if (GetLastError() != ERROR_INSUFFICIENT_BUFFER)
      return -1;
    tmpprocInfoTotal = realloc(procInfoTotal, length);
    if (!tmpprocInfoTotal) {
      free(procInfoTotal);
      return -1;
    }
    procInfoTotal = tmpprocInfoTotal;
  }

  for (procInfo = procInfoTotal;
       (void*) procInfo < (void*) ((uintptr_t) procInfoTotal + length);
       procInfo = (void*) ((uintptr_t) procInfo + procInfo->Size)) {
    if (procInfo->Relationship == RelationProcessorCore) {
      printf("efficiency class %d\n", (int) procInfo->Processor.EfficiencyClass);
    }
  }

  return 0;
}
```

**Comment by ivankochin** [comment]
> Can you try to build a program like this and tell us what it shows on that 32bit machines?
I have no machines with 32bit architecture. I just run 32bit applications on a 64bit Windows Server machine.

To compile this code I needed to cast the `void*` to `PSYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX` in several cases.
But I think that these changes shouldn't break the logic.

This example shows the following output in both 32 and 64 bits modes:
```
efficiency class 0
efficiency class 0
efficiency class 0
efficiency class 0
```

**Comment by bgoglin** [comment]
OK. No problem there.
Assuming you're using the prebuilt hwloc ZIP, I am going to add some debug printf in the code to understand where these crazy efficiency values come from.

**Comment by bgoglin** [comment]
Can you try the ZIPs from https://ci.inria.fr/hwloc/view/all/job/bgoglin/355/ and report the printfs that appear in the text console?

**Comment by bgoglin** [comment]
Even take from https://ci.inria.fr/hwloc/view/all/job/bgoglin/356/ which contains more debug printf.

**Comment by ivankochin** [comment]
Here are two attached files with the debug output generated by [the provided below packages:](https://github.com/open-mpi/hwloc/issues/444#issuecomment-760965354):

- [32bit log](https://github.com/open-mpi/hwloc/files/5829272/hwloc_cpukinds_debug_output_intel64.txt)
- [64bit log](https://github.com/open-mpi/hwloc/files/5829273/hwloc_cpukinds_debug_output_ia32.txt)

**Comment by bgoglin** [comment]
Thanks it looks like Windows is really returning crazy EfficiencyClass from the PROCESSOR_RELATIONSHIP. I don't see anything about 32bit/64bit in https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-processor_relationship
What virtualization technology are you using? I seem to remember reading WoW64 add some strange behavior with respect to locality information. Can you ask some Windows developers if they know more about this?

In the meantime, I could detect crazy values and ignore efficiency class entirely when we don't get 0/1.

**Comment by bgoglin** [comment]
In the meantime, I implemented a workaround that ignores windows efficiencyclass > 3 by default (threshold configurable through environment variable). Zips available at https://ci.inria.fr/hwloc/view/all/job/bgoglin/359/
Can you test this on this 32bit machine, and on a real hybrid machine? If it works, I'll put this in 2.4.1 until the underlying issue is clarified.

**Comment by bgoglin** [comment]
Actually we need to focus on why lstopo and your program have different behaviors. Can you run lstopo from https://ci.inria.fr/hwloc/view/all/job/bgoglin/356/ on 32bits and post the debug messages? I assume it will report correct values but I want to check if anything interesting appears in the log.

**Comment by ivankochin** [comment]
Sorry, but I have no access to the machine at this moment. So I would check proposed options later.

**Comment by ivankochin** [comment]
> In the meantime, I implemented a workaround that ignores windows efficiencyclass > 3 by default (threshold configurable through environment variable). Zips available at https://ci.inria.fr/hwloc/view/all/job/bgoglin/359/
Can you test this on this 32bit machine, and on a real hybrid machine? If it works, I'll put this in 2.4.1 until the underlying issue is clarified.

Does the library report only one core type on machines with more than two core types in this case? Or it just ignores the core types with efficiency > 3?

**Comment by bgoglin** [comment]
Either it exposes all core types, or none. EfficiencyClass > 3 is considered as "something is going wrong, ignore everything".

**Comment by ivankochin** [comment]
> Actually we need to focus on why lstopo and your program have different behaviors. Can you run lstopo from https://ci.inria.fr/hwloc/view/all/job/bgoglin/356/ on 32bits and post the debug messages? I assume it will report correct values but I want to check if anything interesting appears in the log.

Here is the console output for customized `lstopo` execution:
```
got osvi from RtlGetVersion
enabling efficiencyclass
got efficiencyclass 0 efficiencyclass from RelationProcessorCore
Efficiency_Class = 00fab3d5(0), ptr flags+1 = 00fab3d5(0)
adding efficiency_class 0 for cpuset 0x00000003
extended class array to 4 slots
adding new class #0
now class #0 cpuset 0x00000003 with value 0
got efficiencyclass 0 efficiencyclass from RelationProcessorCore
Efficiency_Class = 00fab4d1(0), ptr flags+1 = 00fab4d1(0)
adding efficiency_class 0 for cpuset 0x0000000c
adding to class 0
got efficiencyclass 0 efficiencyclass from RelationProcessorCore
Efficiency_Class = 00fab599(0), ptr flags+1 = 00fab599(0)
adding efficiency_class 0 for cpuset 0x00000030
adding to class 0
got efficiencyclass 0 efficiencyclass from RelationProcessorCore
Efficiency_Class = 00fab661(0), ptr flags+1 = 00fab661(0)
adding efficiency_class 0 for cpuset 0x000000c0
adding to class 0
registering cpukind from class #0 cpuset 0x000000ff with value 0
```
If I understand correctly it looks valid.

I think that the reason for the unexpected behavior is Visual Studio or Windows System Runtimes configuration. I do such a conclusion based on the following facts:
- To reproduce the issue we need to source Visual Studio in x86 mode (run "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" x86 before executing the binary). This issue does not reproduce if we just open cmd and execute the binary without any additional environment settings. 
- On one of the machines, this issue was fixed by updating the Visual Studio.

I tried to display the list of loaded DLLs for both correct and incorrect cases, but the list of DLLs obtained via `listddls` utility are the same:
```
Base                Size      Path
0x0000000000bc0000  0x96000   C:\temp\kivan\hwloc-cpukinds-example.exe
0x00000000451e0000  0x1ed000  C:\Windows\SYSTEM32\ntdll.dll
0x0000000044160000  0x53000   C:\Windows\System32\wow64.dll
0x00000000447d0000  0x7c000   C:\Windows\System32\wow64win.dll
0x0000000077c00000  0x9000    C:\Windows\System32\wow64cpu.dll
0x0000000000bc0000  0x96000   C:\temp\kivan\hwloc-cpukinds-example.exe
0x0000000077c10000  0x19c000  C:\Windows\SysWOW64\ntdll.dll
0x00000000755c0000  0xe0000   C:\Windows\SysWOW64\KERNEL32.DLL
0x00000000773e0000  0x1f9000  C:\Windows\SysWOW64\KERNELBASE.dll
0x000000006ee40000  0x183000  C:\temp\kivan\libhwloc-15.dll
0x00000000762d0000  0xc0000   C:\Windows\SysWOW64\msvcrt.dll
```

I think that we need to reproduce this issue using only WinAPI interfaces and report this issue to Microsoft. But I don't know how to do it. The only possible way in my mind is to compile the HWLOC Windows binaries from sources on my machine in debug mode and use Visual Studio to find what call returns the incorrect value.

**Comment by bgoglin** [comment]
Thanks, this goes beyond my knowledge of windows unfortunately. Did you check whether my test from https://github.com/open-mpi/hwloc/issues/444#issuecomment-760505659 changes if you source VS in X86 mode first?

**Comment by ivankochin** [comment]
Yes, I got it right now!
This sample returns very strangely values:

```
C:\temp\kivan>windows-cpukinds-example.exe
efficiency class 59
efficiency class 69
efficiency class 101
efficiency class 0

C:\temp\kivan>windows-cpukinds-example.exe
efficiency class 105
efficiency class 80
efficiency class 111
efficiency class 67

C:\temp\kivan>windows-cpukinds-example.exe
efficiency class 117
efficiency class 114
efficiency class 41
efficiency class 77
```

**Comment by bgoglin** [comment]
Oh, the values are not even reproducible? I wonder if Microsoft forgot to initialize some field somewhere :)
Do you think you have enough for a bug report to Microsoft now?

**Comment by ivankochin** [comment]
It is strange, but they were different when I ran it 3 first time, but now it looks reproducible:
```
C:\temp\kivan>windows-cpukinds-example.exe
efficiency class: 0
group affinity: 3
efficiency class: 97
group affinity: c
efficiency class: 92
group affinity: 30
efficiency class: 97
group affinity: c0

C:\temp\kivan>windows-cpukinds-example.exe
efficiency class: 0
group affinity: 3
efficiency class: 97
group affinity: c
efficiency class: 92
group affinity: 30
efficiency class: 97
group affinity: c0

C:\temp\kivan>windows-cpukinds-example.exe
efficiency class: 0
group affinity: 3
efficiency class: 97
group affinity: c
efficiency class: 92
group affinity: 30
efficiency class: 97
group affinity: c0
```
As you can see I updated the https://github.com/open-mpi/hwloc/issues/444#issuecomment-760505659 sample by printing the group affinity.

I think that now we have enough information to send a bug report to Microsoft. I will do it at the nearest time. Thanks for the help!

**Comment by ivankochin** [comment]
Here is [the link](https://developercommunity2.visualstudio.com/t/The-GetLogicalProcessorInformationEx-ret/1330376
) to the issue on the Developer Community Forum.

**Comment by bgoglin** [comment]
@ivankochin Did you get any useful answer from your report linked above besides "it's a windows API bug, please report there"?

**Comment by ivankochin** [comment]
@bgoglin no I didn't. I tried to ping for feedback several times [there](https://aka.ms/AAb2sn9), but there is no response. I don't know any other channels to report this problem, so I am stuck here.

**Comment by bgoglin** [comment]
I was told this was a bug in early 32bit versions supporting core types. Hopefully it works now. If not, please reopen.
