### ISSUE TITLE
hwloc 2.4.0: cudaGetDeviceCount overly verbose error

### ISSUE THREAD

**Issue by abouteiller** [open-mpi/hwloc#453]
### What version of hwloc are you using?

hwloc-2.0.4, within mpiexec-4.0.5, built from Spack recipe (spack install openmpi@4.0.5 ~cuda schedulers=slurm)

### Which operating system and hardware are you running on?

CentOS 7, x86_64, Nvidia SDK installed, no Nvidia device (on this machine, devices are available on other systems of this cluster running the same image). 

### Details of the problem

```
 mpiexec hostname
CUDA: Failed to get number of devices with cudaGetDeviceCount(): no CUDA-capable device is detected
hostname.domain.com
```
It took me a while to dig where that message comes from, but it's from `hwloc/cuda-topologies.c:79`. Note that the message can be silenced by setting the env HWLOC_HIDE_ERRORS.

### Recommended changes

1. It can be argued that the reported message is not about an error, but simply the **normal outcome of hwloc detecting the hardware.** So course of action 1 is to remove the message except if some verbosity flag is set (e.g., in `lstopo -v`, or a new flag HWLOC_CUDA_VERBOSE?).
2. If (given past experience with user support?) this message is seen as useful by default, it should clearly contain that it emanates from HWLOC. As it stand, the message misdirect users into thinking that the host program produced this error message itself, this can be especially confusing when said host program also has some sort of CUDA support of its own.

**Comment by bgoglin** [comment]
Hello Aurelien, the actual recommended change is for NVIDIA to return 0 instead of an error here :) This message was suggested by @cponder from NVIDIA in #403, maybe he has an opinion. I'll look in the error code list to see if I can avoid the message in this specific case.

**Comment by bgoglin** [comment]
Totally untested patch:
```
--- a/hwloc/topology-cuda.c
+++ b/hwloc/topology-cuda.c
@@ -75,9 +75,9 @@ hwloc_cuda_discover(struct hwloc_backend *backend, struct hwloc_disc_status *dst
 
   cures = cudaGetDeviceCount(&nb);
   if (cures) {
-    if (!hwloc_hide_errors()) {
+    if (cures != cudaErrorNoDevice && !hwloc_hide_errors()) {
       const char *error = cudaGetErrorString(cures);
-      fprintf(stderr, "CUDA: Failed to get number of devices with cudaGetDeviceCount(): %s\n", error);
+      fprintf(stderr, "hwloc/cuda: Failed to get number of devices with cudaGetDeviceCount(): %s\n", error);
     }
     return -1;
   }
```

**Comment by bgoglin** [comment]
I managed to test here by unbinding existing GPUs from the driver, the patch makes the error message go away. But nvmlInit() shows another message that cannot easily be filtered-out by checking the return value (999 =  unknown error).

I am looking at disabling these warning by default and reenabling them in lstopo (even without -v).

**Comment by bgoglin** [comment]
I pushed some commits to prefix error messages with "hwloc" and also to disable some non-critical ones by default (except in lstopo). We should be good now, I am closing this.
