### ISSUE TITLE
PCI: Failed to initialize libpciaccess with pci_system_init(): 6 (Permission denied)

### ISSUE THREAD

**Issue by thierry-FreeBSD** [open-mpi/hwloc#456]
### Details of the problem
When running `lstopo -` as a regular user, this error is displayed:
`PCI: Failed to initialize libpciaccess with pci_system_init(): 6 (Permission denied)`
This same error is displayed when launching mpirun.
When running as root, no problem.
The full output is:

```
PCI: Failed to initialize libpciaccess with pci_system_init(): 6 (Permission denied)
Machine (15GB total) + Package L#0
  NUMANode L#0 (P#0 15GB)
  L3 L#0 (6144KB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
```
or e.g. on another machine:
```
PCI: Failed to initialize libpciaccess with pci_system_init(): 6 (Permission denied)
Machine (15GB total) + Package L#0
  NUMANode L#0 (P#0 15GB)
  L3 L#0 (8192KB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#1)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#2)
      PU L#3 (P#3)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#4)
      PU L#5 (P#5)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#6)
      PU L#7 (P#7)
```

### What version of hwloc are you using?
```
lstopo --version
lstopo 2.4.1
```
hwloc comes from the FreeBSD port devel/hwloc2, built with clang.

### Which operating system and hardware are you running on?

uname -a
FreeBSD graf.pompo.net 12.2-STABLE FreeBSD 12.2-STABLE r368766 GRAF191116  amd64
(Same error on another machine running FreeBSD-Current)

**Comment by bgoglin** [comment]
Hello, It's a known limitation on BSDs, see https://www.open-mpi.org/projects/hwloc/doc/v2.4.1/a00364.php#faq_privileged
By the way, the error message will be hidden by default in 2.5 to avoid polluting the output of non-hwloc programs.

**Comment by thierry-FreeBSD** [comment]
Thanks!
Indeed, the following sequence fixed the problem:
```
$ mkdir ~/hwloc/
$ su -m
# lstopo --of xml > ~/hwloc/hwloc.xml
$ export HWLOC_XMLFILE=$HOME/hwloc/hwloc.xml
```
