### ISSUE TITLE
Getting static HWLOC library on Windows without MinGW or Cygwin dependencies

### ISSUE THREAD

**Issue by ivankochin** [open-mpi/hwloc#460]
### What version of hwloc are you using?
hwloc 2.4.0

### Which operating system and hardware are you running on?
Windows

### Details of the problem
I want to create a statically linked solution using the HWLOC library. On Linux, I've successfully built the static library using the `./configure --enable-static=yes` command, but on Windows official HWLOC package contains the static library that requires MinGW availability.

Is there any official way to get the static HWLOC library on Windows without MinGW or Cygwin dependencies?

**Comment by bgoglin** [comment]
Hello.
This was supposed to work in the MSVC solution last year according to changes merged in https://github.com/open-mpi/hwloc/pull/420

**Comment by ivankochin** [comment]
Thanks, this option seems applicable to me, but I can see only the `ReleaseStatic` configuration. Is there any way to create the library in `DebugStatic` mode?

**Comment by bgoglin** [comment]
We never enabled Debug builds in hwloc.sln because "they didn't work". But they are still in libhwloc.vcxproj etc. So maybe you'll be able to re-enable them? Did you manage to get Debug (without Static) already?

**Comment by ivankochin** [comment]
At this moment I successfully solved all cases without the debug library, so the latest question is not actual for me anymore.
Thanks for the help!
