### ISSUE TITLE
Icon theming

### ISSUE THREAD

**Issue by arcolinuxz** [open-mpi/hwloc#466]
Can you add the line 

Icon=hwloc

to your .desktop file in /usr/share/applications

It makes your application themable.

![image](https://user-images.githubusercontent.com/36679406/118624341-5ce8c400-b7c9-11eb-9486-471d7b233158.png)

**Comment by bgoglin** [comment]
Hello
Aren't we supposed to distribute a hwloc.foo icon then? Or would the behavior be similar to currently but themes would be able to specify/override a custom icon for lstopo?
Brice

**Comment by arcolinuxz** [comment]
You can supply your own icon 

most of the time they put the icons in /usr/share/icons/hicolor

it can be a png or a svg

but

in the .desktop file you do not use paths or extensions

so just

Icon=hwloc

Linux will then search for any and all icons for that name - png or svg
When the users chooses the icon theme - it will look in that folder for the name hwloc

**Comment by bgoglin** [comment]
Thanks for the explanation, I applied this.
