### ISSUE TITLE
lstopo factorized "8x total" mis-aligned in tikz and fig outputs

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#481]
`lstopo --no-io --factorize=l2,1` on any platform with multiple L2 below a L3 will show one L2 and 3 little squares for hidden/factorized cores and something like "8x total" below. On tikz and fig graphical outputs, the text width cannot be exactly measured, it is over-estimated to avoid crossing the box boundary. This causes the text to be misaligned with respect to squares, and squares to be slightly moved to the right (see the attachment below).
[foo.pdf](https://github.com/open-mpi/hwloc/files/7099074/foo.pdf)

**Comment by clementFoyer** [comment]
2 points that could be interesting : We may want to evaluate the size of text by knowing a fixed size part (the `x total`, but this is also connected to the font, so a correlation table could be necessary) and a variable size, which is the number part, as this has less variability in text width.

The second point is that if we know the label will never be wider than the three small boxes marking the elusion, the label can be anchored on its west, which could be directly aligned with the left-most part of the left-most box.
