### ISSUE TITLE
distances vs multinode

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#49]
Some user want distances in multinode topologies.

1) It's currently disabled because we use cpusets/nodesets to find/create a common ancestor where the matrix is attached. Multinode objects have no cpusets/nodesets.

One way to solve this would be to add a hostset or machineset bitmap to each object to identify the hosts/machines it corresponds too.

2) We'll need a better way to identified objects in multinode topologies. Most distance insertion routines currently use physical indexes, but those are meaningless in multinode systems (and even not always meaningfull in single-node systems because core ids are not always unique).

See also ticket #67 when people don't care about grouping.

**Comment by bgoglin** [comment]
This would actually be possible with the new 2.0 distance API since it manipulates objects instead of indexes.
