### ISSUE TITLE
lstopo: switch to textual output when writing to a pipe, etc

### ISSUE THREAD

**Issue by bgoglin** [open-mpi/hwloc#503]
lstopo currently auto switches from graphical to textual output when DISPLAY is not set in the environment. It could also do that when stdout is a pipe, file, etc.

We may add an explicit "graphics" output format to force the graphical output even when default wants to use console (maybe for catching some debug messages in a pipe/file).

cc @philippemilink

**Comment by philippemilink** [comment]
To give more details, when I connect through SSH into a server with a graphic environment installed on this server:
```
% echo $DISPLAY                                                                                                                                                                                                                                                                                                     
raspberrypi:10.0
% lstopo
# opens a window, with the graphical output
% lstopo | cat
# opens a window, with a graphical output
```
The last command is the one I consider incoherent: I would expect no graphical window and the same output than `lstopo --of console` (like when there is no `$DISPLAY`).

**Comment by bgoglin** [comment]
When redirecting to a pipe or file, only the list of interactive shortcuts is sent there, it's indeed non-sense.

We could force the non-X11 output if stdout isn't a tty, but this will break the launching of lstopo from the window manager menu. In some managers, stdout is the .xsession-errors file. In others, it's a socket. I am not sure there's a safe way to distinguish between lstopo being launched in a terminal with redirected stdout (want text output), and lstopo being launched from a graphical menu (want graphical output).

We could add a command-line option to force the X11 output when stdout is not a terminal, and set this option in the desktop app file to revert to the current behavior. If people use the hwloc-provided lstopo.desktop file, they won't see the difference.

By the way, I also need to disable the displaying of the interactive shortcuts when stdout isn't a tty.

**Comment by sthibaul** [comment]
> In some managers, stdout is the .xsession-errors file. In others, it's a socket

Normally in these cases, the process doesn't have a controlling tty, so tcgetpgrp would fail with ENOTTY, which we can check for.

**Comment by bgoglin** [comment]
"lstopo" redirected in a file or pipe causes tcgetpgrp(STDOUT_FILENO) to return -1/ENOTTY as well. Did you mean tcgetpgrp() on other file descriptor?

**Comment by sthibaul** [comment]
it's rather usually STDIN which is the controlling tty

**Comment by bgoglin** [comment]
Thanks, STDIN seems to work.
