### ISSUE TITLE
autogen.sh: Big Sur libtool patch detection on non-macOS

### ISSUE THREAD

**Issue by buczek** [open-mpi/hwloc#505]
### What version of hwloc are you using?

master @ 005fcda26ac433994cfcdb67001a7864cdaf133d

### Which operating system and hardware are you running on?

GNU/Linux x86_64 
no common distribution
`Linux theinternet.molgen.mpg.de 5.10.24.mx64.375 #1 SMP Fri Mar 19 12:29:21 CET 2021 x86_64 GNU/Linux`

### Details of the problem

Minor cosmetic problem: The output of `autogen.sh` looks disturbing when run on an GNU/Linux system with libtool 2.4.2.

```
buczek@theinternet:~/git/hwloc (master)$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
[...]
Checking whether configure needs patching for MacOS Big Sur libtool.m4 bug... yes
Trying to patch configure...
checking file configure
Hunk #1 FAILED at 8846.
1 out of 1 hunk FAILED
WARNING: Couldn't apply Big Sur libtool.m4 bug fix.
```
The "skip the patch" pattern `darwin\[912`  in `autogen.sh` doesn't match:
```
buczek@theinternet:~/git/hwloc (master)$ grep -A1 MACOSX_DEPLOYMENT_TARGET configure
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
	10.0,*86*-darwin8*|10.0,*-darwin[91]*)
```

Maybe just add `2>/dev/null` for  the `patch --dry-run` in `autogen.sh` ?

**Comment by bgoglin** [comment]
Thanks, I am indeed sending these messages to /dev/null, our "WARNING..." line is enough.

Can you post the output "grep -C10 MACOSX_DEPLOYMENT_TARGET-10.0 configure" to check whether we need to update the patch? I don't know if the big-sur patch is already applied to your libtool.

Brice

**Comment by buczek** [comment]
Thanks!
```
buczek@theinternet:~/git/hwloc (master)$ grep -C10 MACOSX_DEPLOYMENT_TARGET-10.0 configure
$as_echo "$lt_cv_ld_force_load" >&6; }
    case $host_os in
    rhapsody* | darwin1.[012])
      _lt_dar_allow_undefined='${wl}-undefined ${wl}suppress' ;;
    darwin1.*)
      _lt_dar_allow_undefined='${wl}-flat_namespace ${wl}-undefined ${wl}suppress' ;;
    darwin*) # darwin 5.x on
      # if running on 10.5 or later, the deployment target defaults
      # to the OS version, if on x86, and 10.4, the deployment
      # target defaults to 10.4. Don't you love it?
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
	10.0,*86*-darwin8*|10.0,*-darwin[91]*)
	  _lt_dar_allow_undefined='${wl}-undefined ${wl}dynamic_lookup' ;;
	10.[012]*)
	  _lt_dar_allow_undefined='${wl}-flat_namespace ${wl}-undefined ${wl}suppress' ;;
	10.*)
	  _lt_dar_allow_undefined='${wl}-undefined ${wl}dynamic_lookup' ;;
      esac
    ;;
  esac
    if test "$lt_cv_apple_cc_single_mod" = "yes"; then
```

**Comment by buczek** [comment]
With  1f846f66a38f ("autogen: hide bigsur libtool patch apply failure messages"),  I still have the "WARNING", because it tries to use the patch which doesn't apply.

```
Checking whether configure needs patching for MacOS Big Sur libtool.m4 bug... yes
Trying to patch configure...
WARNING: Couldn't apply Big Sur libtool.m4 bug fix.
```

But IMO that's fine. The produced `configure` script is not suited for Big Sur, so the warning is justified. But now it doesn't look like an error and you know you can ignore that if you are not going to use the `configure` script on macOS anyway.

**Comment by bgoglin** [comment]
Yes, the issue is that there are multiple versions of the libtool fix in the wild. We detect 2 of them to avoid the warning but your code is different. One bigsur patch was finally applied to upstream libtool in November so hopefully things will converge in the near future.

You said "no common distribution", does this mean you're using the vanilla libtool? Your grep output doesn't seem to match the upstream libtool code. Which libtool version are you using?

**Comment by buczek** [comment]
Yes, vanilla libtool 2.4.2 without any local changes. Upstream m4 source of the quoted block from configure is at [1]. But I don't think you need or can provide patches for every version of libtool which ever existed and might be in use somewhere :-).  As I said, its fine for me now, we won't configure for macOS and the warning lets us know that it wouldn't work.

Of course, to patch the generated configure script is a bit of a hack and maybe there is something more elegant to solve the macOS problem. If so, I don't have it, unfortunately.

[1]: https://git.savannah.gnu.org/cgit/libtool.git/tree/libltdl/m4/libtool.m4?h=v2.4.2#n1043
