### ISSUE TITLE
configure fails on Android: could not determine link -lib interface

### ISSUE THREAD

**Issue by Saikatsaha1996** [open-mpi/hwloc#506]
Hwloc version new
Android termux
I install successful past but today I can't configure..
![Screenshot_2021-12-11-02-56-53-532_com termux](https://user-images.githubusercontent.com/72664192/145643623-e43c3149-4f25-46d5-a576-add4083b0fbb.jpg)

**Comment by bgoglin** [comment]
Hello
I didn't even know it was possible to configure hwloc like this on Android. I have no idea how to debug this. Does it work with an older hwloc version on the same Android? If you can locate one release where it worked and one where it started failing, I may be able to help doing the bissection.

**Comment by Saikatsaha1996** [comment]
> Hello I didn't even know it was possible to configure hwloc like this on Android. I have no idea how to debug this. Does it work with an older hwloc version on the same Android? If you can locate one release where it worked and one where it started failing, I may be able to help doing the bissection.

Yes i installed successfully August month
![Screenshot_2021-12-11-05-13-56-935_com android chrome](https://user-images.githubusercontent.com/72664192/145654570-787153c5-f85d-414f-b980-9801ee676895.jpg)

But now i can't

**Comment by bgoglin** [comment]
I couldn't find any relevant change in hwloc configure scripts since August 6th. Try building that same hwloc version again (commit c06496af52442825b4ffa59f5e0abd752a5d5364) to make sure it's a hwloc change that broke things and not something else in your build environment.

**Comment by Saikatsaha1996** [comment]
> I couldn't find any relevant change in hwloc configure scripts since August 6th. Try building that same hwloc version again (commit [c06496a](https://github.com/open-mpi/hwloc/commit/c06496af52442825b4ffa59f5e0abd752a5d5364)) to make sure it's a hwloc change that broke things and not something else in your build environment.

Ok I will trying

**Comment by Saikatsaha1996** [comment]
> I couldn't find any relevant change in hwloc configure scripts since August 6th. Try building that same hwloc version again (commit [c06496a](https://github.com/open-mpi/hwloc/commit/c06496af52442825b4ffa59f5e0abd752a5d5364)) to make sure it's a hwloc change that broke things and not something else in your build environment.

Done!
My mistake

git clone https://github.com/open-mpi/hwloc.git
cd hwloc
./autogen.sh
./configure --prefix=$PREFIX --host=aarch64-linux-android
make -j$(nproc)
make install -j$(nproc)

**Comment by fashni** [comment]
It's missing the `ar` binary. Installing the binutils package solves this problem.
```
pkg install binutils
```
