### ISSUE TITLE
Apple M1 probably has incorrect cache infomration

### ISSUE THREAD

**Issue by PaulBone** [open-mpi/hwloc#507]
### What version of hwloc are you using?

lstopo 2.6.0
built from `brew install hwloc`

### Which operating system and hardware are you running on?

Running on at 16GB Mac Mini M1,
System Version:	macOS 12.1 (21C52)
  Kernel Version:	Darwin 21.2.0

```
Machine (3578MB total)
  Package L#0
    NUMANode L#0 (P#0 3578MB)
    L2 L#0 (4096KB)
      L1d L#0 (64KB) + L1i L#0 (128KB) + Core L#0 + PU L#0 (P#0)
      L1d L#1 (64KB) + L1i L#1 (128KB) + Core L#1 + PU L#1 (P#1)
      L1d L#2 (64KB) + L1i L#2 (128KB) + Core L#2 + PU L#2 (P#2)
      L1d L#3 (64KB) + L1i L#3 (128KB) + Core L#3 + PU L#3 (P#3)
    L2 L#1 (4096KB)
      L1d L#4 (64KB) + L1i L#4 (128KB) + Core L#4 + PU L#4 (P#4)
      L1d L#5 (64KB) + L1i L#5 (128KB) + Core L#5 + PU L#5 (P#5)
      L1d L#6 (64KB) + L1i L#6 (128KB) + Core L#6 + PU L#6 (P#6)
      L1d L#7 (64KB) + L1i L#7 (128KB) + Core L#7 + PU L#7 (P#7)
  CoProc(OpenCL) "opencl0d0"
```

### Details of the problem

As above `lstopo -` the cache in the different cores is detected incorrectly.
https://en.wikipedia.org/wiki/Apple_M1

M1 has two types of cores, the performance cores have L1i: 192KB, L1d: 128KB and *I think* they share 12MB L2  The effeciency cores have L1i: 128KB and L1d: 64KB and share 4MB L2 as detected by lstopo

### Additional information

If your issue consists in a wrong topology detection, we also need the following for debugging remotely:

* On MacOS and BSD, `sysctl hw` and `sysctl machdep`
```
% sysctl hw
hw.ncpu: 8
hw.byteorder: 1234
hw.memsize: 17179869184
hw.activecpu: 8
hw.perflevel0.cpusperl2: 4
hw.perflevel0.l1dcachesize: 131072
hw.perflevel0.l1icachesize: 196608
hw.perflevel0.l2cachesize: 12582912
hw.perflevel0.logicalcpu: 4
hw.perflevel0.logicalcpu_max: 4
hw.perflevel0.physicalcpu: 4
hw.perflevel0.physicalcpu_max: 4
hw.perflevel1.cpusperl2: 4
hw.perflevel1.l1dcachesize: 65536
hw.perflevel1.l1icachesize: 131072
hw.perflevel1.l2cachesize: 4194304
hw.perflevel1.logicalcpu: 4
hw.perflevel1.logicalcpu_max: 4
hw.perflevel1.physicalcpu: 4
hw.perflevel1.physicalcpu_max: 4
hw.features.allows_security_research: 0
hw.optional.arm.FEAT_AES: 1
hw.optional.arm.FEAT_BF16: 0
hw.optional.arm.FEAT_BTI: 0
hw.optional.arm.FEAT_CSV2: 1
hw.optional.arm.FEAT_CSV3: 1
hw.optional.arm.FEAT_DPB: 1
hw.optional.arm.FEAT_DPB2: 1
hw.optional.arm.FEAT_DotProd: 1
hw.optional.arm.FEAT_ECV: 1
hw.optional.arm.FEAT_FCMA: 1
hw.optional.arm.FEAT_FHM: 1
hw.optional.arm.FEAT_FP16: 1
hw.optional.arm.FEAT_FPAC: 0
hw.optional.arm.FEAT_FRINTTS: 1
hw.optional.arm.FEAT_FlagM: 1
hw.optional.arm.FEAT_FlagM2: 1
hw.optional.arm.FEAT_I8MM: 0
hw.optional.arm.FEAT_JSCVT: 1
hw.optional.arm.FEAT_LRCPC: 1
hw.optional.arm.FEAT_LRCPC2: 1
hw.optional.arm.FEAT_LSE: 1
hw.optional.arm.FEAT_LSE2: 1
hw.optional.arm.FEAT_PAuth: 1
hw.optional.arm.FEAT_PAuth2: 0
hw.optional.arm.FEAT_PMULL: 1
hw.optional.arm.FEAT_RDM: 1
hw.optional.arm.FEAT_SB: 1
hw.optional.arm.FEAT_SHA1: 1
hw.optional.arm.FEAT_SHA256: 1
hw.optional.arm.FEAT_SHA3: 1
hw.optional.arm.FEAT_SHA512: 1
hw.optional.arm.FEAT_SPECRES: 0
hw.optional.arm.FEAT_SSBS: 1
hw.optional.AdvSIMD: 1
hw.optional.AdvSIMD_HPFPCvt: 1
hw.optional.arm64: 1
hw.optional.armv8_1_atomics: 1
hw.optional.armv8_2_fhm: 1
hw.optional.armv8_2_sha3: 1
hw.optional.armv8_2_sha512: 1
hw.optional.armv8_3_compnum: 1
hw.optional.armv8_crc32: 1
hw.optional.armv8_gpi: 1
hw.optional.breakpoint: 6
hw.optional.floatingpoint: 1
hw.optional.neon: 1
hw.optional.neon_fp16: 1
hw.optional.neon_hpfp: 1
hw.optional.ucnormal_mem: 1
hw.optional.watchpoint: 4
hw.cacheconfig: 8 1 4 0 0 0 0 0 0 0
hw.cachelinesize: 128
hw.cachesize: 3751329792 65536 4194304 0 0 0 0 0 0 0
hw.cpu64bit_capable: 1
hw.cpufamily: 458787763
hw.cpusubfamily: 2
hw.cpusubtype: 2
hw.cputype: 16777228
hw.ephemeral_storage: 0
hw.l1dcachesize: 65536
hw.l1icachesize: 131072
hw.l2cachesize: 4194304
hw.logicalcpu: 8
hw.logicalcpu_max: 8
hw.nperflevels: 2
hw.osenvironment: 
hw.packages: 1
hw.pagesize: 16384
hw.pagesize32: 16384
hw.physicalcpu: 8
hw.physicalcpu_max: 8
hw.serialdebugmode: 0
hw.tbfrequency: 24000000
hw.use_kernelmanagerd: 1
hw.use_recovery_securityd: 0
hw.targettype: J274
```

```
% sysctl machdep
machdep.cpu.brand_string: Apple M1
machdep.cpu.core_count: 8
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
machdep.deferred_ipi_timeout: 64000
machdep.lck_mtx_adaptive_spin_mode: 1
machdep.phy_read_delay_panic: 0
machdep.phy_writedelay_panic: 0
machdep.report_phy_read_delay: 0
machdep.report_phy_read_osbt: 0
machdep.report_phy_write_delay: 0
machdep.report_phy_write_osbt: 0
machdep.time_since_reset: 64221460442
machdep.trace_phy_read_delay: 0
machdep.trace_phy_write_delay: 0
machdep.virtual_address_size: 47
machdep.wake_abstime: 17502953494
machdep.wake_conttime: 172806045455
machdep.user_idle_level: 0
```

**Comment by bgoglin** [comment]
Cache detection is wrong on many Max OS X platforms unfortunately. sysdep just returns invalid information in many cases, we cannot do much about it. The good news is that Apple seems to have added hybrid-specific information about caches in sysdep now (and it matches what you expected), so I should be able to fix this.

**Comment by bgoglin** [comment]
I can't find any information on which cores perflevel0 and perflevel1 correspond too. Looking at your output, I know perflevel0 is for performance cores while perflevel1 is for efficiency cores, but I'd like to have a future-proof way to be sure. Can you "grep -r perflevel ..." in your headers? Hopefully it's documented in your sys/sysctl.h.

**Comment by PaulBone** [comment]
Bingo!  From `sysctl.h` for MacOS 12.1
>  *   perflevel 0 always refers to the highest performance core type in the syste

Oh, and:
>  *   hw.perflevelN.l2perflevels     - These values provide a bitmap, where bit
number of CPUs of the same type that share L2 and L3 caches.
> *   hw.perflevelN.l3perflevels     - If a cache is not present then the selecto
r will return and error.

So we can find out which CPUs access which caches. but that conflates perf level and cache.  (at least how I'm reading it).  What happens in the future if Apple release a CPU with efficiency cores with 2 L2 caches (multiple caches per perf-level).

I'm happy to help further.

[sysctl.h.gz](https://github.com/open-mpi/hwloc/files/7742296/sysctl.h.gz)

**Comment by PaulBone** [comment]
Err, nevermind, it's documented but it's not provided when I run 'sysctl hw`.

**Comment by bgoglin** [comment]
Your issue with L2 caches isn't very important because core IDs aren't very useful on Mac OS X anyway (because we cannot bind tasks to specific CPUs). hw.perflevel0.logicalcpu/hw.perflevel0.cpusperl2 would tell us that there are multiple L2 per perflevel. Then we'd just assume 0-X are in first L2 and X+1...2X are in second L2.

Thanks a lot for the sysctl info. I am going to work on this but it'll take some time because my M1 remote access doesn't seem to work anymore, and because of christmas vacation :) I'll send some patches when I have something to test.

**Comment by PaulBone** [comment]
No worries, I've used hwloc in the past, but not much beyond "create as many worker threads as there are processors, optionally pin them."  I'm not planning anything in the near future but I wanted to test it anyway.  What I mean is you don't have to make it a priority for my sake, but I am happy to help because I like hwloc.

In the future I'm not even sure I want to take the above approach with macos since they have GCD.  I'm probably better off letting it schedule the jobs and not doing that myself.. but it depends on other constraints.

**Comment by bgoglin** [comment]
Hello. I got my M1 remote access back and got things to work. Can you try a tarball from https://ci.inria.fr/hwloc/view/all/job/bgoglin/466/ ?
On a Minimac, I see this:
```
% utils/lstopo/lstopo-no-graphics
Machine (3578MB total)
  Package L#0
    NUMANode L#0 (P#0 3578MB)
    L2 L#0 (4096KB)
      L1d L#0 (64KB) + L1i L#0 (128KB) + Core L#0 + PU L#0 (P#0)
      L1d L#1 (64KB) + L1i L#1 (128KB) + Core L#1 + PU L#1 (P#1)
      L1d L#2 (64KB) + L1i L#2 (128KB) + Core L#2 + PU L#2 (P#2)
      L1d L#3 (64KB) + L1i L#3 (128KB) + Core L#3 + PU L#3 (P#3)
    L2 L#1 (12MB)
      L1d L#4 (128KB) + L1i L#4 (192KB) + Core L#4 + PU L#4 (P#4)
      L1d L#5 (128KB) + L1i L#5 (192KB) + Core L#5 + PU L#5 (P#5)
      L1d L#6 (128KB) + L1i L#6 (192KB) + Core L#6 + PU L#6 (P#6)
      L1d L#7 (128KB) + L1i L#7 (192KB) + Core L#7 + PU L#7 (P#7)
  CoProc(OpenCL) "opencl0d0"
% utils/lstopo/lstopo-no-graphics --cpukinds
CPU kind #0 efficiency 0 cpuset 0x0000000f
  DarwinCompatible = apple,icestorm;ARM,v8
CPU kind #1 efficiency 1 cpuset 0x000000f0
  DarwinCompatible = apple,firestorm;ARM,v8
```
Seems to match what you expected.

**Comment by PaulBone** [comment]
> Hello. I got my M1 remote access back and got things to work. Can you try a tarball from https://ci.inria.fr/hwloc/view/all/job/bgoglin/466/ ?
> On a Minimac, I see this:

Yes, that works for me, it matches what you got also.  I'm also using a mac mini.
