### ISSUE TITLE
Freenode is dead

### ISSUE THREAD

**Issue by PaulBone** [open-mpi/hwloc#508]
Your README.md says

> There is also a #hwloc IRC channel on Freenode (irc.freenode.net).

I don't know if you still use freenode, but everyone moved elsewhere when Andrew Lee took over. Lots of people are now on libera.chat, but there's other options.  I'd recommend moving there, or if you have done already please update the README.md.

**Comment by bgoglin** [comment]
It looks I am already there too, just need to update the README then, thanks :)
