### ISSUE TITLE
Incorrect topology with "OverSubscribe=EXCLUSIVE" Slurm partition config

### ISSUE THREAD

**Issue by jussienko** [open-mpi/hwloc#511]
### What version of hwloc are you using?

hwloc-1.11.8-4 (in RHEL 7) and git master (93a0361)

### Which operating system and hardware are you running on?

AMD Rome, RHEL 7, kernel 3.10.0-1160.41.1.el7.x86_64

Slurm version: 20.11.8-1_issue_344

### Details of the problem

When running a job with undersubscribed nodes, hwloc reports that all PUs are available when Slurm partition config has "OverSubscribe=EXCLUSIVE". As an example:

```
srun --cpus-per-task=4 -p part1 hwloc-info
depth 0:	1 Machine (type #1)
 depth 1:	2 Package (type #3)
  depth 2:	8 NUMANode (type #2)
   depth 3:	32 L3Cache (type #4)
    depth 4:	128 L2Cache (type #4)
     depth 5:	128 L1dCache (type #4)
      depth 6:	128 L1iCache (type #4)
       depth 7:	128 Core (type #5)
        depth 8:	256 PU (type #6)
```
In another Slurm partition in the same system (without "OverSubscribe=EXCLUSIVE" config):
```
srun --cpus-per-task=4 -p part2 hwloc-info
depth 0:	1 Machine (type #1)
 depth 1:	2 Package (type #3)
  depth 2:	8 NUMANode (type #2)
   depth 3:	1 L3Cache (type #4)
    depth 4:	4 L2Cache (type #4)
     depth 5:	4 L1dCache (type #4)
      depth 6:	4 L1iCache (type #4)
       depth 7:	4 Core (type #5)
        depth 8:	8 PU (type #6)
```

Linux `sched_getaffinity` system call reports only `--cpus-per-task` available in both above cases

The configuration for Slurm resource confinement is:
```
TaskPlugin=task/affinity,task/cgroup
```
Attached debug output from the two different runs
[debug-exlusive.txt](https://github.com/open-mpi/hwloc/files/7853703/debug-exlusive.txt)
[debug-nonexlusive.txt](https://github.com/open-mpi/hwloc/files/7853704/debug-nonexlusive.txt)

**Comment by bgoglin** [comment]
hwloc just exposes the resources that are available in the cgroup that SLURM created (all cores in the first case, only 4 cores in the second case). hwloc seems to be working fine here.

Exclusive case in the log:
```
Found cgroup name `/slurm/uid_8842/job_911438/step_0'
Trying to read cgroup1 file </sys/fs/cgroup/cpuset/slurm/uid_8842/job_911438/step_0/cpuset.cpus>
cpuset includes 0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff,0xffffffff
Trying to read cgroup1 file </sys/fs/cgroup/cpuset/slurm/uid_8842/job_911438/step_0/cpuset.mems>
cpuset includes 0x000000ff
```

Non-exclusive case:
```
Found cgroup name `/slurm/uid_8842/job_911437/step_0'
Trying to read cgroup1 file </sys/fs/cgroup/cpuset/slurm/uid_8842/job_911437/step_0/cpuset.cpus>
cpuset includes 0x0000000f,,,,0x0000000f
Trying to read cgroup1 file </sys/fs/cgroup/cpuset/slurm/uid_8842/job_911437/step_0/cpuset.mems>
cpuset includes 0x000000ff
```

**Comment by jussienko** [comment]
Ok, I have to admit that I do not know in detail how cgroup is supposed to work here. I just noticed that `sched_getaffinity` returns in both cases a cpumask which has only 4 cores. Similarly, OpenMP runtime shows in both cases affinity mask of 4 cores.
A minimum C code with OpenMP affinity:
```
#include <hwloc.h>
#include <omp.h>

int main()
{
  omp_display_affinity(NULL);

  printf("# counting cores with hwloc...\n");
  hwloc_topology_t topology;
  hwloc_topology_init(&topology);
  hwloc_topology_load(topology);
  int depth = hwloc_get_type_depth(topology, HWLOC_OBJ_CORE);
  char* level = "cores";
  int n = hwloc_get_nbobjs_by_depth(topology, depth);
  printf("# found %d %s\n", n, level);
  hwloc_topology_destroy(topology);
}
```
Output:
```
level 0 thread 0x7fffbffe67c0 affinity 0-3
# counting cores with hwloc...
# found 128 cores
```

**Comment by bgoglin** [comment]
I don't know SLURM in details but I would assume that:
* by default, non exclusive mode, a node may be shared between users or jobs: we don't want tasks from one job to use cores assigned to another job. cgroups do this, that's why you see only 4 cores in this case.
* in exclusive mode, you get the entire node, hence cgroups are NOT needed for preventing jobs or users from disturbing each other. cgroups could still be used to restrict the number of available cores to what you requested but it looks like SLURM doesn't enforce this.
I am closing this issue, feel free to ask more questions, I'll be happy to answer.

**Comment by jussienko** [comment]
I think your description about exlusive / non-exclusive is correct. However, even in exlusive mode one might want to limit the number of cores visible to application (i.e. have only 1 core per L3 cache), and in order to do that, Slurm may set affinity masks for the application (which apparently work outside cgroups). Now, if application uses hwloc API for finding number of available resources (e.g. cores), but the topology information is not consistent with the affinity mask, one may end up in the situation where application launches more threads than there are available cores resulting in severe performance degradation.

The question here is maybe then whether hwloc should use `sched_getaffinity` or similar instead of cgroups information? Or is there a way to use hwloc for querying number of available resources, taking into account affinity mask?

Btw. I noticed that I can reproduce the issue also outside Slurm e.g. with `numactl`, for example in my laptop
```
numactl --physcpubind=0,1 ./hw
level 0 thread 0x7fedf90e47c0 affinity 0-1
# counting cores with hwloc...
# found 4 cores
```

**Comment by bgoglin** [comment]
hwloc can use both cgroup and sched_setaffinity (we call this CPU binding). By default, cgroups are used to restrict the topology to the available resources. That's what most applications wanted when we created hwloc 12 years ago, that's why it's the default. I don't remember ever receiving an explicit request to limit the topology to the CPU affinity by default, but the API provided a way to implement it from early releases:
```
  hwloc_bitmap_t cpuset = hwloc_bitmap_alloc();
  hwloc_get_cpubind(topology, cpuset, 0);
  hwloc_topology_restrict(topology, cpuset, 0);
  hwloc_bitmap_free(cpuset);
```
This wasn't enough to avoid an unrelated problem on Windows, hence hwloc 2.5 brought a very easy way to activate this between init() and load():
```
  hwloc_topology_set_flags(topology, HWLOC_TOPOLOGY_FLAG_RESTRICT_TO_CPUBINDING|HWLOC_TOPOLOGY_FLAG_IS_THISSYSTEM);
```
I assumed above that only CPU affinity matter (SLURM doesn't limit memory nodes in cgroups in your case) but these examples can be extended to memory affinity too.

**Comment by jussienko** [comment]
Thanks a lot for the info, the `hwloc_topology_set_flags` seems to work fine. 

I ran recently into a application (https://gitlab.inria.fr/pm2/pm2/-/tree/master/mpibenchmark) which by default launched too many threads (due to hwloc topology information being inconsistent with affinity mask), however the application has also internal variables for controlling number of threads so this was not that severe problem.
