### ISSUE TITLE
Kindly add installation of Windows debugger files (pdb)?

### ISSUE THREAD

**Issue by emmenlau** [open-mpi/hwloc#512]
This is a kind feature request. Thanks for this great library! I've seen that when built on Windows, it generates debugger information (in file `libhwloc.pdb`). However this file is not installed with `make install`. Therefore it can not be found during debugging, and i.e. it is lost when the build tree is removed.

Would it be possible to add this file to the install target on Windows? I guess something like this may be a good start for shared library builds:
```
if(MSVC AND BUILD_SHARED_LIBS)
    install(FILES $<TARGET_PDB_FILE:${PROJECT_NAME}>
        DESTINATION "${CMAKE_INSTALL_BINDIR}"
        OPTIONAL)
endif()
```
It works a bit different for static libraries, though, and I do not have copy-paste-instructions for that case. See https://stackoverflow.com/a/40860436/7200132 for a good start...

**Comment by bgoglin** [comment]
@Neumann-A @scivision Do you see any problem with this?

**Comment by emmenlau** [comment]
Thanks for your consideration! I just wanted to add that its also possible to generate and store `pdb` files for static library builds. However requires that the `COMPILE_PDB_NAME` is set in cmake for the target. So something along those lines would need to be added in addition to the install command from above, too:
```
if (MSVC AND NOT BUILD_SHARED_LIBS)
    # Set the output name for debugger files, otherwise they are not generated:
    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        COMPILE_PDB_NAME_DEBUG ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELEASE ${PROJECT_NAME}
        COMPILE_PDB_NAME_MINSIZEREL ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELWITHDEBINFO ${PROJECT_NAME})
endif()
```
Then the install command should work for the static and the shared case...

**Comment by scivision** [comment]
I didn't try this, but like:

```cmake
if(MSVC)
  if(BUILD_SHARED_LIBS)
    install(FILES $<TARGET_PDB_FILE:${PROJECT_NAME}>
        TYPE BIN
        OPTIONAL)
  else()
    # Set the output name for debugger files, otherwise they are not generated:
      set_target_properties(${PROJECT_NAME}
          PROPERTIES
          COMPILE_PDB_NAME_DEBUG ${PROJECT_NAME}
          COMPILE_PDB_NAME_RELEASE ${PROJECT_NAME}
          COMPILE_PDB_NAME_MINSIZEREL ${PROJECT_NAME}
          COMPILE_PDB_NAME_RELWITHDEBINFO ${PROJECT_NAME})
  endif()
endif()
```

The use of PROJECT_NAME is since we happen to have PROJECT_NAME=hwloc and that's the library name of interest. If we had other/additional libraries to do this for, we'd do as above but with the specific other library name too.

**Comment by scivision** [comment]
This added to windows-cmake/CMakeLists.txt does install bin/hwloc.pdb for a Debug build:

```cmake
if(MSVC AND BUILD_SHARED_LIBS)
  install(FILES $<TARGET_PDB_FILE:hwloc>
    TYPE BIN
    OPTIONAL)
endif()
```

**Comment by emmenlau** [comment]
> This added to windows-cmake/CMakeLists.txt does install bin/hwloc.pdb for a Debug build with Visual Studio 2022:

Awesome!

**Comment by emmenlau** [comment]
> I am not sure this is [supported yet by CMake for static](https://gitlab.kitware.com/cmake/cmake/-/issues/16932#note_273512) and is an [open issue](https://gitlab.kitware.com/cmake/cmake/-/issues/16935).

I have been using libraries that have this working for static libraries, so in principle I know it can work. Furthermore I'm sure that setting the `COMPILE_PDB_NAME` is a good and required step. About the other details, I'm not 100% certain.

From one of the libraries I could extract the following pieces of code that works there. I do not know if all parts of these functions are required, i.e. the `PDB_OUTPUT_DIRECTORY` may be optional?
```
function(add_msvc_debugger_symbols TARGET_NAME)
    get_target_property(TARGET_TYPE "${TARGET_NAME}" TYPE)
    if("${TARGET_TYPE}" STREQUAL "SHARED_LIBRARY" OR "${TARGET_TYPE}" STREQUAL "EXECUTABLE")
        set_target_properties("${TARGET_NAME}" PROPERTIES
            PDB_NAME "${TARGET_NAME}"
            PDB_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    elseif("${TARGET_TYPE}" STREQUAL "STATIC_LIBRARY")
        set_target_properties("${TARGET_NAME}" PROPERTIES
            COMPILE_PDB_NAME "${TARGET_NAME}"
            COMPILE_PDB_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    else()
        message(FATAL_ERROR "add_msvc_debugger_symbols(): Unsupported target type '${TARGET_TYPE}'")
    endif()
endfunction()

function(install_msvc_debugger_symbols)
    set(TARGET_NAMES "${ARGN}")

    if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND MSVC)
        foreach(TARGET_NAME IN LISTS TARGET_NAMES)
            if("${TARGET_NAME}" STREQUAL "")
                message(STATUS "install_msvc_debugger_symbols(): The list contains empty entries. This typically comes from disabled components. Ignored.")
                continue()
            endif()
            get_target_property(TARGET_TYPE "${TARGET_NAME}" TYPE)
            if("${TARGET_TYPE}" STREQUAL "SHARED_LIBRARY" OR "${TARGET_TYPE}" STREQUAL "EXECUTABLE")
                get_target_property(PDB_NAME "${TARGET_NAME}" PDB_NAME)
                get_target_property(PDB_OUTPUT_DIRECTORY "${TARGET_NAME}" PDB_OUTPUT_DIRECTORY)
                if(NOT PDB_NAME OR NOT PDB_OUTPUT_DIRECTORY)
                    message(FATAL_ERROR "Could not detect PDB_NAME and/or PDB_OUTPUT_DIRECTORY for target '${TARGET_NAME}'")
                endif()
                install(FILES "${PDB_OUTPUT_DIRECTORY}/${PDB_NAME}.pdb" DESTINATION bin)
            elseif("${TARGET_TYPE}" STREQUAL "STATIC_LIBRARY")
                if(NOT "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
                    # NOTE: Static libraries do not generate pdb files with clang-cl.
                    # See also https://gitlab.kitware.com/cmake/cmake/-/issues/21169
                    get_target_property(COMPILE_PDB_NAME "${TARGET_NAME}" COMPILE_PDB_NAME)
                    get_target_property(COMPILE_PDB_OUTPUT_DIRECTORY "${TARGET_NAME}" COMPILE_PDB_OUTPUT_DIRECTORY)
                    if(NOT COMPILE_PDB_NAME OR NOT COMPILE_PDB_OUTPUT_DIRECTORY)
                        message(FATAL_ERROR "Could not detect COMPILE_PDB_NAME and/or COMPILE_PDB_OUTPUT_DIRECTORY for target '${TARGET_NAME}'")
                    endif()
                    install(FILES "${COMPILE_PDB_OUTPUT_DIRECTORY}/${COMPILE_PDB_NAME}.pdb" DESTINATION bin)
                endif()
            else()
                message(FATAL_ERROR "install_msvc_debugger_symbols(): Unsupported target type '${TARGET_TYPE}'")
            endif()
        endforeach()
    endif()
endfunction()
```

**Comment by bgoglin** [comment]
I just pushed the shared-lib part from https://github.com/open-mpi/hwloc/issues/512#issuecomment-1012523925 thanks.

**Comment by scivision** [comment]
Yes emmanlau as you note for static PDB custom CMake function script is required

**Comment by emmenlau** [comment]
Thanks this looks good, I'll close the issue!
