### ISSUE TITLE
Discrepancy of units in documentation of CUDA memory/cache size attributes

### ISSUE THREAD

**Issue by mkre** [open-mpi/hwloc#519]
Hi,

The [documentation](https://www.open-mpi.org/projects/hwloc/doc/v2.7.0/a00365.php) of the attributes `CUDAGlobalMemorySize`, `CUDAL2CacheSize`, and `CUDASharedMemorySizePerMP` states that

> Sizes are in kB.

However, looking at the [implementation](https://github.com/open-mpi/hwloc/blob/63fdc81cd7de4d9220aa2b9f3971971e49055352/hwloc/topology-cuda.c#L107-L108) of these functions, it turns out that the values returned by CUDA are divided by 1024 instead of 1000. Thus, I think the documentation should correctly state that the sizes reported by HWLOC are in "KiB" (kibibyte) rather than "kB" (kilobyte).

**Comment by bgoglin** [comment]
Thanks, I am going to fix this for CUDA as well as other GPU/accelerator/disk backends.
