### ISSUE TITLE
HWLOC_TOPOLOGY_FLAG_INCLUDE_DISALLOWED  flag is not working, offline cores are not being showed in Linux

### ISSUE THREAD

**Issue by rmarinbe** [open-mpi/hwloc#522]
### What version of hwloc are you using?
the release version is 2.7.0
> lstopo --version
lstopo 2.7.0

### Which operating system and hardware are you running on?

OS:
❯ uname -a           
Linux ubuntu 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

HW: 
Model name:           Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
2 sockets, 24 Cores per socket, 2 CPU/threads per Core (96 cpus total)

On-line CPU(s) list:  0,2-95
CPU 1 is offline on purpose to show the problem:
Off-line CPU(s) list: 1  (offline by this command echo 0 > /sys/devices/system/cpu/cpu1/online)

### Details of the problem
Offline cores are not shown in the topology (not in the graphical or command line)
I have tried:
lstopo --disallowed 
lstopo --disallowed --whole-system
lstopo --disallowed --flags 1

For example, this is a partial section of the output of lstopo --disallowed (last 3 Cores of Package/socket 0)

...
       L2 L#21 (1024KB) + L1d L#21 (32KB) + L1i L#21 (32KB) + Core L#21
        PU L#42 (P#22)
        PU L#43 (P#70)
      L2 L#22 (1024KB) + L1d L#22 (32KB) + L1i L#22 (32KB) + Core L#22
        PU L#44 (P#23)
        PU L#45 (P#71)
      L2 L#23 (1024KB) + L1d L#23 (32KB) + L1i L#23 (32KB) + Core L#23 + **PU L#46 (P#49)**
...
Notice that P#49 appears alone, the offline PU (#P1) is not shown even with the option --disallowed.

Worse that this, when all CPU's (LPUs/threads) that belong to a Core (for example cpu1 and cpu49 are offline) the whole Core or L2 cache topology cannot be retrieved.

### Additional information
I ran:  hwloc-gather-topology myhost
I also run lstopo --disallowed with one cpu disable in the core (lstopo1.svg) and also with the two cpus of the same core disabled (lstopo2.svg), neither case show the offline cpus, and in the second case the whole cache and core is not show in the hierarchy which according to the examples in the the documentation they should appear in red color, here notice that socket 1 has now 23 cpus and socket 2 has 24.

[gather_topo_output.tar.gz](https://github.com/open-mpi/hwloc/files/8065280/gather_topo_output.tar.gz)

[lstopo_images.tar.gz](https://github.com/open-mpi/hwloc/files/8065266/lstopo_images.tar.gz)

**Comment by bgoglin** [comment]
Hello
Offline cores are not only disallowed, they are offline. Disallowed means online but excluded (by cgroup/cpuset on Linux).
The doc talks about "offline" resources only in the sections about "complete_cpuset" and "complete_nodeset".
I'll see if I can clarify the doc.
Brice

**Comment by rmarinbe** [comment]
Hi @bgoglin,
Is there a way to see part of a topology like cores/caches, when the CPUs are offline? In our application, we are required to report all the topology, even the offline related CPUs.

**Comment by bgoglin** [comment]
No. Linux doesn't expose any cache/core info for offline cores, and x86 instructions for querying core/cache info must run on the target core, not on its neighbors.
One way to solve this is to boot with all cores online, save the hwloc topology to XML, make some cores offlines, load the XML and restrict the topology to what's online and allowed. If you want to go this way, I'll be happy to help.

**Comment by rmarinbe** [comment]
Thanks @bgoglin!
You are right about Intel x86 instructions! I was having some false hope from Linux stored info about those cpus
