### ISSUE TITLE
Looking for suggestions regarding README build challenges using distinct build directory

### ISSUE THREAD

**Issue by bradcray** [open-mpi/hwloc#526]
### What version of hwloc are you using?

2.6.0 (though my colleague @ronawho has mentioned seeing this with 2.7 as well, and we see it in 1.11.13 and as far back as 1.9, I believe)

### Which operating system and hardware are you running on?

I believe that this issue is independent of this information, but in writing up this issue, I was reproducing on:

$ uname -a Darwin [redacted] 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64

### Details of the problem

First, thanks for `hwloc`, which has been an invaluable package for our project to build upon!

For several years now, we've noticed that when:
* doing a `configure` + `make` of `hwloc` from a build directory distinct from where the sources live _and_
* `doc/doxygen-doc/hwloc.tag` happens to have a newer timestamp than `README`

we get a failure when building of the form:

```
...
Making all in doc
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in examples
make[3]: Nothing to be done for `all'.
sed -n -f ../../hwloc-2.6.0/doc/README.sed doxygen-doc/html/index.html > doxygen-doc/html/readme.tmp.html
/bin/sh: doxygen-doc/html/readme.tmp.html: No such file or directory
make[3]: *** [/Users/bradc/Downloads/hwloc-2.6.0/README] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

If we build within the `hwloc` source directory itself, we don't see this behavior.

For context as to why this might happen / one might care:
* We build in directories other than the source directory in order to maintain multiple versions of `hwloc` simultaneously, sharing a single set of sources (e.g., for distinct compilers, platforms, etc.)
* We store third-party packages like `hwloc` as unpacked / raw source, rather than a tarball, within our source tree in order to reduce the size of our project's history when we upgrade versions.  As a result, this can cause the timestamps of `README` vs. `hwloc.tag` to vary w.r.t. which is newer depending on when things are updated, checked out, etc.

We've historically worked around this using some `touch` commands within our Makefiles to try and ensure that `README` is newer than `hwloc.tag`, but would like to remove that logic if possible.  To that end, we were curious:

* whether you're already aware of this issue
* whether there's a `configure` option that could be used to skip the building of the README, since it doesn't particularly matter to us (we've given a cursory look, but haven't seen one)
* whether there's some other simple patch or fix we could apply that would work around the issue 

In slightly more detail, I believe you should be able to reproduce what we're seeing using:
```bash
$ [download and unpack hwloc-2.6.0.tar.gz as `/tmp/hwloc-2.6.0]
$ mkdir /tmp/hwloc-build
$ mkdir /tmp/hwloc-install
$ cd /tmp/hwloc-build
$ touch ../hwloc-2.6.0/doc/doxygen-doc/hwloc.tag
$ ../hwloc-2.6.0/configure CC=[your cc of choice] CXX=[your cxx of choice] --prefix=/tmp/hwloc-install --enable-static --disable-shared --disable-cairo --disable-libxml2 --disable-libudev --disable-cuda --disable-nvml --disable-opencl --disable-gl --disable-pci --with-hwloc-symbol-prefix=chpl_
$ make
```

**Comment by bgoglin** [comment]
Hello
I was not aware of the issue. The build system gets confused because your setup mixes the existing prebuilt documentation (built inside the source directory) and some things it wants to rebuild in your build directory.
The optimal solution might be to create doc/doxygen-doc/html before sed outputs its temporary file (your error message), and tell sed to use index.html from VPATH instead of only in the build tree (another error message you'd get later). I need to verify this won't brea something else.
Or we could add --disable-readme (or disable it by tricking configure so that it doesn't w3m and lynx (required for building the readme)).

**Comment by bgoglin** [comment]
@bradcray Can you try with tarball https://ci.inria.fr/hwloc/view/all/job/bgoglin/lastSuccessfulBuild/artifact/hwloc-builddir-readme-20220324.0638.git8abea95c5.tar.bz2 ? Hopefully it'll regenerate the README correctly.

**Comment by ronawho** [comment]
I can confirm that the linked tarball allows the README to be regenerated successfully.

That said it does result in a slightly different README (line lengths are different, missing "Generated by doxygen..." comment). If you're not opposed to another configure option, I think a `--disable-readme` option would be a clean solution for us.

FWIW I tried configuring with say `W3M={no,/dev/null,/does/not/exit}` and that didn't squash the generation (it just ignored `no` and found the `/usr/bin` version, and just accepted the abs paths.) If you know of good ways to trick configure I could try those, though I guess that approach would break if the README dependencies ever change.

**Comment by bgoglin** [comment]
Out of curiosity, do you know if it used w3m or lynx to generate the README? I think my build uses w3m, but yours may have regenerated with lynx if w3m was missing, it would explain the slightly different output.
Adding --disable-readme is likely easy, I'll look at it.

**Comment by bgoglin** [comment]
This tarball has --disable-readme that seems to work around the issue https://ci.inria.fr/hwloc/view/all/job/bgoglin/lastSuccessfulBuild/artifact/hwloc-disable-readme-20220324.1200.git3cd8d93cb.tar.bz2

**Comment by ronawho** [comment]
Can confirm that works around the issue for us.

**Comment by bradcray** [comment]
Thanks for the quick response on this, Brice!
