### ISSUE TITLE
potential NULL glibc-cpuset dereferences in topology-linux.c

### ISSUE THREAD

**Issue by ash1852** [open-mpi/hwloc#544]
Hi, I found a potential null pointer dereference bug in the project source code of hwloc, and I have shown the execution sequence of the program that may generate the bug on the graph below. The red text illustrates the steps that generate the bug, the green text represents some additional information to help understanding when the steps occur and the file path can be seen in the blue framed section.

![CPU_ALLOC](https://user-images.githubusercontent.com/87304478/187577800-0e0a56a8-b0d3-496b-b701-09e22ce112d2.jpg)

Although the code shown is for version 2.1.0, this potential bug is still present in the current version

https://github.com/open-mpi/hwloc/blob/352348a1d861614f67553dd5fd6ad1ef1d4ebca5/hwloc/topology-linux.c#L857-L860
would you can help to check if this bug is true?thank you!

**Comment by bgoglin** [comment]
Hello
Yes, there are likely many corner cases like where we don't check allocation return values. The (bad) rational is that other things will go wrong before this one will trigger a crash. Feel free to send a fix :)

**Comment by bgoglin** [comment]
Thanks for the reminder, I forgot about this, I am pushing the fix to master and all stable branches.
