### ISSUE TITLE
libxml2 needs a call to xmlMemGet to avoid undefined reference to `xmlFree'

### ISSUE THREAD

**Issue by jiangxiaobin96** [open-mpi/hwloc#545]
### What version of hwloc are you using?
1.11.13

### Which operating system and hardware are you running on?
Linux 5.4.0 amd64

### Details of the problem
```c
hwloc-1.11.13/src/topology-xml-libxml.c:533: undefined reference to `xmlFree'
hwloc-1.11.13/src/topology-xml-libxml.c:310: undefined reference to `xmlFreeDoc'
hwloc-1.11.13/src/topology-xml-libxml.c:372: undefined reference to `xmlNewProp'
...
```
I see  libxml2 is written so that calls to xmlFree, xmlMalloc and xmlRealloc dispatch through static variables in the DLL - the actual function has another name which is refer to [using libxml2 on MinGW - xmlFree crashes](https://www.linuxquestions.org/questions/programming-9/[solved]using-libxml2-on-mingw-xmlfree-crashes-839802/)

**Comment by bgoglin** [comment]
Hello
That's unexpected. I am gonna need to check the impact of the workaround and when we actually need to implement it (mingw works fine here).
```
AFTER an initial call to xmlParseFile() or some other xml function that initializes the DLL's variables, add the line:
if(!xmlFree)
  xmlMemGet(&xmlFree,&xmlMalloc,&xmlRealloc,NULL);
```

**Comment by bgoglin** [comment]
I am puzzled by your error messages. They seem to come from link time. The fix seems rather for fixing executime time errors. Also why is xmlNewProp() also not found? Are you sure it actually tries to link with the libxml DLL here?

**Comment by jiangxiaobin96** [comment]
I guess it is the error of static link. We use hwloc with libhwloc.a
- build
```shell
./configure --prefix=xxx/build --enable-static
make && make install
```
- readelf
```shell
readelf -s build/lib/libhwloc.a | grep xmlFree
66: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND xmlFree
68: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND xmlFreeDoc
```
Is it the problem of NOTYPE?

**Comment by bgoglin** [comment]
I can't even check with our prebuilt tarballs (those on the download website are built with MinGW too), readelf fails because the .a file is not an ELF file, which makes sense.
What does readelf report for other libxml symbols? is xmlNewProp the same? what about others? My understanding of the documentation is that only xmlFree/Alloc/Realloc/Strdup might be affected by the need to call xmlGetMem().

**Comment by jiangxiaobin96** [comment]
Thanks for your reply. We have solved this problem. libxml built without static link. Adding `--enable-static=yes --disable-libnuma CFLAGS="-static"` is OK.
