### ISSUE TITLE
Failure to bind Numa node to process ID 

### ISSUE THREAD

**Issue by evanovan** [open-mpi/hwloc#548]
### What version of hwloc are you using?  / lstopo 2.7.1

I am new to hwloc and I am trying to bind a process ID to a Numa node ( membind_proc call fails "Error set_proc_membind" )

code below 

```

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <stdlib.h>
#include "hwloc.h"


int main ()
{

  hwloc_bitmap_t set;
  hwloc_obj_t obj;
  hwloc_topology_t topology;

  hwloc_topology_init(&topology);
  hwloc_topology_load(topology);


  obj = hwloc_get_obj_by_type(topology, HWLOC_OBJ_NUMANODE, 0);
  set = hwloc_bitmap_dup(obj->cpuset);


  int e = hwloc_set_proc_membind(topology, getpid(), set, HWLOC_MEMBIND_BIND , HWLOC_MEMBIND_BYNODESET);
  if (e < 0)
  {
        printf("Error set_proc_membind \n");
  }

  void *ptr_Numanode_0 =  malloc(sizeof(int));


  hwloc_bitmap_free(set);
  return 0;
}

```

My questions  :  

- what is the issue in the code ?
- does membind_proc bind any malloc call that comes after to that specific Numa Node ? ( in this case Numa node 0 )
- Is this the best way to do it ? ( I dont want to do hwloc calls like "hwloc_alloc_membind" , i like the application not to change and use its own malloc calls ) 

Thanks and sorry if my question is not clear

**Comment by bgoglin** [comment]
Hello

When you pass MEMBIND_BYNODESET, you have to pass a nodeset, but you're passing obj->cpuset. Try obj->nodeset instead. If there's something unclear about this in the doc, please let me know.

Then proc_membind isn't available on all systems, not on Linux at least. If you print the error with perror or strerror(errno), you'll see errno=ENOENT in this case. Linux may only change the binding of the current thread.
```
$ hwloc-info --support | grep membind
membind:set_thisproc_membind = 0
membind:get_thisproc_membind = 0
membind:set_proc_membind = 0
membind:get_proc_membind = 0
membind:set_thisthread_membind = 1
```

Once those are fixed, all future allocations will go to that node. But malloc does not always allocate new pages. It may reuse pages that were partiall allocated before, or allocated and freed. Those won't move unless you explicitly request migration. Allocating with mmap() doesn't have the same issue, but it gives coarse-granularity allocations (entire pages).

**Comment by evanovan** [comment]
Hi, 

I made the changes: 

```
  obj = hwloc_get_obj_by_type(topology, HWLOC_OBJ_NUMANODE, 0);
  set = hwloc_bitmap_dup(obj->nodeset);

  int e = hwloc_set_proc_membind(topology, getpid(), set, HWLOC_MEMBIND_BIND , HWLOC_MEMBIND_BYNODESET);
  if (e < 0)
  {
        //printf("Error set_proc_membind \n");
        perror("error bind");
  }
```


I got this error : 
`error bind: Function not implemented`




gdb debug:

```
394     hwloc_set_proc_membind_by_nodeset(hwloc_topology_t topology, hwloc_pid_t pid, hwloc_const_nodeset_t nodeset, hwloc_membind_policy_t policy, int flags)
(gdb) s
hwloc_set_proc_membind_by_nodeset (topology=0x5555555592a0, pid=1524079, nodeset=<optimized out>,
    policy=HWLOC_MEMBIND_BIND, flags=32) at bind.c:408
408       errno = ENOSYS;
(gdb)
```



support 
```
hwloc-info --support | grep membind

- membind:set_thisproc_membind = 0
- membind:get_thisproc_membind = 0
- membind:set_proc_membind = 0
- membind:get_proc_membind = 0
- membind:set_thisthread_membind = 1
- membind:get_thisthread_membind = 1
- membind:set_area_membind = 1
- membind:get_area_membind = 1
- membind:alloc_membind = 1
- membind:firsttouch_membind = 1
- membind:bind_membind = 1
- membind:interleave_membind = 1
- membind:nexttouch_membind = 0
- membind:migrate_membind = 1
- membind:get_area_memlocation = 1
```

System
`5.4.0-81-generic`

**Comment by bgoglin** [comment]
Linux doesn't allow to change the memory binding policy of an entire process. If you really need this, your application will have to tell each individual thread to change it's own memory binding policy with set_membind(). If your application is not multithreaded, just use set_membind().

**Comment by evanovan** [comment]
@bgoglin is there an API to know the NUMA node ID from virtual address or physical frame number ?

similar to "page_to_nid" but from user space ?

**Comment by bgoglin** [comment]
Did you reply and remove your comment? I seem to remember you replied last week.

**Comment by bgoglin** [comment]
Several months later, let's assume things are OK now.
