### ISSUE TITLE
configure --with-target= fails to install (sed cannot find prefixed scripts)

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [open-mpi/hwloc#560]
### What version of hwloc are you using?

2.7.0

### Which operating system and hardware are you running on?

Linux <COMPUTER_NAME> 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux

Machine (16GB total) + Package L#0
  NUMANode L#0 (P#0 16GB)
  Core L#0 + PU L#0 (P#0)
  Core L#1 + PU L#1 (P#1)

My computer runs Windows 10 Enterprise (WSL), with an Intel Pentium G3258, 2*8GB Patriot Viper DDR3-1600 RAM, and built-in graphics.

### Details of the problem

I am trying to build Hwloc. `./configure --prefix="/root/MiOSR/toolchain/i686-elf/" --target=i686-elf` works, and so does `make -s`. But when I try to run `make -s check`, test-hwloc-compress-dir.sh fails to run.

### Additional information

I tried to fix a previous error that was related to `gunzip` and `tar` failing to unzip `test-hwloc-compress-dir.input.tar.gz` and `test-hwloc-compress-dir.output.tar.gz`. So, I tried to unzip them manually.

Here's the full `test-suite.log`:
```
=============================================
   hwloc 2.9.0: utils/hwloc/test-suite.log
=============================================

# TOTAL: 8
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-hwloc-compress-dir.sh
================================

ls: cannot access '/tmp/foosawUN6/test-hwloc-compress-dir.input': No such file or directory
Compressed 0 new topologies (0 were already compressed)
Kept 0 new topologies non-compressed (0 were already non-compressed)
/usr/bin/diff: /tmp/foosawUN6/test-hwloc-compress-dir.output: No such file or directory
FAIL test-hwloc-compress-dir.sh (exit status: 2)
```

**Comment by bgoglin** [comment]
So tar xfz doesn't work on this file only? Or on any .tar.gz file on this machine? What does it say?

**Comment by ItsNovaAndCrap** [comment]
it happens with every .tar.gz file, and here is the error gunzip gives me:
`/usr/bin/gunzip: 57: exec: gzip: Exec format error`
and the error tar gives me:
```
tar: This does not look like a tar archive
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now
``` (note: both errors have been used with empty .tar.gz files.)

**Comment by ItsNovaAndCrap** [comment]
FYI, i also tried these commands with an unempty .tar.gz archive, and they returned the same errors.

**Comment by bgoglin** [comment]
Sounds like your gzip executable is broken?

**Comment by ItsNovaAndCrap** [comment]
ok, i tried reinstalling gzip, and now i get this error:
```

gzip: fdsfdf.tar.gz: not in gzip format
```

**Comment by bgoglin** [comment]
What's this fdsfdf.tar.gz ? Try this:
```
tar cfz foo.tar.gz <a subdirectory of where you are>
tar tvfz foo.tar.gz => lists the contents, should match the contents of your directory
mkdir bar
cd bar
tar xfz ../foo.tar.gz => you should have a copy of the original directory under bar
```

**Comment by ItsNovaAndCrap** [comment]
fdsfdf.tar.gz is an example archive that i made myself
it has a txt file inside it which is about 27KB

**Comment by ItsNovaAndCrap** [comment]
ok now it unzips correctly... but i still have the error in `test-suite.log`

**Comment by bgoglin** [comment]
Add a line "set -x" after the copyright headers and send the full output of utils/hwloc/test-hwloc-compress-dir.sh

**Comment by ItsNovaAndCrap** [comment]
where do i find the copyright headers?
please pardon me being an idiot, this is my first time dealing with something like this

**Comment by bgoglin** [comment]
Inside the script utils/hwloc/test-hwloc-compress-dir.sh that you're going to run. set -x will make it display every single line it executes.

**Comment by ItsNovaAndCrap** [comment]
huh, that's weird...

i added `set -x` to the script, and it passed. super duper weird, but i'll take it.
i guess this fixes it then.

**Comment by ItsNovaAndCrap** [comment]
huh, now that I run `make -s install`, it doesn't work
here's the full log:
```
Making install in .
make[1]: Entering directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
make[2]: Entering directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
 /usr/bin/mkdir -p '/root/MiOSR/toolchain/i686-elf/bin'
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-annotate '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-annotate'
libtool: install: /usr/bin/install -c .libs/hwloc-annotate /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-annotate
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-bind '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-bind'
libtool: install: /usr/bin/install -c .libs/hwloc-bind /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-bind
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-calc '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-calc'
libtool: install: /usr/bin/install -c .libs/hwloc-calc /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-calc
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-diff '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-diff'
libtool: install: /usr/bin/install -c .libs/hwloc-diff /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-diff
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-distrib '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-distrib'
libtool: install: /usr/bin/install -c .libs/hwloc-distrib /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-distrib
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-info '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-info'
libtool: install: /usr/bin/install -c .libs/hwloc-info /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-info
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-patch '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-patch'
libtool: install: /usr/bin/install -c .libs/hwloc-patch /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-patch
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-ps '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-ps'
libtool: install: /usr/bin/install -c .libs/hwloc-ps /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-ps
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c hwloc-gather-cpuid '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-gather-cpuid'
libtool: install: /usr/bin/install -c .libs/hwloc-gather-cpuid /root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-gather-cpuid
 /usr/bin/mkdir -p '/root/MiOSR/toolchain/i686-elf/bin'
 /usr/bin/install -c hwloc-compress-dir '/root/MiOSR/toolchain/i686-elf/bin/./i686-elf-hwloc-compress-dir'
make  install-exec-hook
make[3]: Entering directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
/usr/bin/sed -e 's/HWLOC_top_builddir\/utils\/hwloc/bindir/' -e 's/HWLOC_top_builddir\/utils\/lstopo/bindir/' -e '/HWLOC_top_builddir/d' /root/MiOSR/toolchain/i686-elf/bin/hwloc-compress-dir > /root/MiOSR/toolchain/i686-elf/bin/hwloc-compress-dir.tmp && mv -f /root/MiOSR/toolchain/i686-elf/bin/hwloc-compress-dir.tmp /root/MiOSR/toolchain/i686-elf/bin/hwloc-compress-dir
/usr/bin/sed: can't read /root/MiOSR/toolchain/i686-elf/bin/hwloc-compress-dir: No such file or directory
make[3]: *** [Makefile:1829: install-exec-hook] Error 2
make[3]: Leaving directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
make[2]: *** [Makefile:1727: install-exec-am] Error 2
make[2]: Leaving directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
make[1]: *** [Makefile:1657: install-am] Error 2
make[1]: Leaving directory '/root/Downloads/hwloc-2.9.0/utils/hwloc'
make: *** [Makefile:1273: install-recursive] Error 1
```

**Comment by ItsNovaAndCrap** [comment]
also, sorry about the closing and reopening of the issue. i thought it had been fixed.

**Comment by bgoglin** [comment]
Oh that one is interesting. You've configured with --target=i686-elf so binaries are prefixed with that, but the sed command doesn't know it. I don't know how I am supposed to get that prefix in the Makefile, it might take some time.

**Comment by bgoglin** [comment]
To workaround the issue, comment-out the SED lines in the install-exec-hook rule at the end of utils/hwloc/Makefile.

**Comment by bgoglin** [comment]
Hello, sorry I forgot about this for a while. I merged Clement's fix into master. Feel free to try the tarball from https://ci.inria.fr/hwloc/job/basic/job/master/
I'll backport it to v2.10 too (to be released in a couple months) but I'd like your name to thank you in the NEWS for reporting the issue.
If you need a backport to earlier branches, the patch should be easy to apply https://github.com/open-mpi/hwloc/commit/32117b9109ed0c4c905ec2e291f8e610870f3bb8.diff
