### ISSUE TITLE
Document error cases

### ISSUE THREAD

**Issue by HadrienG2** [open-mpi/hwloc#578]
I'm writing [a Rust binding to hwloc](https://github.com/HadrienG2/hwlocality). It is not completely finished yet, but in the final polishing stages before publication.

One thing that I constantly struggled with in this project is that the error cases of hwloc are very sparsely documented. Many functions just return int without any documentation of which int values are possible, what values errno can take and what these errno values mean, etc. Sometimes (thankfully not often), even figuring out what inputs are valid or not requires juggling between multiple Doxygen pages, checking the source code or guessing.

I could provide a more idiomatic API to Rust clients if this situation improved, and I think it would be in the best interest of people who directly consume the hwloc C API too.

**Comment by bgoglin** [comment]
Hello
Please report specific cases so that we can maintain a list of what's missing and what we fixed. A quick look at hwloc.h doesn't reveal much missing information, except some trivial errno values (but I am not sure we are going to document everywhere that we can return ENOMEM on allocation failure).

**Comment by sthibaul** [comment]
Concerning potential errno values, we cannot really promise anything, since it's up to the kernel to decide what it may return.

**Comment by HadrienG2** [comment]
Thanks for your help!

> Please report specific cases so that we can maintain a list of what's missing and what we fixed.

@bgoglin Do you still want that list now that you started enumerating cases on your side in #579? A full list of entry points lacking error documentations would probably be quite long (I would say maybe 80% of the hwloc API surface), but perhaps a list of modules (per the doxygen index) where there are functions with missing docs would be good enough?

> Concerning potential errno values, we cannot really promise anything, since it's up to the kernel to decide what it may return.

Assuming the kernel does document its error cases, there is some prior art of translating kernel errors into standardized errno values in e.g. hwloc's [CPU binding](https://hwloc.readthedocs.io/en/v2.9/group__hwlocality__cpubinding.html) and [memory binding](https://hwloc.readthedocs.io/en/v2.9/group__hwlocality__membinding.html). But I can totally understand that this requires a fair amount of work on your side, may not always be feasible (e.g. if kernel APIs are poorly documented), and may not be top priority.

> but I am not sure we are going to document everywhere that we can return ENOMEM on allocation failure

One good strategy for these common errno values is to enumerate them in a shared location, rather than on every individual entry point. For example the [CPU binding](https://hwloc.readthedocs.io/en/v2.9/group__hwlocality__cpubinding.html) docs do this by mentioning in the module-level documentation that all binding functions can set errno to ENOSYS when the operation is impossible and EXDEV when binding to the target set cannot be enforced.

You could probably go one step further by having a "Error reporting" doxygen page which states library-wide conventions. For example, from a grep through the source code and a look at #579, I get the impression that almost every function that returns an int (except for topology diffing) returns 0 on success and -1 on failure, this could be a candidate for such a common documentation page.

**Comment by bgoglin** [comment]
I am going to review the entire API and push some changes in the next days, we'll discuss what remains then. The "error reporting" may indeed be a good candidate for documenting conventions.
