### ISSUE TITLE
Can we optionally load hardware information?

### ISSUE THREAD

**Issue by UERO** [open-mpi/hwloc#592]

**Comment by bgoglin** [comment]
Example ?

**Comment by UERO** [comment]
@bgoglin I need to get the number of cores, the number of pu and the corresponding thread information of the current machine. But I found that the hwloc_topology_load() takes at least 50ms to load a lot of irrelevant information, such as cache. this time is far beyond the program's running time, so I wonder if there is a way to selectively load hardware information?

**Comment by bgoglin** [comment]
Read https://www.open-mpi.org/projects/hwloc/doc/v2.9.1/a00373.php#faq_why (maybe I should rename that section) and maybe https://www.open-mpi.org/projects/hwloc/doc/v2.9.1/a00373.php#faq_slow_lstopo (which should be extended with rsmi and levelzero maybe).
If you're often using the same machine(s), see also https://www.open-mpi.org/projects/hwloc/doc/v2.9.1/a00373.php#faq_xml for saving the topology as XML.

**Comment by UERO** [comment]
hwloc_topology_set_all_types_filter(topology, HWLOC_TYPE_FILTER_KEEP_NONE);
    /* filter Package back in */
    hwloc_topology_set_type_filter(topology, HWLOC_OBJ_PACKAGE, HWLOC_TYPE_FILTER_KEEP_ALL);
    
    /* disable distances, memory attributes and CPU kinds */
    hwloc_topology_set_flags(topology, HWLOC_TOPOLOGY_FLAG_NO_DISTANCES
                                      |HWLOC_TOPOLOGY_FLAG_NO_MEMATTRS
                                      |HWLOC_TOPOLOGY_FLAG_NO_CPUKINDS);
Thank you for your help. I took the configuration you provided and the load time went from 31ms to 23ms, but this is still much longer than the execution time of my program. Is there any other option I can disable?

**Comment by bgoglin** [comment]
Not that I know of. As long as you are loading the native topology, on Linux it means reading lots of tiny files in /sys and those syscalls aren't very quick unfortunately (especially when multiple processes do it simultaneously). Saving a XML topology on each node is the only way to improve this.

**Comment by bgoglin** [comment]
There's one small optimization that I could had to the code if you can test it. If you built your own hwloc, go in hwloc/topology-linux.c, search for "look at the caches" and disable the for loop just below that comment (put an #if 0 before the `for()` and #endif before `} hwloc_bitmap_foreach_end();`)
This would potentially remove 4 open/read/close per cache per hardware thread.

**Comment by UERO** [comment]
Thanks a lot, hwloc_topology_load() on my machine is reduced by 6ms, which is an acceptable cost. 
>go in hwloc/topology-linux.c, search for "look at the caches" and disable the for loop just below that comment (put an #if 0 before the for() and #endif before } hwloc_bitmap_foreach_end();)

**Comment by bgoglin** [comment]
Ok thanks for testing, I'll commit a proper change. Another thing you may want to try: There are multiple CPU backends in hwloc. If you're running on x86, there's an x86 backend that is likely unneeded since the Linux backend already provides what you seem to need. The x86 backend can be disabled by setting `export HWLOC_COMPONENTS=-x86` in the environment (or by calling `hwloc_topology_set_components(topology, HWLOC_TOPOLOGY_COMPONENTS_FLAG_BLACKLIST, "x86") between `topology_init()` and `load()`). If you don't care about NUMA nodes, you could also try to disable the linux backend and only keep the x86 one (replace "x86" with "linux" above).

**Comment by UERO** [comment]
Thanks for your advice. I'm curious about "multiple CPU backends in hwloc", which you mentioned above. Could you tell me what is included in the hwloc, I can't seem to find it in the manual. Hope to get your reply.

**Comment by bgoglin** [comment]
See https://www.open-mpi.org/projects/hwloc/doc/v2.9.1/a00371.php
Backends and components are pretty much the same (components are the generic things that is declared to hwloc as "I can discover things", and backends are an instance of these once enabled).

**Comment by bgoglin** [comment]
I am closing this issue which has been quiet for 2-3 month. Feel free to add more related questions here if needed (but tag me @bgoglin to make sure I don't miss them).
