### ISSUE TITLE
Missing MemoryModule objects

### ISSUE THREAD

**Issue by xiongzubiao** [open-mpi/hwloc#598]
### What version of hwloc are you using?

lstopo 3.0.0a1-git, built from the newest source code

### Which operating system and hardware are you running on?

```
# uname -a
Linux fedora 6.2.0-rc6+ #12 SMP PREEMPT_DYNAMIC Tue Feb 28 15:56:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Details of the problem

In the output of `lstopo -v`, the `MemoryModule` objects are missing. The `dmidecode -t memory` can find it though.

After some digging into the source code, I feel it is related to `/sys/firmware/dmi/entries`. On this particular system, there is no `entries` subdirectory under `/sys/firmware/dmi`, but only a `tables` subdirectory:
```
# ls -l /sys/firmware/dmi
total 0
drwxr-xr-x 2 root root 0 Jun 20 17:49 tables
```

On some other system which has `/sys/firmware/dmi/entries`, `lstopo -v` works perfectly fine. I am not familiar with `dmi`, not sure why some system has no `entries` subdirectory. Any insights would be appreciated!

**Comment by bgoglin** [comment]
Hello. Do you have CONFIG_DMI_SYSFS enabled (look in /boot/config-...) in both kernel? If set to =m, the dmi-sysfs module should be loaded (check in lsmod)? I think that's required for the kernel to decode tables into individual entries. However dmidecode might be able to decode raw tables without that.

**Comment by xiongzubiao** [comment]
@bgoglin Thanks for the pointer! In the one where the MemoryModule is not shown, it is `CONFIG_DMI_SYSFS=m`. It is `CONFIG_DMI_SYSFS=y` in the other. `lsmod` doesn't show anything about dmi-sysfs though.

BTW, any plan that hwloc would decode raw tables as dmidecode?

**Comment by bgoglin** [comment]
On the CONFIG_DMI_SYSFS=m one, try `modprobe dmi-sysfs`.
There's no plan to decode raw tables, but I have no idea how hard it would be. If easy, could be possible if there's a strong need.

**Comment by xiongzubiao** [comment]
> On the CONFIG_DMI_SYSFS=m one, try modprobe dmi-sysfs.

It works like a charm! It is not a big hassle to run this command, so I see no strong need to decode raw tables. I will close the issue. Thanks a lot!
