### ISSUE TITLE
Improper Memory Affinity Reporting

### ISSUE THREAD

**Issue by antoine-morvan** [open-mpi/hwloc#604]
### What version of hwloc are you using?

2.9.1

### Which operating system and hardware are you running on?

* Red Hat Enterprise Linux release 8.6 (Ootpa)
* `Linux c266 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`
* AMD 7763 bisocket

### Details of the problem

Hello, 

#### Context

I was monitoring the affinity of some processes and trying to bind their buffers to dedicated banks. 

I initially run my programs using `mpiexec --map-by numa --bind-to numa`, that is lacking the memory bindings. The idea is to use hwloc-bind to get the current binding, then use it to bind the memory: `hwloc-bind --strict --membind $(hwloc-bind --get --logical)`.

In order to avoid blaming the MPI implementation, I use hwloc-bind for binding to compute units in the following examples.

#### The issue

The memory affinity is not displayed/reported/bound properly when I use `lstopo --pid $PID` with a `$PID` that is different from 0. For instance, in the method 1 below, I get the proper reporting (processing & memory); whereas in the method 2, I get proper processing binding, but the memory is not limited to the numa bank.

```
##
## Method 1: use lstopo --pid 0
##
hwloc-bind socket:0.numa:0 \
  bash -c "hwloc-bind --strict --membind \$(hwloc-bind --get --logical) \
    lstopo-no-graphics -p --of txt --no-io --no-legend --restrict binding --pid 0"
```
![image](https://github.com/open-mpi/hwloc/assets/18552103/4e6ea161-cefa-4f07-866f-eff7dc230bf4)

```
##
## Method 2: use lstopo --pid $PID_OF
##
(
  sleep 5
  lstopo-no-graphics -p --of txt --no-io --no-legend --restrict binding --pid $(pidof "sleep" | cut -d' ' -f1)
) &

hwloc-bind socket:0.numa:0 \
  bash -c "hwloc-bind --strict --membind \$(hwloc-bind --get --logical) \
    sleep 10"
```
![image](https://github.com/open-mpi/hwloc/assets/18552103/69d5734b-b54c-4868-94e1-151cbb505df3)

What did I do wrong ? :)

**Comment by bgoglin** [comment]
Hello

Linux doesn't support memory binding outside of the process itself. It only supports binding/querying the current thread. This should be shown in hwloc-info --support.
There are some discussions about revamping membind syscalls with a pid parameter but there won't be any official solution before a while.
Brice

**Comment by bgoglin** [comment]
That's correct, but I don't see any more "elegant" workaround for now.
