### ISSUE TITLE
Add optional argument(s) to --ps and --top to filter output

### ISSUE THREAD

**Issue by antoine-morvan** [open-mpi/hwloc#606]
### What version of hwloc are you using?

2.9.1

### Which operating system and hardware are you running on?

* Linux (RHEL8, 9; AmazonLinux2)
* Several systems (x86 & arm)

### Details of the problem

Hello,

As stated in the manpage of lstopo, the output can become "hard to read" when you start several processes with all the threads bound (e.g., `KMP_AFFINITY` set) on a large machine.

Here is an example where I combine the 2 flags `--ps --pid $PID`. We can see that my first MPI process is properly bound to 1st NUMA, but the processes/threads from the 3 other MPI processes are also shown. As well as lstopo. 

![image](https://github.com/open-mpi/hwloc/assets/18552103/564adcc9-af68-4bd8-8a2d-ecfcd3a80e3c)

To make it more readable, I would like to have an additional, optional argument to this option, that would be a PID (as for --pid).  This would show the processes/threads belonging to this PID hierarchy only.

I believe it will be easier to read several lstopo outputs (one per MPI process for instance) than deciphering one lstopo with all the processes. Also, we might be able to filter out some profiler, system or other wrapper bound processes.

**Comment by bgoglin** [comment]
Hello. We have a --pid for hwloc-ps, and the code is shared with lstopo --ps, so it shouldn't be too hard to implement. When you say "PID hierarchy", do you actually mean a hierarchy of process children (not sure how easy this is) or just a process and its threads (what hwloc-ps does) ?

**Comment by bgoglin** [comment]
Looks like proc/<pid>/task/<tid>/children would be a way to find children TIDs.

**Comment by bgoglin** [comment]
I pushed some code in a branch, a tarball will be available soon from https://ci.inria.fr/hwloc/view/all/job/bgoglin/528/

hwloc-ps has a new option "--children-of-pid <pid>" that will show the given PID and its children hierarchy. Can you check if it shows what you want?

I am not sure what to do with lstopo yet. We tried to have lots of top/ps related features in hwloc-ps but keep the minimum in lstopo because lstopo already has tons of other features and command-line options. I don't think we want to duplicate all hwloc-ps options in lstopo, but maybe there's a way to have lstopo rely on hwloc-ps somehow.

**Comment by antoine-morvan** [comment]
Hello, 

Although this was just some thinking, the children of PID seem to work (I used https://www.maqao.org/ in this experiment):
* `--pid`: https://gist.github.com/antoine-morvan/bdf35d3f86fd233dbb6119ba2ccb3720
* `--children-of-pid` : https://gist.github.com/antoine-morvan/41711fc7e6c506dd154e66467760ac43

I am more interested in seing such feature (just the `--pid` would be great) in lstopo: the rationale is that I mostly do my reporting using slide decks (either to managers, business, customers, students, or even other experts), and dropping a graphical view instead of a text log has way more impact. Thus the more options and flexibility offered by lstopo, the better (at least for me). Especially filtering the processes/threads I want to observed, either by PID, name, etc. Ideally those 😇 :
```
  --pid <pid>        Only show process of pid number <pid>
  --children-of-pid <pid> Only show process of pid number <pid> and its children
  --name <name>      Only show processes whose name contains <name>
  --uid <uid>        Only show processes of the user with the given uid
  --uid all          Show processes of all users
```

**Comment by bgoglin** [comment]
lstopo uses "Misc" objects to show processes and threads, and those objects can be used to show many other things. I am tempted to rather provide a generic way to add those Misc objects and just make hwloc-ps generate that input:
```
hwloc-ps .... <your options> --lstopo-misc-output=myfile
lstopo --misc-from=myfile
```
myfile could contain for each object:
* the name of the object to show (PID + command in our case)
* the cpuset
* maybe some options for colors (we'll keep the current yellow by default)

**Comment by antoine-morvan** [comment]
That would behave the same way as `hwloc-bind $(hwloc-calc xxxx)`. If the overhead is not excessive, that would be perfect.

Also, having a one liner would be neat :) 
```
lstopo --misc=$(hwloc-ps --lstopo-misc-format XXX)
```

**Comment by bgoglin** [comment]
In the meantime, that's already possible with:
```
# export the topology to XML
lstopo foo.xml
# add a Misc object for each line of the output
hwloc-ps --single-ancestor <youroptions> | while read pid locality command ; do hwloc-annotate foo.xml foo.xml -- $locality -- misc "$pid $command" ; done
# change all Misc objects to yellow background
hwloc-annotate foo.xml foo.xml -- misc:all -- info lstopoStyle Background=#ffff00
# display
lstopo -i foo.xml
```

**Comment by bgoglin** [comment]
#609 allows to do
```
hwloc-ps --children-of-pid 23 --lstopo-misc - | lstopo --misc-from -
```
Tarball will be available at https://ci.inria.fr/hwloc/job/basic/job/PR-609/ soon

**Comment by antoine-morvan** [comment]
Trying this PR-609 with

```sh
${HWLOC_PS_EXE} --short-name --threads --children-of-pid ${PID} --lstopo-misc - | \
        ${LSTOPO_EXE} --misc-from - ${_LSTOPO_WRAP_FLAGS} --pid ${PID} --of svg \
            > ${OUTPUT_FOLDER}/${PID}_observed_${DATE}.svg \
            2> ${OUTPUT_FOLDER}/${PID}_observed_${DATE}.svg.log
```

works like a charm on my first experiments 👍 

Just 2 comments:

## does not work with `--pid $PID`

The following 2 commands give the same output (`--lstopo-misc -` is ignored):

```
${HWLOC_PS_EXE} --short-name --threads --pid ${PID} --lstopo-misc -
${HWLOC_PS_EXE} --short-name --threads --pid ${PID} 
```

## the Thread ID seems to be missing in the name

`--children-of-pid ${PID}` properly list the thead IDs of children:
```sh
$ ${HWLOC_PS_EXE} --short-name --threads --children-of-pid ${PID}
2264522	PU:0 PU:2 PU:4 PU:6 PU:8 PU:10 PU:12 PU:14 PU:16 PU:18 PU:20 PU:22 PU:24 PU:26 PU:28 PU:30		pi.exe
 2264522	PU:0		pi.exe
 2264524	PU:2		pi.exe
```

But it disappears with `--lstopo-misc -`
```
$ ${HWLOC_PS_EXE} --short-name --threads --children-of-pid ${PID} --lstopo-misc -
name=2264522 pi.exe
cpuset=0x0000ffff
subtype=Process

name=2264522 pi.exe
cpuset=0x00000001
subtype=Thread

name=2264522 pi.exe
cpuset=0x00000002
subtype=Thread
```

**Comment by bgoglin** [comment]
Oops, thanks. --pid was indeed missing an else case.
Thread ids were indeed broken too. I reused the code from lstopo, so it's supposed to show "PID processname TID threadname" which can be quite long (if threadname is defined). We may discuss that formatting.
A new tarball will appear at https://ci.inria.fr/hwloc/job/basic/job/PR-609/ in several minutes.

**Comment by antoine-morvan** [comment]
Much better :)

Regarding thread naming there is definitely something to do, alhtough nothing in mind right now. But imo that surely deserve another issue since that might benenif `lstopo --ps` too or other usages.

**Comment by antoine-morvan** [comment]
To compare with the initial example, I can now observe each process individually:

![image](https://github.com/open-mpi/hwloc/assets/18552103/2fa1aad1-ad69-47f8-ac1c-87984769ff6e)

**Comment by bgoglin** [comment]
Indeed, that's nice. I am merging the PR and backporting to the future 2.10. Thanks for the suggestions and for testing.
