### ISSUE TITLE
No way to free a partially constructed group object

### ISSUE THREAD

**Issue by HadrienG2** [open-mpi/hwloc#619]
Constructing a group object is done through the following iterative procedure:

1. Call [`hwloc_topology_alloc_group_object()`](https://hwloc.readthedocs.io/en/latest/group__hwlocality__tinker.html#ga4cea4741165faf5323931a9ed8786ef7) to allocate a new group object.
2. Set up its cpusets and nodesets, typically using [`hwloc_obj_add_other_obj_sets()`](https://hwloc.readthedocs.io/en/latest/group__hwlocality__tinker.html#gad458715d3335df44849216cc123d1055).
3. Insert it into the topology using [`hwloc_topology_insert_group_object()`](https://hwloc.readthedocs.io/en/latest/group__hwlocality__tinker.html#ga1fc6012b3e1c249b83f48cb7bcacaa5b).

Currently (as of the latest readthedocs public API docs at the time of writing), if something goes wrong at step 2 and I must error out, there is no way to discard the previously allocated group object without inserting it. In this scenario, I have no apparent choice but to leak the allocation.

It would be good to instead have some kind of `hwloc_topology_free_group_object()` that can be called to clean up at some point after `hwloc_topology_alloc_group_object()`, for such cases where `hwloc_topology_insert_group_object()` has not yet been called and should not be called.

**Comment by bgoglin** [comment]
Indeed. I think the only way with the current API would be to set cpuset, nodeset, complete_cpuset, complete_nodeset back to NULL before hwloc_topology_insert_group_object(). I'll add a new function in 2.10 and document this workaround in 2.9.x

**Comment by bgoglin** [comment]
v2.10 will have hwloc_topology_free_group_object(). v2.9.4 (if ever released) will document that the group may be discarded by inserting without adding any CPU or node-sets. Thanks.
