### ISSUE TITLE
hwloc_topology_set_xmlbuffer doesn't seem to validate input on Windows

### ISSUE THREAD

**Issue by HadrienG2** [open-mpi/hwloc#623]
As of hwloc 2.9.3, and when using the [official binary builds](https://www.open-mpi.org/software/hwloc/v2.9/), the `hwloc_topology_set_xmlbuffer()` function does not seem to validate its input string on Windows. For example, `"<ZaLgO>"` is seemingly accepted (function returns 0) even though this string contains an unclosed tag and is very unlikely to otherwise match hwloc's XML schema.

**Comment by bgoglin** [comment]
I guess the Windows build doesn't use libxml hence it falls back to our internal minimalistic XML parser, which doesn't validate anything and will fail to load() later. I am closing this as wontfix since we're not going to improve our minimalistic parser.
