### ISSUE TITLE
Looks like 2.9.3 release was never announced?

### ISSUE THREAD

**Issue by chenrui333** [open-mpi/hwloc#627]
👋 it looks like the 2.9.3 release was never announced in the mailing list, `https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/`. Raise this issue to confirm it was a left out. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/151735

**Comment by bgoglin** [comment]
It was quickly announced in https://www.mail-archive.com/hwloc-announce@lists.open-mpi.org/msg00161.html without changing the subject.

**Comment by chenrui333** [comment]
oh, i see, thanks! (would be good to create a new one for future ref though)
