### ISSUE TITLE
Any drivers that supports MI250X from HPE CARY EX235A

### ISSUE THREAD

**Issue by yanbosmu** [open-mpi/hwloc#645]
hello, EVERYONE!
I got a AMD MI250X GPU card recently. Obviously it was a part from HPE cray EX235a system.
But I got problem in using it now in ubuntu. Probably no driver suitable in ubuntu?
So, do you have drivers or BIOS that can make my card alive? It is writtern D65201-OB Rev13 on GPU.

**Comment by bgoglin** [comment]
Hello, if you're looking for AMD GPU drivers, you should ask AMD. This github is about the hwloc software for managing the locality of CPU/memory/devices, not about drivers for these devices.
