### ISSUE TITLE
LoadLibrary("kernel32.dll") should be LoadLibrary(TEXT("kernel32.dll")) in topology-windows.c

### ISSUE THREAD

**Issue by MKoep** [open-mpi/hwloc#655]
`LoadLibrary` automatically switches between `LoadLibraryW` and `LoadLibraryA` when UNICODE is enabled or disabled but the given string `"kernel32.dll"` does not and the call fails. The `TEXT` macro fixes this.

`GetModuleHandle` has the same issue.

**Comment by bgoglin** [comment]
Thanks, does https://github.com/open-mpi/hwloc/pull/656/files look fine to you?

**Comment by bgoglin** [comment]
Thanks a lot, I am backporting this to stable branches. It will be in the next release, either 2.10.1 or 2.11 within a couple weeks.

**Comment by bgoglin** [comment]
Took a bit longer that expected, but I am posting 2.11rc1 right now with this fix.
