### ISSUE TITLE
relaxed distance constraints when NOT grouping

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#68]
I got some user requests about distance that don't fit well in the current distance model.

People want to insert distances just for getting them back later. Basically the topology (especially as XML) puts all inputs together (usual hwloc stuff + external things such as distances). The application just loads hwloc instead of loading multiple things and merging them

They don't care about us grouping. Grouping is actually what makes the current distance API not very satisfying, because grouping can reorder objects, and thus change logical indexes.

For their case, there's no reason to use physical indexes to identify objects in matrices, and we can deal with multiple topologies without any problem (ticket #48)

So these people need some relaxed distance matrix API that doesn't group and just annotates the topology with distance matrices.

**Comment by bgoglin** [comment]
This is possible since the new 2.0 distances API in commit 9e97e8a1e96a034b61027c122560320f7bad2785.
Grouping is a flag during distance addition, distances can be marked as latency or bandwidth or none.
