### ISSUE TITLE
Convenience value path of hwloc_memattr_get_value() lacks target object type checking

### ISSUE THREAD

**Issue by HadrienG2** [open-mpi/hwloc#685]
In hwloc 2.10.0 and current master, when `hwloc_memattr_get_value()` is called for a convenience value (CAPACITY or LOCALITY attribute), it [forwards the call to the `hwloc__memattr_get_convenience_value()` utility function](https://github.com/open-mpi/hwloc/blob/0b0f5fa8445b373a496a8692e17760979e933c98/hwloc/memattrs.c#L826).

This function, in turns [performs operations that either...](https://github.com/open-mpi/hwloc/blob/0b0f5fa8445b373a496a8692e17760979e933c98/hwloc/memattrs.c#L17)

- Assume the requested target is a NUMA node when querying the CAPACITY attribute.
- Assume the requested target has a CPU set when querying the LOCALITY attribute.

However, these assumptions are not checked by either of `hwloc_memattr_get_value()` and `hwloc__memattr_get_convenience_value()`. As a result, a program which calls `hwloc_memattr_get_value()` on a target which is not a NUMA node can get arbitrary garbage (if querying the `CAPACITY` attribute) or a segfault (if querying the `LOCALITY` attribute on an object which doesn't have a cpuset).

I think at least one of the `hwloc_memattr_get_value()` and `hwloc__memattr_get_convenience_value()` functions should ensure that the input object is a NUMA node and fail with EINVAL otherwise. Since `hwloc__memattr_get_convenience_value()` returns an unsigned 64-bit integer, it has no available bits in its current return type to encode an error, so `hwloc_memattr_get_value()` would be the most obvious place to insert such an error check.

**Comment by bgoglin** [comment]
It's even worse than that. the given target is read without checking for NULL first. Thanks, I'll fix all this.
At some point, you'll have to explain how you find all those deep bugs :)
