### ISSUE TITLE
A function to query the full list of memory attributes would be nice

### ISSUE THREAD

**Issue by HadrienG2** [open-mpi/hwloc#686]
Not for everyday usage, but it could make sense for tools that aim to exhaustively report topology properties... and when testing the topology editing functions of language bindings, as I do, where it's good to have an "I only modified what I intended and nothing else" assertion ;)

**Comment by bgoglin** [comment]
I think you should iterate over integer IDs starting from 0 until you get a EINVAL from hwloc_memattr_get_name() or hwloc_memattr_get_flags(). I don't think it's documented, but internally it's a contigous array of attributes starting from 0=CAPACITY to 7=WRITE_LATENCY and then dynamically registered ones (and there's no way to remove one). If that's enough, I'll document it.
