### ISSUE TITLE
latency between PU/core and local caches

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#69]
I got some user requests about distance that don't fit well in the current distance model (follow-up to #67).

People want distance from coreX to cacheY or memoryZ. That's different from our current matrices: we have distance from typeX to typeY (always the same type).

I don't think it's really a problem to say that distance from coreX to numaY is different from numaX to numaY. But our model currently does not support distance from a core to it's local cache for instance.

So we could annotate the tree to add the latencies between each core and its local caches. Different solutions:
1) each cache object (and numa node?) gets a new attribute for the latency to PU/core(s) under to this cache. This assume each core below a shared cached has the same latency...
2) Each pu (or core?) object gets an array of latencies to all memory/caches objects above it. API may be ugly given the variety of cache levels we can have.

**Comment by bgoglin** [comment]
FWIW, the new 2.0 distances API could actually work for distances between in objects, even of different types, for instance between cores and caches. The public API doesn't enforce the same types for objects, we'll just need some internal tweaks.
