### ISSUE TITLE
"__acc_compiled" is undefined, OpenMPI build gives undefined reference

### ISSUE THREAD

**Issue by cponder** [open-mpi/hwloc#691]
I'm building HWLoc 2.11.2 and OpenMPI 5.0.5 on 
```
Rocky Linux release 9.3 (Blue Onyx)
```
I build the HWLoc externally so I can control the build-flags more directly, and run all the regression-tests on it.
I use this flag with the OpenMPI
```
--with-hwloc=$HWLOC"
```
pointing to the installation directory. The "configure" phase, though, gives me the message
```
checking for hwloc.h... yes
checking for hwloc_topology_init... no
configure: error: External hwloc requested but not found.
```
The config.log has this explanation
```
/usr/bin/ld: ...../lib/libhwloc.so: undefined reference to `__acc_compiled'
```
and running the command
```
nm libhwloc.so.15.8.1 | fgrep acc_compile
```
shows
```
U __acc_compiled
```
I built the HWLoc using the nvc flags
```
-acc -gpu=ccnative,cuda12.6
```
Is there some other setting I need to make?

**Comment by bgoglin** [comment]
Hello. What about another compiler or different nvc flags? I don't have any problem building on Rocky 9 here.

**Comment by cponder** [comment]
Can you show me what flags you use for the HWLoc? Then I can compare.
Also, what does this command giev you?
```
nm libhwloc.so.15.8.1 | fgrep acc_compile
```

**Comment by bgoglin** [comment]
I don't use any flag, and I don't use nvc either. I don't have any acc_compile symbol in the lib. This is likely related to your "-acc" option? There's no OpenACC inside hwloc.
