### ISSUE TITLE
Discrepancy between the implementation and the documentation on the return value of hwloc_bitmap_asprintf()

### ISSUE THREAD

**Issue by oaumage** [open-mpi/hwloc#694]
Hi,

As of commit #ac77f17 on the master branch, the documentation on the return value of hwloc_bitmap_asprintf() reads as "return 0 on success, -1 on error.", while it is implemented as `return hwloc_bitmap_snprintf(buf, len+1, set);`, thus it returns the length of the string in case of success.

Best regards,
--
Olivier Aumage

**Comment by bgoglin** [comment]
Yes, I discovered that while documenting these functions yesterday, but I didn't have time to finish reviewing other instances of asprintf() we may have somewhere in the API, will be fixed soon.
