### ISSUE TITLE
win32 support for more than 32 cores

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#74]
Windows support for more than 32 cores was fixed in 1.4.2 (ticket #70) but it's broken in win32 because windows report crappy affinity info. See Remarks in
  http://msdn.microsoft.com/en-us/library/windows/desktop/dd405488%28v=vs.85%29.aspx

On a 48 core machine, hwloc reports a big warning and ignores all objects that should contain bits >= 32.
  http://www.open-mpi.org/community/lists/hwloc-devel/2012/05/3054.php

That's likely not very important, but somebody may want to dig into this.

**Comment by bgoglin** [comment]
We're fixing processor group support for 64bits windows but the 32bits API is just too broken.
