### ISSUE TITLE
cmake support for native Windows build

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#88]
Shiqing (former OMPI windows builder) sent a draft of patch (a couple months ago) to enable native Windows build with cmake.

**Comment by emmenlau** [comment]
Thanks a lot @bgoglin for the positive response!

I'm under the impression that the license (MIT) applies here and would allow adopting the code. Furthermore, I'm under the impression that its in the best interest of vcpkg that more and more upstream projects adopt cmake. At least in my typical work, more than 90% of projects nowadays have native cmake support or at least provide cmake build instructions in a `contrib` section.

For my needs, I use hwloc as a prerequisite of [oneTBB](https://github.com/oneapi-src/oneTBB). Therefore I _only_ need the core library, no tools. oneTBB provides a cmake build, so I think that many users of oneTBB would be happy if hwloc would provide (at least basic) cmake support.

I also saw that vcpkg is replacing some definitions in the windows `config.h`. There is a corresponding code block in https://github.com/microsoft/vcpkg/blob/a79d4a8ec7ae4464eb22f6af23e277882a67595d/ports/hwloc/CMakeLists.txt#L10. Furthermore they make some changes again in https://github.com/microsoft/vcpkg/blob/a79d4a8ec7ae4464eb22f6af23e277882a67595d/ports/hwloc/portfile.cmake#L19. Both files are written in cmake syntax. Note that this refers to hwloc 2.2.0, and possibly the changes are just not needed anymore in newer hwloc?

I did apply the changes from `CMakeLists.txt`, but _not_ the ones from `portfile.cmake`, and can confirm that I got a working shared library build when building with Visual Studio 2019 v16.11.5 and also with ClangCl 13.0.0 from upstream LLVM on Windows.
