### ISSUE TITLE
combine linux sysfs, devicetree and /proc/cpuinfo

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#95]
The devicetree is currently only used when no caches were detected from sysfs, which is very rare. When it's used, it may detect things that end up being ignored because sysfs or /proc/cpuinfo added different things first.

We recently got some report about a FreeScale P4080 machine where Linux reports L2/L3 with size=0 while the devicetree contains better info. We must improve this.

/proc/cpuinfo is already well used: we gather everything and make it available to others (instead of directly adding objects to the topology).

We should do the same for sysfs and the devicetree: detect everything, create objects, keep them in the linux backend, compare what we got from all sources, keep/merge the best information, and then only add objects to the topology.

Brice

**Comment by bgoglin** [comment]
Devicetree won't be much useful in the future (#96). And we already have good collaboration between sysfs (vast majority of the discovery) and /proc/cpuinfo (only cpumodel info etc).
