### ISSUE TITLE
more generic device-tree support

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/hwloc#96]
We got a report from a FreeScale P4080 user where hwloc doesn't find anything about L2 and L3 in the device tree. The reasons are:
- the current code expects a handle in the l2-cache while this platform has a l2-cache sub-directory instead.
- the l3 is under /proc/device-tree/soc@ffe000000/l3-cache-controller@10000/ while we only look in /proc/device-tree/cpus for now

These files contain better info than Linux (it sees L2/L3 but doesn't find the cache sizes).

I don't know how standard these directories/files are. And the device-tree code is hard to understand. So it's not clear what how much time we need/should spend on this.

The P4080 is documented at
http://www.freescale.com/webapp/sps/site/prod_summary.jsp?code=P4080

Hopefully the new ACPI PPTT table that ARM is pushing will make device-tree useless on ARM.

**Comment by bgoglin** [comment]
Recent POWER don't need devicetree anymore, sysfs has what we need. ARM devicetree is currently disabled on Linux and it looks ACPI PPTT will bring all we need in sysfs.
